Repository OCA/web, pull requests merged in 2018-02, with the labels that each got.

#854 [IMP] web_dashboard_tile: reduce computation time
  web_dashboard_tile/models/tile_tile.py
Labels: enhancement, needs review

#873 [FIX] web_responsive : fixed the issue of fullscreen
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/static/src/less/main.less
Labels: bug, needs review

#876 [11.0][MIG] web_tree_many2one_clickable
  web_tree_many2one_clickable/README.rst
  web_tree_many2one_clickable/__init__.py
  web_tree_many2one_clickable/__manifest__.py
  web_tree_many2one_clickable/static/description/icon.png
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
  web_tree_many2one_clickable/static/src/xml/assets.xml
Labels: needs review
