Repository OCA/web, pull requests merged in 2018-10, with the labels that each got.

#651 [FIX] Search more always visible even if results below limit
  web_m2x_options/static/src/js/form.js
Labels: needs review

#1028 [10.0][MIG] web_menu_navbar_needaction
  web_menu_navbar_needaction/README.rst
  web_menu_navbar_needaction/__init__.py
  web_menu_navbar_needaction/__manifest__.py
  web_menu_navbar_needaction/data/ir_config_parameter.xml
  web_menu_navbar_needaction/data/ir_ui_menu.xml
  web_menu_navbar_needaction/models/__init__.py
  web_menu_navbar_needaction/models/ir_ui_menu.py
  web_menu_navbar_needaction/readme/CONFIGURE.rst
  web_menu_navbar_needaction/readme/CONTRIBUTORS.rst
  web_menu_navbar_needaction/readme/DESCRIPTION.rst
  web_menu_navbar_needaction/static/description/index.html
  web_menu_navbar_needaction/static/src/css/web_menu_navbar_needaction.css
  web_menu_navbar_needaction/static/src/js/web_menu_navbar_needaction.js
  web_menu_navbar_needaction/tests/test_web_menu_navbar_needaction.py
  web_menu_navbar_needaction/views/ir_ui_menu.xml
  web_menu_navbar_needaction/views/templates.xml
Labels: needs review

#1073 [10.0][FIX] web_notify: function declaration
  web_notify/static/src/js/notification.js
Labels: needs review

#1074 [MIG] web_editor_background_color: Migrate to v11
  web_editor_background_color/README.rst
  web_editor_background_color/__init__.py
  web_editor_background_color/__manifest__.py
  web_editor_background_color/i18n/ca.po
  web_editor_background_color/i18n/es.po
  web_editor_background_color/i18n/fr.po
  web_editor_background_color/i18n/sl.po
  web_editor_background_color/i18n/web_editor_background_color.pot
  web_editor_background_color/readme/CONTRIBUTORS.rst
  web_editor_background_color/readme/CREDITS.rst
  web_editor_background_color/readme/DESCRIPTION.rst
  web_editor_background_color/readme/USAGE.rst
  web_editor_background_color/static/description/icon.png
  web_editor_background_color/static/src/css/background_color.less
  web_editor_background_color/static/src/js/background_color.js
  web_editor_background_color/static/src/lib/bootstrap-colorpicker/bootstrap-colorpicker.css
  web_editor_background_color/static/src/lib/bootstrap-colorpicker/bootstrap-colorpicker.js
  web_editor_background_color/static/src/xml/colorpicker.xml
  web_editor_background_color/templates/assets.xml
Labels: needs fixing

#1083 [FIX] don't fail if there's no parent (any more)
  web_export_view/static/src/js/web_export_view.js
Labels: needs review

#1060 [12.0][MIG] web_favicon
  web_favicon/README.rst
  web_favicon/__init__.py
  web_favicon/__manifest__.py
  web_favicon/controllers/__init__.py
  web_favicon/controllers/web_favicon.py
  web_favicon/i18n/da.po
  web_favicon/i18n/de.po
  web_favicon/i18n/es.po
  web_favicon/i18n/hr.po
  web_favicon/i18n/nl_NL.po
  web_favicon/i18n/pt_BR.po
  web_favicon/i18n/web_favicon.pot
  web_favicon/models/__init__.py
  web_favicon/models/res_company.py
  web_favicon/readme/CONFIGURE.rst
  web_favicon/readme/DESCRIPTION.rst
  web_favicon/readme/ROADMAP.rst
  web_favicon/static/description/icon.png
  web_favicon/static/description/index.html
  web_favicon/static/src/img/android-chrome-144x144.png
  web_favicon/static/src/img/android-chrome-192x192.png
  web_favicon/static/src/img/android-chrome-36x36.png
  web_favicon/static/src/img/android-chrome-48x48.png
  web_favicon/static/src/img/android-chrome-72x72.png
  web_favicon/static/src/img/android-chrome-96x96.png
  web_favicon/static/src/img/apple-touch-icon-114x114.png
  web_favicon/static/src/img/apple-touch-icon-120x120.png
  web_favicon/static/src/img/apple-touch-icon-144x144.png
  web_favicon/static/src/img/apple-touch-icon-152x152.png
  web_favicon/static/src/img/apple-touch-icon-180x180.png
  web_favicon/static/src/img/apple-touch-icon-57x57.png
  web_favicon/static/src/img/apple-touch-icon-60x60.png
  web_favicon/static/src/img/apple-touch-icon-72x72.png
  web_favicon/static/src/img/apple-touch-icon-76x76.png
  web_favicon/static/src/img/apple-touch-icon-precomposed.png
  web_favicon/static/src/img/apple-touch-icon.png
  web_favicon/static/src/img/browserconfig.xml
  web_favicon/static/src/img/favicon-16x16.png
  web_favicon/static/src/img/favicon-32x32.png
  web_favicon/static/src/img/favicon-96x96.png
  web_favicon/static/src/img/favicon.ico
  web_favicon/static/src/img/manifest.json
  web_favicon/static/src/img/master_original_favicon.png
  web_favicon/static/src/img/master_original_favicon.svg
  web_favicon/static/src/img/mstile-144x144.png
  web_favicon/static/src/img/mstile-150x150.png
  web_favicon/static/src/img/mstile-310x150.png
  web_favicon/static/src/img/mstile-310x310.png
  web_favicon/static/src/img/mstile-70x70.png
  web_favicon/static/src/img/website_favicon_sample.html
  web_favicon/tests/__init__.py
  web_favicon/tests/test_web_favicon.py
  web_favicon/views/res_company.xml
  web_favicon/views/templates.xml
Labels: needs review

#1093 fixup! [IMP] web_widget_x2many_2d_matrix: New option field_att_<name>
  web_widget_x2many_2d_matrix/static/src/js/web_widget_x2many_2d_matrix.js
Labels: needs review

#1087 [11.0][FIX] web_timeline: add_events call and add jsdocs
  web_timeline/__manifest__.py
  web_timeline/static/src/js/timeline_canvas.js
  web_timeline/static/src/js/timeline_controller.js
  web_timeline/static/src/js/timeline_model.js
  web_timeline/static/src/js/timeline_renderer.js
  web_timeline/static/src/js/timeline_view.js
Labels: needs review

#820 [10.0][MIG] web_ckeditor4: migration to 10.0
  web_ckeditor4/README.rst
  web_ckeditor4/__manifest__.py
  web_ckeditor4/models/ckeditor_monkeypatch.py
  web_ckeditor4/static/src/css/web_ckeditor4.css
  web_ckeditor4/static/src/js/web_ckeditor4.js
  web_ckeditor4/static/src/js/web_ckeditor4_formview.js
  web_ckeditor4/views/qweb.xml
Labels: work in progress

#1061 [12.0][MIG] web_disable_export_group
  web_disable_export_group/README.rst
  web_disable_export_group/__init__.py
  web_disable_export_group/__manifest__.py
  web_disable_export_group/i18n/web_disable_export_group.pot
  web_disable_export_group/models/__init__.py
  web_disable_export_group/models/ir_http.py
  web_disable_export_group/readme/CONFIGURE.rst
  web_disable_export_group/readme/CONTRIBUTORS.rst
  web_disable_export_group/readme/DESCRIPTION.rst
  web_disable_export_group/readme/USAGE.rst
  web_disable_export_group/security/groups.xml
  web_disable_export_group/static/description/index.html
  web_disable_export_group/static/src/js/disable_export_group.js
  web_disable_export_group/templates/assets.xml
Labels: needs review

#1094 [11.0] web_advanced_search: fix initialization of 1st domain node + add changelog
  web_advanced_search/README.rst
  web_advanced_search/__manifest__.py
  web_advanced_search/readme/CONTRIBUTORS.rst
  web_advanced_search/readme/HISTORY.rst
  web_advanced_search/static/description/index.html
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: needs review
