Repository OCA/web, pull requests merged in 2019-02, with the labels that each got.

#1146 [12.0] [MIG] web_widget_x2many_2d_matrix_example
  web_widget_x2many_2d_matrix_example/README.rst
  web_widget_x2many_2d_matrix_example/__init__.py
  web_widget_x2many_2d_matrix_example/__manifest__.py
  web_widget_x2many_2d_matrix_example/demo/x2m.demo.csv
  web_widget_x2many_2d_matrix_example/i18n/web_widget_x2many_2d_matrix_example.pot
  web_widget_x2many_2d_matrix_example/models/__init__.py
  web_widget_x2many_2d_matrix_example/models/x2m_demo.py
  web_widget_x2many_2d_matrix_example/readme/CONTRIBUTORS.rst
  web_widget_x2many_2d_matrix_example/readme/DESCRIPTION.rst
  web_widget_x2many_2d_matrix_example/security/ir.model.access.csv
  web_widget_x2many_2d_matrix_example/static/description/icon.png
  web_widget_x2many_2d_matrix_example/views/x2m_demo.xml
  web_widget_x2many_2d_matrix_example/wizard/__init__.py
  web_widget_x2many_2d_matrix_example/wizard/x2m_matrix.py
  web_widget_x2many_2d_matrix_example/wizard/x2m_matrix.xml
Labels: approved, needs review, ready to merge

#1171 [FIX] web_responsive: Skip re-search when not writing and make app icons and search results middle-button-clickable
  web_responsive/static/src/js/web_responsive.js
  web_responsive/static/src/xml/apps.xml
Labels: approved, needs review

#1151 [11.0][ADD] web_tree_resize_column: Resize columns in tree views
  web_tree_resize_column/README.rst
  web_tree_resize_column/__init__.py
  web_tree_resize_column/__manifest__.py
  web_tree_resize_column/readme/CONTRIBUTORS.rst
  web_tree_resize_column/readme/CREDITS.rst
  web_tree_resize_column/readme/DESCRIPTION.rst
  web_tree_resize_column/readme/USAGE.rst
  web_tree_resize_column/static/lib/resizableColumns/LICENSE
  web_tree_resize_column/static/lib/resizableColumns/jQuery.resizableColumns.js
  web_tree_resize_column/static/src/js/backend.js
  web_tree_resize_column/templates/assets.xml
Labels: approved, needs review, ready to merge

#1192 [FIX] web_widget_bokeh_chart
  web_widget_bokeh_chart/static/src/css/custom-bokeh.css
  web_widget_bokeh_chart/views/web_widget_bokeh_chart.xml
Labels: approved

#1183 [12.0][ADD] web_edit_user_filter: Easy adjust user filters and facets
  web_edit_user_filter/README.rst
  web_edit_user_filter/__init__.py
  web_edit_user_filter/__manifest__.py
  web_edit_user_filter/models/__init__.py
  web_edit_user_filter/models/ir_filters.py
  web_edit_user_filter/readme/CONTRIBUTORS.rst
  web_edit_user_filter/readme/DESCRIPTION.rst
  web_edit_user_filter/readme/ROADMAP.rst
  web_edit_user_filter/readme/USAGE.rst
  web_edit_user_filter/static/description/edit_facet.png
  web_edit_user_filter/static/src/js/backend.js
  web_edit_user_filter/static/src/scss/backend.scss
  web_edit_user_filter/static/src/xml/backend.xml
  web_edit_user_filter/templates/assets.xml
  web_edit_user_filter/tests/__init__.py
  web_edit_user_filter/tests/test_edit_user_filter.py
Labels: approved, needs review, ready to merge

#1193 [12.0][IMP] web_widget_x2many_2d_matrix: center header cell
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/static/src/css/web_widget_x2many_2d_matrix.css
  web_widget_x2many_2d_matrix/static/src/js/2d_matrix_renderer.js
  web_widget_x2many_2d_matrix/static/src/scss/web_widget_x2many_2d_matrix.scss
  web_widget_x2many_2d_matrix/views/assets.xml
Labels: approved

#1086 12.0 mig web m2x options
  web_m2x_options/README.rst
  web_m2x_options/__init__.py
  web_m2x_options/__manifest__.py
  web_m2x_options/i18n/ar.po
  web_m2x_options/i18n/de.po
  web_m2x_options/i18n/es.po
  web_m2x_options/i18n/fi.po
  web_m2x_options/i18n/fr.po
  web_m2x_options/i18n/hr.po
  web_m2x_options/i18n/it.po
  web_m2x_options/i18n/nl_NL.po
  web_m2x_options/i18n/pt_BR.po
  web_m2x_options/i18n/sl.po
  web_m2x_options/i18n/tr.po
  web_m2x_options/i18n/web_m2x_options.pot
  web_m2x_options/models/__init__.py
  web_m2x_options/models/ir_config_parameter.py
  web_m2x_options/readme/CONTRIBUTORS.rst
  web_m2x_options/readme/DESCRIPTION.rst
  web_m2x_options/readme/ROADMAP.rst
  web_m2x_options/readme/USAGE.rst
  web_m2x_options/static/description/icon.png
  web_m2x_options/static/description/index.html
  web_m2x_options/static/src/js/form.js
  web_m2x_options/static/src/xml/base.xml
  web_m2x_options/views/view.xml
Labels: needs review

#1197 [MIG] web_advanced_search: Migrate to v12
  web_advanced_search/README.rst
  web_advanced_search/__init__.py
  web_advanced_search/__manifest__.py
  web_advanced_search/i18n/da.po
  web_advanced_search/i18n/de.po
  web_advanced_search/i18n/es.po
  web_advanced_search/i18n/fr.po
  web_advanced_search/i18n/hr.po
  web_advanced_search/i18n/nl.po
  web_advanced_search/i18n/nl_NL.po
  web_advanced_search/i18n/pt_BR.po
  web_advanced_search/i18n/web_advanced_search.pot
  web_advanced_search/readme/CONTRIBUTORS.rst
  web_advanced_search/readme/DESCRIPTION.rst
  web_advanced_search/readme/HISTORY.rst
  web_advanced_search/readme/ROADMAP.rst
  web_advanced_search/readme/USAGE.rst
  web_advanced_search/static/description/icon.png
  web_advanced_search/static/description/index.html
  web_advanced_search/static/src/js/human_domain.js
  web_advanced_search/static/src/js/web_advanced_search.js
  web_advanced_search/static/src/xml/web_advanced_search.xml
  web_advanced_search/views/templates.xml
Labels: approved, needs review

#1200 [ADD] web_widget_domain_editor_dialog: New module
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/__init__.py
  web_widget_domain_editor_dialog/__manifest__.py
  web_widget_domain_editor_dialog/i18n/es.po
  web_widget_domain_editor_dialog/i18n/web_widget_domain_editor_dialog.pot
  web_widget_domain_editor_dialog/readme/CONTRIBUTORS.rst
  web_widget_domain_editor_dialog/readme/DESCRIPTION.rst
  web_widget_domain_editor_dialog/readme/USAGE.rst
  web_widget_domain_editor_dialog/static/description/index.html
  web_widget_domain_editor_dialog/static/src/img/behaviour.gif
  web_widget_domain_editor_dialog/static/src/js/basic_fields.js
  web_widget_domain_editor_dialog/static/src/js/widget_domain_editor_dialog.js
  web_widget_domain_editor_dialog/views/templates.xml
Labels: approved

#1204 [FIX][12.0] web_disable_export_group: Tests
  web_disable_export_group/tests/test_disable_export_group.py
Labels: approved, needs review
