Repository OCA/web, pull requests merged in 2019-05, with the labels that each got.

#1263 [10][IMP] switch company warning : Add detection of switching database
  web_switch_company_warning/README.rst
  web_switch_company_warning/__manifest__.py
  web_switch_company_warning/static/src/js/switch_company_warning.js
  web_switch_company_warning/static/src/xml/switch_company_warning.xml
Labels: approved, ready to merge

#1276 [10.0] [FIX] web_widget_text_markdown: convert markdown only when widget attr is present in tree view
  web_widget_text_markdown/static/src/js/web_widget_text_markdown.js
Labels: approved

#1269 12.0 mig web_export_view
  web_export_view/README.rst
  web_export_view/__init__.py
  web_export_view/__manifest__.py
  web_export_view/controllers/__init__.py
  web_export_view/controllers/controllers.py
  web_export_view/i18n/da.po
  web_export_view/i18n/de.po
  web_export_view/i18n/es.po
  web_export_view/i18n/hr.po
  web_export_view/i18n/nl_NL.po
  web_export_view/i18n/pt_BR.po
  web_export_view/i18n/web_export_view.pot
  web_export_view/i18n/zh_CN.po
  web_export_view/readme/CONFIGURATION.rst
  web_export_view/readme/CONFIGURE.rst
  web_export_view/readme/CONTRIBUTORS.rst
  web_export_view/readme/DESCRIPTION.rst
  web_export_view/readme/ROADMAP.rst
  web_export_view/readme/USAGE.rst
  web_export_view/security/groups.xml
  web_export_view/static/description/icon.png
  web_export_view/static/description/index.html
  web_export_view/static/src/js/web_export_view.js
  web_export_view/static/src/xml/web_export_view_template.xml
  web_export_view/views/web_export_view_view.xml
Labels: approved

#1243 [11.0][MIG] web_access_rule_buttons
  web_access_rule_buttons/README.rst
  web_access_rule_buttons/__init__.py
  web_access_rule_buttons/__manifest__.py
  web_access_rule_buttons/models/__init__.py
  web_access_rule_buttons/models/models.py
  web_access_rule_buttons/readme/CONTRIBUTORS.rst
  web_access_rule_buttons/readme/DESCRIPTION.rst
  web_access_rule_buttons/readme/USAGE.rst
  web_access_rule_buttons/static/src/js/form_controller.js
  web_access_rule_buttons/tests/__init__.py
  web_access_rule_buttons/tests/test_access_rule_buttons.py
  web_access_rule_buttons/views/web_access_rule_buttons.xml
Labels: approved, ready to merge

#1253 [12.0][ADD] web_company_color
  web_company_color/README.rst
  web_company_color/__init__.py
  web_company_color/__manifest__.py
  web_company_color/hooks.py
  web_company_color/models/__init__.py
  web_company_color/models/res_company.py
  web_company_color/readme/CONTRIBUTORS.rst
  web_company_color/readme/DESCRIPTION.rst
  web_company_color/readme/ROADMAP.rst
  web_company_color/readme/USAGE.rst
  web_company_color/static/description/index.html
  web_company_color/tests/__init__.py
  web_company_color/tests/test_res_company.py
  web_company_color/utils.py
  web_company_color/view/assets.xml
  web_company_color/view/res_company.xml
Labels: approved, needs fixing

#1291 [9.0] Mail thread is an AbstractModel, not a Model
  web_widget_digitized_signature/models/mail_thread.py
Labels: approved

#1290 [12.0][MIG] web_tree_many2one_clickable
  web_tree_many2one_clickable/README.rst
  web_tree_many2one_clickable/__init__.py
  web_tree_many2one_clickable/__manifest__.py
  web_tree_many2one_clickable/i18n/web_tree_many2one_clickable.pot
  web_tree_many2one_clickable/readme/CONFIGURATION.rst
  web_tree_many2one_clickable/readme/CONTRIBUTORS.rst
  web_tree_many2one_clickable/readme/DESCRIPTION.rst
  web_tree_many2one_clickable/static/description/icon.png
  web_tree_many2one_clickable/static/description/index.html
  web_tree_many2one_clickable/static/src/css/web_tree_many2one_clickable.scss
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
  web_tree_many2one_clickable/views/assets.xml
Labels: approved

#1294 [12.0][IMP] web_tree_many2one_clickable: Readme - USAGE
  web_tree_many2one_clickable/README.rst
  web_tree_many2one_clickable/readme/DESCRIPTION.rst
  web_tree_many2one_clickable/readme/USAGE.rst
  web_tree_many2one_clickable/static/description/index.html
  web_tree_many2one_clickable/static/img/clickable.gif
Labels: approved
