Repository OCA/web, pull requests merged in 2019-03, with the labels that each got.

#974 [11.0][MIG] web_drop_target
  web_drop_target/README.rst
  web_drop_target/__init__.py
  web_drop_target/__manifest__.py
  web_drop_target/readme/CONTRIBUTORS.rst
  web_drop_target/readme/DESCRIPTION.rst
  web_drop_target/readme/DEVELOP.rst
  web_drop_target/readme/ROADMAP.rst
  web_drop_target/readme/USAGE.rst
  web_drop_target/static/description/icon.png
  web_drop_target/static/lib/base64js.min.js
  web_drop_target/static/src/css/web_drop_target.css
  web_drop_target/static/src/js/web_drop_target.js
  web_drop_target/views/templates.xml
Labels: approved, needs review, ready to merge

#955 [REM] web_widget_datepicker_options: No longer needed
  setup/web_widget_datepicker_options/odoo/addons/web_widget_datepicker_options
  setup/web_widget_datepicker_options/setup.cfg
  setup/web_widget_datepicker_options/setup.py
  web_widget_datepicker_options/README.rst
  web_widget_datepicker_options/__init__.py
  web_widget_datepicker_options/__manifest__.py
  web_widget_datepicker_options/i18n/web_widget_datepicker_options.pot
  web_widget_datepicker_options/static/description/icon.png
  web_widget_datepicker_options/static/description/icon.svg
  web_widget_datepicker_options/static/src/js/datepicker.js
  web_widget_datepicker_options/views/assets.xml
Labels: needs review

#690 [FIX][WIP] Avoid to save sign every time form is saved
  web_widget_digitized_signature/static/lib/jSignature/jSignatureCustom.js
  web_widget_digitized_signature/static/src/js/digital_sign.js
Labels: approved, ready to merge

#1213 [FIX][web_menu_navbar_needaction] mute logger for assertRaises
  web_menu_navbar_needaction/tests/test_web_menu_navbar_needaction.py
Labels: approved, needs review

#1211 [11.0][FIX] web_widget_bokeh_chart: fix grahs expanding outside the container element.
  web_widget_bokeh_chart/__manifest__.py
  web_widget_bokeh_chart/static/src/css/custom-bokeh.css
  web_widget_bokeh_chart/static/src/less/custom-bokeh.less
  web_widget_bokeh_chart/views/web_widget_bokeh_chart.xml
Labels: approved

#1209 [FIX] web_drop_target
  web_drop_target/__manifest__.py
  web_drop_target/static/src/js/web_drop_target.js
Labels: approved

#1218 [12.0][Mig] web_searchbar_full_width
  web_searchbar_full_width/README.rst
  web_searchbar_full_width/__init__.py
  web_searchbar_full_width/__manifest__.py
  web_searchbar_full_width/i18n/web_searchbar_full_width.pot
  web_searchbar_full_width/readme/CONTRIBUTORS.rst
  web_searchbar_full_width/readme/DESCRIPTION.rst
  web_searchbar_full_width/readme/USAGE.rst
  web_searchbar_full_width/static/description/icon.png
  web_searchbar_full_width/static/description/index.html
  web_searchbar_full_width/static/description/preview.png
  web_searchbar_full_width/static/src/scss/web_searchbar_full_width.scss
  web_searchbar_full_width/views/templates.xml
Labels: approved

#1225 [10.0] web_ckeditor4: fix no re-init on form discard
  web_ckeditor4/__manifest__.py
  web_ckeditor4/static/src/js/web_ckeditor4.js
  web_ckeditor4/static/src/js/web_ckeditor4_config.js
  web_ckeditor4/templates/assets.xml
  web_ckeditor4/views/qweb.xml
Labels: approved, needs review, ready to merge
