Repository OCA/web, pull requests merged in 2019-11, with the labels that each got.

#1421 web_tree_image_tooltip: add image width and height limit in tooltip
  web_tree_image_tooltip/static/src/js/tooltip.js
  web_tree_image_tooltip/static/src/scss/common.scss
Labels: approved, ready to merge

#1371 [12.0][ADD] web_widget_dropdown_dynamic
  web_widget_dropdown_dynamic/__init__.py
  web_widget_dropdown_dynamic/__manifest__.py
  web_widget_dropdown_dynamic/readme/CONTRIBUTORS.rst
  web_widget_dropdown_dynamic/readme/DESCRIPTION.rst
  web_widget_dropdown_dynamic/readme/ROADMAP.rst
  web_widget_dropdown_dynamic/readme/USAGE.rst
  web_widget_dropdown_dynamic/static/src/js/basic_model.js
  web_widget_dropdown_dynamic/static/src/js/field_dynamic_dropdown.js
  web_widget_dropdown_dynamic/static/tests/web_widget_dropdown_dynamic_tests.js
  web_widget_dropdown_dynamic/templates/assets.xml
  web_widget_dropdown_dynamic_example/__init__.py
  web_widget_dropdown_dynamic_example/__manifest__.py
  web_widget_dropdown_dynamic_example/models/__init__.py
  web_widget_dropdown_dynamic_example/models/web_widget_dropdown_dynamic_example.py
  web_widget_dropdown_dynamic_example/views/web_widget_dropdown_dynamic_example.xml
Labels: approved, ready to merge

#1369 [12.0][NEW] web_widget_plotly_chart
  requirements.txt
  web_widget_plotly_chart/README.rst
  web_widget_plotly_chart/__init__.py
  web_widget_plotly_chart/__manifest__.py
  web_widget_plotly_chart/readme/CONTRIBUTORS.rst
  web_widget_plotly_chart/readme/CREDITS.rst
  web_widget_plotly_chart/readme/DESCRIPTION.rst
  web_widget_plotly_chart/readme/INSTALL.rst
  web_widget_plotly_chart/readme/USAGE.rst
  web_widget_plotly_chart/static/description/example.png
  web_widget_plotly_chart/static/description/index.html
  web_widget_plotly_chart/static/lib/plotly/plotly-latest.min.js
  web_widget_plotly_chart/static/src/js/widget_plotly.js
  web_widget_plotly_chart/views/web_widget_plotly_chart.xml
Labels: approved

#1433 [12.0][IMP] web_responsive: Scroll menu sections on mobile
  web_responsive/static/src/css/web_responsive.scss
Labels: approved

#1442 [FIX] web_responsive: modify action handling
  web_responsive/static/src/js/web_responsive.js
Labels: approved, bug

#1448 [FIX] web_widget_x2many_2d_matrix: Wrong widget
  web_widget_x2many_2d_matrix/static/src/js/abstract_view_matrix_limit_extend.js
Labels: approved
