Repository OCA/web, pull requests merged in 2019-01, with the labels that each got.

#1030 [10.0][MIG] web_search_autocomplete_prefetch
  web_search_autocomplete_prefetch/README.rst
  web_search_autocomplete_prefetch/__init__.py
  web_search_autocomplete_prefetch/__manifest__.py
  web_search_autocomplete_prefetch/i18n/es.po
  web_search_autocomplete_prefetch/i18n/fi.po
  web_search_autocomplete_prefetch/i18n/sl.po
  web_search_autocomplete_prefetch/i18n/tr.po
  web_search_autocomplete_prefetch/i18n/web_search_autocomplete_prefetch.pot
  web_search_autocomplete_prefetch/images/web_search_autocomplete_prefetch.png
  web_search_autocomplete_prefetch/readme/CONFIGURE.rst
  web_search_autocomplete_prefetch/readme/CONTRIBUTORS.rst
  web_search_autocomplete_prefetch/readme/DESCRIPTION.rst
  web_search_autocomplete_prefetch/static/description/icon.png
  web_search_autocomplete_prefetch/static/description/index.html
  web_search_autocomplete_prefetch/static/src/js/web_search_autocomplete_prefetch.js
  web_search_autocomplete_prefetch/views/base_view.xml
  web_search_autocomplete_prefetch/views/templates.xml
Labels: approved, needs review, ready to merge

#1135 [web_timeline][IMP] Add margin support in web_timeline
  web_timeline/README.rst
  web_timeline/__manifest__.py
  web_timeline/readme/CONFIGURE.rst
  web_timeline/static/src/js/timeline_view.js
Labels: approved

#1118 [FIX] open option on many2many_tags
  web_m2x_options/static/src/js/form.js
Labels: approved, needs review, ready to merge

#1107 [ADD] web_widget_url_advanced
  web_widget_url_advanced/README.rst
  web_widget_url_advanced/__init__.py
  web_widget_url_advanced/__manifest__.py
  web_widget_url_advanced/readme/CONTRIBUTORS.rst
  web_widget_url_advanced/readme/DESCRIPTION.rst
  web_widget_url_advanced/readme/USAGE.rst
  web_widget_url_advanced/static/description/after.png
  web_widget_url_advanced/static/description/before.png
  web_widget_url_advanced/static/description/icon.png
  web_widget_url_advanced/static/description/index.html
  web_widget_url_advanced/static/src/js/url_widget.js
  web_widget_url_advanced/templates/assets.xml
Labels: approved, needs review, ready to merge

#1066 [MIG] web_responsive: Migrate to v12 and refactor
  web_responsive/README.rst
  web_responsive/__init__.py
  web_responsive/__manifest__.py
  web_responsive/i18n/da.po
  web_responsive/i18n/de.po
  web_responsive/i18n/es.po
  web_responsive/i18n/hr.po
  web_responsive/i18n/pt_BR.po
  web_responsive/i18n/web_responsive.pot
  web_responsive/models/__init__.py
  web_responsive/models/res_users.py
  web_responsive/readme/CONTRIBUTORS.rst
  web_responsive/readme/DESCRIPTION.rst
  web_responsive/readme/ROADMAP.rst
  web_responsive/readme/USAGE.rst
  web_responsive/static/description/icon.png
  web_responsive/static/description/index.html
  web_responsive/static/src/css/web_responsive.scss
  web_responsive/static/src/js/web_responsive.js
  web_responsive/static/src/xml/apps.xml
  web_responsive/static/src/xml/form_view.xml
  web_responsive/static/src/xml/navbar.xml
  web_responsive/tests/__init__.py
  web_responsive/tests/test_res_users.py
  web_responsive/views/assets.xml
  web_responsive/views/res_users.xml
  web_responsive/views/web.xml
Labels: needs review

#1152 [FIX] web_advanced_search: Ignore field domain
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: approved, bug, needs review

#1154 [FIX] web_decimal_numpad_dot: Fix inconsistent behavior
  web_decimal_numpad_dot/static/src/js/numpad_dot.js
Labels: approved, bug, needs review

#1155 [FIX] web_m2x_options: Fix error in tree views with many2many_tags
  web_m2x_options/static/src/js/form.js
Labels: approved, bug, needs review

#1156 [12.0][FIX] web_timeline: Reloading view
  web_timeline/__manifest__.py
  web_timeline/static/src/js/timeline_controller.js
Labels: approved

#1142 [10.0] web_advanced_search_wildcard: adds 'starts with' and 'ends with'
  web_advanced_search_wildcard/README.rst
  web_advanced_search_wildcard/i18n/fr.po
  web_advanced_search_wildcard/static/src/js/search.js
Labels: approved

#1161 [12.0] [MIG] web_widget_many2many_tags_multi_selection
  web_widget_many2many_tags_multi_selection/README.rst
  web_widget_many2many_tags_multi_selection/__init__.py
  web_widget_many2many_tags_multi_selection/__manifest__.py
  web_widget_many2many_tags_multi_selection/i18n/lt.po
  web_widget_many2many_tags_multi_selection/i18n/nl_NL.po
  web_widget_many2many_tags_multi_selection/i18n/pt_BR.po
  web_widget_many2many_tags_multi_selection/i18n/web_widget_many2many_tags_multi_selection.pot
  web_widget_many2many_tags_multi_selection/readme/CONFIGURATION.rst
  web_widget_many2many_tags_multi_selection/readme/CONTRIBUTORS.rst
  web_widget_many2many_tags_multi_selection/readme/DESCRIPTION.rst
  web_widget_many2many_tags_multi_selection/static/description/icon.png
  web_widget_many2many_tags_multi_selection/static/description/index.html
  web_widget_many2many_tags_multi_selection/static/src/js/view_form.js
  web_widget_many2many_tags_multi_selection/views/web_widget_many2many_tags_multi_selection.xml
Labels: needs review

#1164 [11.0] web_export_view: add security group
  web_export_view/README.rst
  web_export_view/__manifest__.py
  web_export_view/security/groups.xml
  web_export_view/static/src/js/web_export_view.js
Labels: approved
