Repository OCA/web, pull requests merged in 2019-12, with the labels that each got.

#1432 [FIX] web_view_calendar_column: Set license of the widget as Open Source
  web_view_calendar_column/static/src/js/calendar_renderer.js
Labels: approved

#1456 [12.0][IMP] mail_tracking: Changed form statusbar z-index
  web_responsive/static/src/css/web_responsive.scss
Labels: approved

#1452 [12.0][ADD][web_ir_actions_close_wizard_refresh_view] Add module
  web_ir_actions_close_wizard_refresh_view/README.rst
  web_ir_actions_close_wizard_refresh_view/__init__.py
  web_ir_actions_close_wizard_refresh_view/__manifest__.py
  web_ir_actions_close_wizard_refresh_view/readme/DESCRIPTION.rst
  web_ir_actions_close_wizard_refresh_view/readme/USAGE.rst
  web_ir_actions_close_wizard_refresh_view/static/description/index.html
  web_ir_actions_close_wizard_refresh_view/static/src/js/web_ir_actions_close_wizard_refresh_view.js
  web_ir_actions_close_wizard_refresh_view/templates/assets.xml
Labels: approved, ready to merge

#1404 [12.0][FIX] web_widget_x2many_2d_matrix: rendering in kanban mode
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/readme/ROADMAP.rst
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/src/js/2d_matrix_view.js
  web_widget_x2many_2d_matrix/views/assets.xml
Labels: approved, help wanted, ready to merge, work in progress

#1461 [IMP] web_widget_x2many_matrix: Sticky header, footer rows and main, …
  web_widget_x2many_2d_matrix/static/src/scss/web_widget_x2many_2d_matrix.scss
Labels: approved
