Repository OCA/web, pull requests merged in 2020-08, with the labels that each got.

#1653 [IMP] web_responsive: change search options buttons css
  web_responsive/static/src/css/web_responsive.scss
Labels: approved, bot is merging ⏳

#1654 Design improvements for the backend user interface
  web_responsive/static/src/css/web_responsive.scss
  web_responsive/static/src/img/home-menu-bg-overlay.svg
  web_responsive/static/src/js/web_responsive.js
  web_responsive/static/src/xml/apps.xml
Labels: bot is merging ⏳

#1658 [IMP][12.0] web_drop_target: Change .less to .scss
  web_drop_target/static/src/scss/web_drop_target.scss
  web_drop_target/views/templates.xml
Labels: approved, bot is merging ⏳

#1657 [IMP][13.0] web_responsive
  web_responsive/readme/CONTRIBUTORS.rst
  web_responsive/static/src/css/web_responsive.scss
  web_responsive/static/src/xml/apps.xml
Labels: approved, bot is merging ⏳

#1652 [IMP] web_advanced_search: Don't block modal filter menu
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: approved, bot is merging ⏳, ready to merge

#1592 [12.0][MIG] web_widget_float_formula
  web_widget_float_formula/__init__.py
  web_widget_float_formula/__manifest__.py
  web_widget_float_formula/i18n/web_widget_float_formula.pot
  web_widget_float_formula/readme/CONTRIBUTORS.rst
  web_widget_float_formula/readme/DESCRIPTION.rst
  web_widget_float_formula/readme/ROADMAP.rst
  web_widget_float_formula/static/description/icon.png
  web_widget_float_formula/static/src/js/web_widget_float_formula.js
  web_widget_float_formula/static/tests/js/test_web_widget_float_formula.js
  web_widget_float_formula/templates/assets.xml
Labels: approved, bot is merging ⏳

#1672 Remove wrong translation dir; module will be then translated by weblate
  web_widget_model_viewer/l18n/it.po
Labels: bot is merging ⏳
