Repository OCA/web, pull requests merged in 2020-05, with the labels that each got.

#1598 [FIX] web_timeline: Change vis-timeline library import
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.min.js
  web_timeline/static/src/js/timeline_view.js
  web_timeline/static/src/scss/web_timeline.scss
  web_timeline/views/web_timeline.xml
Labels: bot is merging ⏳

#1600 [FIX] web_timeline: Change draw_dependencies
  web_timeline/static/src/js/timeline_renderer.js
Labels: bot is merging ⏳

#1606 [FIX] web_advanced_search: Change management of relational fields
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: approved, bot is merging ⏳

#1544 [12.0][FIX] web_translate_dialog: load translation for text field
  web_translate_dialog/models/base.py
  web_translate_dialog/static/src/js/web_translate_dialog.js
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1573 [13.0][MIG] web_widget_dropdown_dynamic
  setup/web_widget_dropdown_dynamic/odoo/addons/web_widget_dropdown_dynamic
  setup/web_widget_dropdown_dynamic/setup.py
  setup/web_widget_dropdown_dynamic_example/odoo/addons/web_widget_dropdown_dynamic_example
  setup/web_widget_dropdown_dynamic_example/setup.py
  web_widget_dropdown_dynamic/README.rst
  web_widget_dropdown_dynamic/__init__.py
  web_widget_dropdown_dynamic/__manifest__.py
  web_widget_dropdown_dynamic/i18n/web_widget_dropdown_dynamic.pot
  web_widget_dropdown_dynamic/readme/CONTRIBUTORS.rst
  web_widget_dropdown_dynamic/readme/DESCRIPTION.rst
  web_widget_dropdown_dynamic/readme/USAGE.rst
  web_widget_dropdown_dynamic/static/description/icon.png
  web_widget_dropdown_dynamic/static/description/index.html
  web_widget_dropdown_dynamic/static/src/js/basic_model.js
  web_widget_dropdown_dynamic/static/src/js/field_dynamic_dropdown.js
  web_widget_dropdown_dynamic/static/tests/web_widget_dropdown_dynamic_tests.js
  web_widget_dropdown_dynamic/templates/assets.xml
  web_widget_dropdown_dynamic_example/__init__.py
  web_widget_dropdown_dynamic_example/__manifest__.py
  web_widget_dropdown_dynamic_example/i18n/web_widget_dropdown_dynamic_example.pot
  web_widget_dropdown_dynamic_example/models/__init__.py
  web_widget_dropdown_dynamic_example/models/web_widget_dropdown_dynamic_example.py
  web_widget_dropdown_dynamic_example/readme/CONTRIBUTORS.rst
  web_widget_dropdown_dynamic_example/readme/DESCRIPTION.rst
  web_widget_dropdown_dynamic_example/static/description/icon.png
  web_widget_dropdown_dynamic_example/views/web_widget_dropdown_dynamic_example.xml
Labels: approved, bot is merging ⏳, ready to merge

#1608 [IMP][13.0] web_drop_target: Change less files for scss
  web_drop_target/static/src/scss/web_drop_target.scss
  web_drop_target/views/templates.xml
Labels: approved, bot is merging ⏳
