Repository OCA/web, pull requests merged in 2020-09, with the labels that each got.

#1648 [13.0][IMP] web_notify: add channels only if not done already
  web_notify/static/src/js/web_client.js
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1677 Fix enterprise mobile bug
  web_m2x_options/static/src/js/form.js
Labels: bot is merging ⏳

#1676 [13.0][FIX] web_drop_target: improve extensibility
  web_drop_target/readme/CONTRIBUTORS.rst
  web_drop_target/static/src/js/web_drop_target.js
Labels: approved, bot is merging ⏳

#1595 [13.0][MIG] web_action_conditionable
  setup/web_action_conditionable/odoo/addons/web_action_conditionable
  setup/web_action_conditionable/setup.py
  web_action_conditionable/README.rst
  web_action_conditionable/__init__.py
  web_action_conditionable/__manifest__.py
  web_action_conditionable/i18n/es.po
  web_action_conditionable/i18n/hr.po
  web_action_conditionable/i18n/web_action_conditionable.pot
  web_action_conditionable/i18n/zh_CN.po
  web_action_conditionable/readme/CONTRIBUTORS.rst
  web_action_conditionable/readme/DESCRIPTION.rst
  web_action_conditionable/readme/USAGE.rst
  web_action_conditionable/static/description/icon.png
  web_action_conditionable/static/description/index.html
  web_action_conditionable/static/description/index.html~2eb1f1bc... [FIX] web_action_conditionable: Adapt to new api
  web_action_conditionable/static/src/js/field_one2many.js
  web_action_conditionable/templates/assets.xml
Labels: approved, bot is merging ⏳

#1681 [13.0][FIX] web_action_conditionable - Delete file
  web_action_conditionable/static/description/index.html~2eb1f1bc... [FIX] web_action_conditionable: Adapt to new api
Labels: approved, bot is merging ⏳

#1690 [12.0][FIX] web_responsive update scss
  web_responsive/static/src/css/web_responsive.scss
Labels: approved, bot is merging ⏳
