Repository OCA/web, pull requests merged in 2020-07, with the labels that each got.

#1629 [ADD] web_view_searchpanel
  web_view_searchpanel/README.rst
  web_view_searchpanel/__init__.py
  web_view_searchpanel/__manifest__.py
  web_view_searchpanel/demo/res_users_views.xml
  web_view_searchpanel/models/__init__.py
  web_view_searchpanel/models/base.py
  web_view_searchpanel/readme/CONTRIBUTORS.rst
  web_view_searchpanel/readme/DESCRIPTION.rst
  web_view_searchpanel/readme/USAGE.rst
  web_view_searchpanel/static/description/icon.png
  web_view_searchpanel/static/description/index.html
  web_view_searchpanel/static/src/js/kanban_controller.js
  web_view_searchpanel/static/src/js/kanban_renderer.js
  web_view_searchpanel/static/src/js/kanban_searchpanel.js
  web_view_searchpanel/static/src/js/kanban_view.js
  web_view_searchpanel/static/src/scss/kanban_view.scss
  web_view_searchpanel/static/src/scss/variables.scss
  web_view_searchpanel/static/src/xml/kanban.xml
  web_view_searchpanel/template/assets.xml
Labels: approved, bot is merging ⏳

#1471 [11.0][ADD] web_widget_open_tab
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/demo/res_users_view.xml
  web_widget_open_tab/readme/CONTRIBUTORS.rst
  web_widget_open_tab/readme/DESCRIPTION.rst
  web_widget_open_tab/readme/USAGE.rst
  web_widget_open_tab/static/description/icon.png
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/static/src/js/widget.js
  web_widget_open_tab/templates/assets.xml
Labels: bot is merging ⏳

#1633 web_ir_actions_act_view_reload: fix README
  web_ir_actions_act_view_reload/README.rst
  web_ir_actions_act_view_reload/readme/USAGE.rst
Labels: approved, needs fixing

#1512 [11.0][ADD] web_view_calendar_list
  web_view_calendar_list/README.rst
  web_view_calendar_list/__init__.py
  web_view_calendar_list/__manifest__.py
  web_view_calendar_list/models/__init__.py
  web_view_calendar_list/models/ir_actions_act_window_view.py
  web_view_calendar_list/models/ir_ui_view.py
  web_view_calendar_list/readme/CONTRIBUTORS.rst
  web_view_calendar_list/readme/DESCRIPTION.rst
  web_view_calendar_list/readme/USAGE.rst
  web_view_calendar_list/static/description/icon.png
  web_view_calendar_list/static/src/js/calendar_list_controller.js
  web_view_calendar_list/static/src/js/calendar_list_model.js
  web_view_calendar_list/static/src/js/calendar_list_renderer.js
  web_view_calendar_list/static/src/js/calendar_list_view.js
  web_view_calendar_list/templates/assets.xml
Labels: approved, bot is merging ⏳

#1255 [11.0][ADD] web_company_title
  web_company_title/__init__.py
  web_company_title/__manifest__.py
  web_company_title/readme/DESCRIPTION.rst
  web_company_title/static/src/js/web_company_title.js
  web_company_title/views/assets.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1639 [12.0][FIX] web_widget_open_tab: Allow to open tab on dashboards or trees inside other forms
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/demo/res_users_view.xml
  web_widget_open_tab/static/src/js/widget.js
  web_widget_open_tab/static/src/less/open_tab.less
  web_widget_open_tab/templates/assets.xml
Labels: approved, bot is merging ⏳

#1638 [12.0][MIG] web_view_calendar_list
  web_view_calendar_list/README.rst
  web_view_calendar_list/__init__.py
  web_view_calendar_list/__manifest__.py
  web_view_calendar_list/i18n/web_view_calendar_list.pot
  web_view_calendar_list/models/__init__.py
  web_view_calendar_list/models/ir_actions_act_window_view.py
  web_view_calendar_list/models/ir_ui_view.py
  web_view_calendar_list/readme/CONTRIBUTORS.rst
  web_view_calendar_list/readme/DESCRIPTION.rst
  web_view_calendar_list/readme/USAGE.rst
  web_view_calendar_list/static/description/icon.png
  web_view_calendar_list/static/description/index.html
  web_view_calendar_list/static/src/js/calendar_list_controller.js
  web_view_calendar_list/static/src/js/calendar_list_model.js
  web_view_calendar_list/static/src/js/calendar_list_renderer.js
  web_view_calendar_list/static/src/js/calendar_list_view.js
  web_view_calendar_list/templates/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1056 [8.0] [ADD] web_tree_date_search
  web_tree_date_search/README.rst
  web_tree_date_search/__init__.py
  web_tree_date_search/__openerp__.py
  web_tree_date_search/demo/demo.xml
  web_tree_date_search/i18n/fr.po
  web_tree_date_search/i18n/nl.po
  web_tree_date_search/static/description/icon.png
  web_tree_date_search/static/src/css/web_tree_date_search.css
  web_tree_date_search/static/src/img/demo.png
  web_tree_date_search/static/src/img/demo1.png
  web_tree_date_search/static/src/js/web_tree_date_search.js
  web_tree_date_search/static/src/xml/web_tree_date_search.xml
  web_tree_date_search/views/assets_backend.xml
Labels: approved, ready to merge

#1584 [12.0] [MIG] web_group_expand
  web_group_expand/README.rst
  web_group_expand/__init__.py
  web_group_expand/__manifest__.py
  web_group_expand/i18n/nl.po
  web_group_expand/i18n/web_group_expand.pot
  web_group_expand/readme/CONTRIBUTORS.rst
  web_group_expand/readme/DESCRIPTION.rst
  web_group_expand/static/description/icon.png
  web_group_expand/static/description/index.html
  web_group_expand/static/src/js/web_group_expand.js
  web_group_expand/static/src/xml/expand_buttons.xml
  web_group_expand/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#1647 [12.0][IMP] web_advanced_search: Prevent the menu from closing when using a relational field
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: approved, bot is merging ⏳

#1649 [FIX] web_view_searchpanel: Typo error on JS
  web_view_searchpanel/static/src/js/kanban_view.js
Labels: approved, bot is merging ⏳
