Repository OCA/web, pull requests merged in 2020-12, with the labels that each got.

#1698 [13.0] [MIG] web_widget_domain_editor_dialog: Migration to v13.0
  setup/web_widget_domain_editor_dialog/odoo/addons/web_widget_domain_editor_dialog
  setup/web_widget_domain_editor_dialog/setup.py
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/__init__.py
  web_widget_domain_editor_dialog/__manifest__.py
  web_widget_domain_editor_dialog/i18n/es.po
  web_widget_domain_editor_dialog/i18n/web_widget_domain_editor_dialog.pot
  web_widget_domain_editor_dialog/i18n/zh_CN.po
  web_widget_domain_editor_dialog/readme/CONTRIBUTORS.rst
  web_widget_domain_editor_dialog/readme/DESCRIPTION.rst
  web_widget_domain_editor_dialog/readme/USAGE.rst
  web_widget_domain_editor_dialog/static/description/icon.png
  web_widget_domain_editor_dialog/static/description/index.html
  web_widget_domain_editor_dialog/static/src/img/behaviour.gif
  web_widget_domain_editor_dialog/static/src/js/basic_fields.js
  web_widget_domain_editor_dialog/static/src/js/widget_domain_editor_dialog.js
  web_widget_domain_editor_dialog/views/templates.xml
Labels: approved, bot is merging ⏳

#1746 [13.0][MIG] web_pivot_computed_measure: Migration to 13.0
  setup/web_pivot_computed_measure/odoo/addons/web_pivot_computed_measure
  setup/web_pivot_computed_measure/setup.py
  web_pivot_computed_measure/README.rst
  web_pivot_computed_measure/__init__.py
  web_pivot_computed_measure/__manifest__.py
  web_pivot_computed_measure/i18n/es.po
  web_pivot_computed_measure/i18n/web_pivot_computed_measure.pot
  web_pivot_computed_measure/readme/CONTRIBUTORS.rst
  web_pivot_computed_measure/readme/DESCRIPTION.rst
  web_pivot_computed_measure/readme/ROADMAP.rst
  web_pivot_computed_measure/readme/USAGE.rst
  web_pivot_computed_measure/static/description/icon.png
  web_pivot_computed_measure/static/description/index.html
  web_pivot_computed_measure/static/src/js/pivot_controller.js
  web_pivot_computed_measure/static/src/js/pivot_model.js
  web_pivot_computed_measure/static/src/xml/web_pivot_computed_measure.xml
  web_pivot_computed_measure/view/assets.xml
Labels: approved, bot is merging ⏳

#1700 [FIX] web_pivot_computed_measure : do not raise Javascript error in case of no data
  web_pivot_computed_measure/static/src/js/pivot_model.js
Labels: approved, bot is merging ⏳, ready to merge

#1750 [12.0][IMP] web_responsive: Cut long filters names in the filters menu
  web_responsive/static/src/css/web_responsive.scss
Labels: approved, bot is merging ⏳

#1753 [13.0][IMP] web_responsive: Cut long filters names in the filters menu
  web_responsive/static/src/css/web_responsive.scss
Labels: approved, bot is merging ⏳

#1723 [12.0][ADD] web_set_single_page_hidden
  web_set_single_page_hidden/README.rst
  web_set_single_page_hidden/__init__.py
  web_set_single_page_hidden/__manifest__.py
  web_set_single_page_hidden/readme/CONTRIBUTORS.rst
  web_set_single_page_hidden/readme/DESCRIPTION.rst
  web_set_single_page_hidden/static/description/index.html
  web_set_single_page_hidden/static/src/js/pager.js
  web_set_single_page_hidden/static/src/js/relational_fields.js
  web_set_single_page_hidden/views/webclient_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#1628 [12.0][IMP] web_pwa_oca: Refactor to use OdooClass
  web_pwa_oca/README.rst
  web_pwa_oca/__init__.py
  web_pwa_oca/__manifest__.py
  web_pwa_oca/controllers/__init__.py
  web_pwa_oca/controllers/main.py
  web_pwa_oca/models/__init__.py
  web_pwa_oca/models/res_config_settings.py
  web_pwa_oca/readme/CONFIGURE.rst
  web_pwa_oca/readme/CONTRIBUTORS.rst
  web_pwa_oca/readme/DESCRIPTION.rst
  web_pwa_oca/readme/ROADMAP.rst
  web_pwa_oca/readme/USAGE.rst
  web_pwa_oca/static/description/index.html
  web_pwa_oca/static/img/icons/odoo_logo.svg
  web_pwa_oca/static/src/js/pwa_install.js
  web_pwa_oca/static/src/js/pwa_manager.js
  web_pwa_oca/static/src/js/webclient.js
  web_pwa_oca/static/src/js/worker/libs/class.js
  web_pwa_oca/static/src/js/worker/pwa.js
  web_pwa_oca/templates/assets.xml
  web_pwa_oca/templates/service_worker.xml
  web_pwa_oca/tests/__init__.py
  web_pwa_oca/tests/test_web_pwa_oca_controller.py
  web_pwa_oca/views/res_config_settings_views.xml
  web_pwa_oca/views/webclient_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#1751 [13.0][IMP] web_pivot_computed_measure: Saving vertical space
  web_pivot_computed_measure/static/src/js/pivot_controller.js
  web_pivot_computed_measure/static/src/scss/web_pivot_computed_measure.scss
  web_pivot_computed_measure/static/src/xml/web_pivot_computed_measure.xml
  web_pivot_computed_measure/view/assets.xml
Labels: approved, bot is merging ⏳

#1759 [12.0][IMP] web_pwa_oca: Drop BeforeInstallPrompt
  web_pwa_oca/README.rst
  web_pwa_oca/__manifest__.py
  web_pwa_oca/readme/INSTALL.rst
  web_pwa_oca/readme/ROADMAP.rst
  web_pwa_oca/readme/USAGE.rst
  web_pwa_oca/static/description/index.html
  web_pwa_oca/static/src/js/pwa_install.js
  web_pwa_oca/static/src/js/pwa_manager.js
  web_pwa_oca/static/src/xml/pwa_install.xml
  web_pwa_oca/templates/assets.xml
Labels: approved, bot is merging ⏳

#1760 [12.0][IMP] web_widget_numeric_step: better visualization in list view cells
  web_widget_numeric_step/static/src/css/numeric_step.scss
  web_widget_numeric_step/static/src/js/numeric_step.js
Labels: approved, bot is merging ⏳

#1594 [12.0][FIX] web_action_conditionable: Adapt to new api
  web_action_conditionable/README.rst
  web_action_conditionable/readme/CONTRIBUTORS.rst
  web_action_conditionable/readme/DESCRIPTION.rst
  web_action_conditionable/readme/USAGE.rst
  web_action_conditionable/static/description/index.html
  web_action_conditionable/static/src/js/field_one2many.js
  web_action_conditionable/static/src/js/views.js
  web_action_conditionable/views/view.xml
Labels: bot is merging ⏳

#1762 [12.0][FIX] web_widget_many2many_tags_multi_selection: Correct handle of 'Save & New'
  web_widget_many2many_tags_multi_selection/README.rst
  web_widget_many2many_tags_multi_selection/readme/CONTRIBUTORS.rst
  web_widget_many2many_tags_multi_selection/static/description/index.html
  web_widget_many2many_tags_multi_selection/static/src/js/view_form.js
Labels: approved, bot is merging ⏳

#1520 [12.0][MIG] web_widget_timepicker
  web_widget_timepicker/README.rst
  web_widget_timepicker/__init__.py
  web_widget_timepicker/__manifest__.py
  web_widget_timepicker/i18n/web_widget_timepicker.pot
  web_widget_timepicker/readme/CONTRIBUTORS.rst
  web_widget_timepicker/readme/CREDITS.rst
  web_widget_timepicker/readme/DESCRIPTION.rst
  web_widget_timepicker/readme/USAGE.rst
  web_widget_timepicker/static/description/icon.png
  web_widget_timepicker/static/description/index.html
  web_widget_timepicker/static/src/js/web_widget_timepicker.js
  web_widget_timepicker/views/web_widget_timepicker_assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1763 [13.0][FIX] web_responsive: port shortcuts
  web_responsive/__manifest__.py
  web_responsive/static/src/xml/menu.xml
Labels: bot is merging ⏳

#1768 [12.0][FIX] web_widget_numeric_step: Better visualization in list view cells
  web_widget_numeric_step/static/src/css/numeric_step.scss
  web_widget_numeric_step/static/src/js/numeric_step.js
Labels: approved, bot is merging ⏳

#1767 [13.0][ADD] web_widget_many2one_simple
  setup/web_widget_many2one_simple/odoo/addons/web_widget_many2one_simple
  setup/web_widget_many2one_simple/setup.py
  web_widget_many2one_simple/README.rst
  web_widget_many2one_simple/__init__.py
  web_widget_many2one_simple/__manifest__.py
  web_widget_many2one_simple/readme/CONFIGURE.rst
  web_widget_many2one_simple/readme/CONTRIBUTORS.rst
  web_widget_many2one_simple/readme/DESCRIPTION.rst
  web_widget_many2one_simple/readme/USAGE.rst
  web_widget_many2one_simple/static/description/index.html
  web_widget_many2one_simple/static/img/preview.gif
  web_widget_many2one_simple/static/src/css/many2one_simple.scss
  web_widget_many2one_simple/static/src/js/many2one_simple_field.js
  web_widget_many2one_simple/static/src/xml/many2one_simple.xml
  web_widget_many2one_simple/views/assets.xml
Labels: approved, bot is merging ⏳

#1770 [12.0][IMP] web_widget_one2many_product_picker: Remove items in main lines
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
Labels: approved, bot is merging ⏳
