Repository OCA/web, pull requests merged in 2020-04, with the labels that each got.

#1468 [11.0][ADD] web_search_date
  web_search_date/README.rst
  web_search_date/__init__.py
  web_search_date/__manifest__.py
  web_search_date/readme/CONTRIBUTORS.rst
  web_search_date/readme/DESCRIPTION.rst
  web_search_date/readme/USAGE.rst
  web_search_date/static/description/icon.png
  web_search_date/static/description/index.html
  web_search_date/static/src/js/widget.js
  web_search_date/views/web_widget_image_url.xml
Labels: approved, bot is merging ⏳, ready to merge

#1564 [13.0][MIG] web_m2x_options
  web_m2x_options/README.rst
  web_m2x_options/__init__.py
  web_m2x_options/__manifest__.py
  web_m2x_options/i18n/ar.po
  web_m2x_options/i18n/de.po
  web_m2x_options/i18n/es.po
  web_m2x_options/i18n/fi.po
  web_m2x_options/i18n/fr.po
  web_m2x_options/i18n/hr.po
  web_m2x_options/i18n/it.po
  web_m2x_options/i18n/nl_NL.po
  web_m2x_options/i18n/pt_BR.po
  web_m2x_options/i18n/sl.po
  web_m2x_options/i18n/tr.po
  web_m2x_options/i18n/web_m2x_options.pot
  web_m2x_options/i18n/zh_CN.po
  web_m2x_options/models/__init__.py
  web_m2x_options/models/ir_config_parameter.py
  web_m2x_options/readme/CONTRIBUTORS.rst
  web_m2x_options/readme/DESCRIPTION.rst
  web_m2x_options/readme/ROADMAP.rst
  web_m2x_options/readme/USAGE.rst
  web_m2x_options/static/description/icon.png
  web_m2x_options/static/description/index.html
  web_m2x_options/static/src/js/form.js
  web_m2x_options/static/src/xml/base.xml
  web_m2x_options/views/view.xml
Labels: approved, bot is merging ⏳

#1570 [12.0][FIX][web_m2x_options] when all is undefined, fall back to core's default
  web_m2x_options/static/src/xml/base.xml
Labels: approved, bot is merging ⏳

#1533 [13.0][MIG] web_ir_actions_act_multi : Migration to 13.0
  web_ir_actions_act_multi/README.rst
  web_ir_actions_act_multi/__init__.py
  web_ir_actions_act_multi/__manifest__.py
  web_ir_actions_act_multi/i18n/web_ir_actions_act_multi.pot
  web_ir_actions_act_multi/i18n/zh_CN.po
  web_ir_actions_act_multi/readme/CONTRIBUTORS.rst
  web_ir_actions_act_multi/readme/DESCRIPTION.rst
  web_ir_actions_act_multi/readme/USAGE.rst
  web_ir_actions_act_multi/static/description/icon.png
  web_ir_actions_act_multi/static/description/index.html
  web_ir_actions_act_multi/static/src/js/web_ir_actions_act_multi.js
  web_ir_actions_act_multi/views/web_ir_actions_act_multi.xml
Labels: bot is merging ⏳

#1551 [13.0][MIG] web_advanced_search: Migration to 13.0
  web_advanced_search/README.rst
  web_advanced_search/__init__.py
  web_advanced_search/__manifest__.py
  web_advanced_search/i18n/da.po
  web_advanced_search/i18n/de.po
  web_advanced_search/i18n/es.po
  web_advanced_search/i18n/fr.po
  web_advanced_search/i18n/hr.po
  web_advanced_search/i18n/nl.po
  web_advanced_search/i18n/nl_NL.po
  web_advanced_search/i18n/pt.po
  web_advanced_search/i18n/pt_BR.po
  web_advanced_search/i18n/web_advanced_search.pot
  web_advanced_search/i18n/zh_CN.po
  web_advanced_search/readme/CONTRIBUTORS.rst
  web_advanced_search/readme/DESCRIPTION.rst
  web_advanced_search/readme/HISTORY.rst
  web_advanced_search/readme/ROADMAP.rst
  web_advanced_search/readme/USAGE.rst
  web_advanced_search/static/description/icon.png
  web_advanced_search/static/description/index.html
  web_advanced_search/static/src/js/human_domain.js
  web_advanced_search/static/src/js/web_advanced_search.js
  web_advanced_search/static/src/xml/web_advanced_search.xml
  web_advanced_search/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#1568 [13.0][MIG] web_company_color: Migration to 13.0
  setup/web_company_color/odoo/addons/web_company_color
  setup/web_company_color/setup.py
  web_company_color/README.rst
  web_company_color/__init__.py
  web_company_color/__manifest__.py
  web_company_color/hooks.py
  web_company_color/i18n/hr.po
  web_company_color/i18n/web_company_color.pot
  web_company_color/i18n/zh_CN.po
  web_company_color/models/__init__.py
  web_company_color/models/assetsbundle.py
  web_company_color/models/ir_qweb.py
  web_company_color/models/res_company.py
  web_company_color/readme/CONTRIBUTORS.rst
  web_company_color/readme/DESCRIPTION.rst
  web_company_color/readme/ROADMAP.rst
  web_company_color/readme/USAGE.rst
  web_company_color/static/description/icon.png
  web_company_color/static/description/index.html
  web_company_color/tests/__init__.py
  web_company_color/tests/test_res_company.py
  web_company_color/utils.py
  web_company_color/view/assets.xml
  web_company_color/view/res_company.xml
Labels: approved, bot is merging ⏳

#1576 [IMP] web_tree_many2one_clickable: Don't break keyboard navigation
  web_tree_many2one_clickable/static/src/css/web_tree_many2one_clickable.scss
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
Labels: approved, bot is merging ⏳

#1565 [IMP] web_pivot_computed_measure: Time Ranges Comparison
  web_pivot_computed_measure/static/src/js/pivot_model.js
Labels: approved, bot is merging ⏳, ready to merge

#1578 [13.0][IMP] web_advance_search: Debug Mode
  web_advanced_search/README.rst
  web_advanced_search/readme/USAGE.rst
  web_advanced_search/static/description/index.html
  web_advanced_search/static/img/debug_mode.png
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: bot is merging ⏳

#1579 [12.0][IMP] web_advance_search: Debug mode
  web_advanced_search/README.rst
  web_advanced_search/readme/USAGE.rst
  web_advanced_search/static/description/index.html
  web_advanced_search/static/img/debug_mode.png
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: approved, bot is merging ⏳

#1577 [13.0] [FIX] web_m2x_options: quick search filter only if search value
  web_m2x_options/static/src/js/form.js
Labels: approved, bot is merging ⏳

#1557 [13.0][MIG] web_timeline: Migration to 13.0
  .isort.cfg
  setup/web_timeline/odoo/addons/web_timeline
  setup/web_timeline/setup.py
  web_notify/tests/test_res_users.py
  web_timeline/README.rst
  web_timeline/__init__.py
  web_timeline/__manifest__.py
  web_timeline/i18n/es.po
  web_timeline/i18n/fr.po
  web_timeline/i18n/hr.po
  web_timeline/i18n/nl_NL.po
  web_timeline/i18n/pt.po
  web_timeline/i18n/web_timeline.pot
  web_timeline/i18n/zh_CN.po
  web_timeline/models/__init__.py
  web_timeline/models/ir_ui_view.py
  web_timeline/readme/CONFIGURE.rst
  web_timeline/readme/CONTRIBUTORS.rst
  web_timeline/readme/DESCRIPTION.rst
  web_timeline/readme/ROADMAP.rst
  web_timeline/readme/USAGE.rst
  web_timeline/static/description/icon.png
  web_timeline/static/description/index.html
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.css
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.min.js
  web_timeline/static/src/js/timeline_canvas.js
  web_timeline/static/src/js/timeline_controller.js
  web_timeline/static/src/js/timeline_model.js
  web_timeline/static/src/js/timeline_renderer.js
  web_timeline/static/src/js/timeline_view.js
  web_timeline/static/src/scss/web_timeline.scss
  web_timeline/static/src/xml/web_timeline.xml
  web_timeline/views/web_timeline.xml
Labels: approved, bot is merging ⏳, needs fixing, ready to merge

#1572 [11.0][MIG] web_widget_dropdown_dynamic: Backport to 11.0
  web_widget_dropdown_dynamic/README.rst
  web_widget_dropdown_dynamic/__init__.py
  web_widget_dropdown_dynamic/__manifest__.py
  web_widget_dropdown_dynamic/i18n/web_widget_dropdown_dynamic.pot
  web_widget_dropdown_dynamic/readme/CONTRIBUTORS.rst
  web_widget_dropdown_dynamic/readme/DESCRIPTION.rst
  web_widget_dropdown_dynamic/readme/ROADMAP.rst
  web_widget_dropdown_dynamic/readme/USAGE.rst
  web_widget_dropdown_dynamic/static/description/icon.png
  web_widget_dropdown_dynamic/static/description/index.html
  web_widget_dropdown_dynamic/static/src/js/basic_model.js
  web_widget_dropdown_dynamic/static/src/js/field_dynamic_dropdown.js
  web_widget_dropdown_dynamic/static/tests/web_widget_dropdown_dynamic_tests.js
  web_widget_dropdown_dynamic/templates/assets.xml
  web_widget_dropdown_dynamic_example/__init__.py
  web_widget_dropdown_dynamic_example/__manifest__.py
  web_widget_dropdown_dynamic_example/i18n/web_widget_dropdown_dynamic_example.pot
  web_widget_dropdown_dynamic_example/models/__init__.py
  web_widget_dropdown_dynamic_example/models/web_widget_dropdown_dynamic_example.py
  web_widget_dropdown_dynamic_example/static/description/icon.png
  web_widget_dropdown_dynamic_example/views/web_widget_dropdown_dynamic_example.xml
Labels: bot is merging ⏳

#1575 [IMP] web_responsive: Restore discuss mobile mode
  web_responsive/__manifest__.py
  web_responsive/static/src/js/discuss.js
  web_responsive/static/src/xml/discuss.xml
  web_responsive/views/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1560 [FIX] web_responsive: fix hotkey combinations in a shortcut template
  web_responsive/__manifest__.py
  web_responsive/static/src/xml/menu.xml
Labels: approved, bot is merging ⏳

#1555 [MIG][12.0] web_widget_image_webcam
  web_widget_image_webcam/README.rst
  web_widget_image_webcam/__init__.py
  web_widget_image_webcam/__manifest__.py
  web_widget_image_webcam/models/__init__.py
  web_widget_image_webcam/models/ir_config_parameter.py
  web_widget_image_webcam/readme/CONFIGURE.rst
  web_widget_image_webcam/readme/CONTRIBUTORS.rst
  web_widget_image_webcam/readme/DESCRIPTION.rst
  web_widget_image_webcam/static/description/icon.png
  web_widget_image_webcam/static/src/css/web_widget_image_webcam.css
  web_widget_image_webcam/static/src/img/webcam_placeholder.png
  web_widget_image_webcam/static/src/js/webcam.js
  web_widget_image_webcam/static/src/js/webcam.swf
  web_widget_image_webcam/static/src/js/webcam_widget.js
  web_widget_image_webcam/static/src/xml/web_widget_image_webcam.xml
  web_widget_image_webcam/views/assets.xml
Labels: approved, ready to merge

#1589 [12.0][FIX] web_pivot_computed_measure: Change custom_events addition
  web_pivot_computed_measure/static/src/js/pivot_controller.js
Labels: approved, bot is merging ⏳

#1585 [12.0][FIX] web_tree_many2one_clickable: Compatible with decoration colors
  web_tree_many2one_clickable/static/src/css/web_tree_many2one_clickable.scss
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
Labels: approved, bot is merging ⏳

#1486 [13.0][MIG] web_drop_target
  setup/web_drop_target/odoo/addons/web_drop_target
  setup/web_drop_target/setup.py
  web_drop_target/README.rst
  web_drop_target/__init__.py
  web_drop_target/__manifest__.py
  web_drop_target/i18n/fr.po
  web_drop_target/i18n/web_drop_target.pot
  web_drop_target/readme/CONTRIBUTORS.rst
  web_drop_target/readme/DESCRIPTION.rst
  web_drop_target/readme/DEVELOP.rst
  web_drop_target/readme/ROADMAP.rst
  web_drop_target/readme/USAGE.rst
  web_drop_target/static/description/icon.png
  web_drop_target/static/description/index.html
  web_drop_target/static/description/screenshot.png
  web_drop_target/static/lib/base64js.min.js
  web_drop_target/static/src/js/web_drop_target.js
  web_drop_target/static/src/less/web_drop_target.less
  web_drop_target/static/src/xml/widgets.xml
  web_drop_target/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge
