Repository OCA/web, pull requests merged in 2020-02, with the labels that each got.

#1507 [FIX] web_widget_x2many_2d_matrix: Ensure lines order
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
Labels: approved, ready to merge

#1509 [12.0][IMP] web_responsive: Payment info popover position
  web_responsive/static/src/css/web_responsive.scss
Labels: approved

#1524 [12.0][MIG] web_widget_open_tab
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/readme/CONTRIBUTORS.rst
  web_widget_open_tab/readme/DESCRIPTION.rst
  web_widget_open_tab/readme/USAGE.rst
  web_widget_open_tab/static/description/icon.png
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/static/src/js/widget.js
  web_widget_open_tab/static/src/less/open_tab.less
  web_widget_open_tab/views/assets.xml
Labels: approved

#1527 [13.0][FIX] Fixed the pyeval.js path in assets_backend
  web_domain_field/views/web_domain_field.xml
Labels: approved

#1515 [12.0][ADD] web_widget_numeric_step
  web_widget_numeric_step/README.rst
  web_widget_numeric_step/__init__.py
  web_widget_numeric_step/__manifest__.py
  web_widget_numeric_step/demo/res_users_view.xml
  web_widget_numeric_step/i18n/fr.po
  web_widget_numeric_step/readme/CONTRIBUTORS.rst
  web_widget_numeric_step/readme/DESCRIPTION.rst
  web_widget_numeric_step/readme/USAGE.rst
  web_widget_numeric_step/static/description/add_two_buttons.png
  web_widget_numeric_step/static/description/icon.png
  web_widget_numeric_step/static/description/index.html
  web_widget_numeric_step/static/description/step0,25andlimits.gif
  web_widget_numeric_step/static/description/step10_limit15_placeholder117_with_onchange.gif
  web_widget_numeric_step/static/src/css/numeric_step.scss
  web_widget_numeric_step/static/src/js/numeric_step.js
  web_widget_numeric_step/static/src/xml/numeric_step.xml
  web_widget_numeric_step/view/assets.xml
Labels: approved

#1535 [FIX] web_widget_numeric_step: Float Precision
  web_widget_numeric_step/static/src/js/numeric_step.js
Labels: approved

#1534 [FIX] web_responsive: Change AppDrawer close method
  web_responsive/static/src/js/web_responsive.js
Labels: approved

#1312 [12.0][MIG] web_translate_dialog + improvements
  web_translate_dialog/README.rst
  web_translate_dialog/__init__.py
  web_translate_dialog/__manifest__.py
  web_translate_dialog/i18n/ar.po
  web_translate_dialog/i18n/de.po
  web_translate_dialog/i18n/es.po
  web_translate_dialog/i18n/fi.po
  web_translate_dialog/i18n/fr.po
  web_translate_dialog/i18n/hr.po
  web_translate_dialog/i18n/it.po
  web_translate_dialog/i18n/nl.po
  web_translate_dialog/i18n/nl_NL.po
  web_translate_dialog/i18n/pt_BR.po
  web_translate_dialog/i18n/sl.po
  web_translate_dialog/i18n/tr.po
  web_translate_dialog/i18n/web_translate_dialog.pot
  web_translate_dialog/models/__init__.py
  web_translate_dialog/models/base.py
  web_translate_dialog/models/res_lang.py
  web_translate_dialog/readme/CONTRIBUTORS.rst
  web_translate_dialog/readme/DESCRIPTION.rst
  web_translate_dialog/readme/USAGE.rst
  web_translate_dialog/static/description/icon.png
  web_translate_dialog/static/src/css/base.css
  web_translate_dialog/static/src/js/web_translate_dialog.js
  web_translate_dialog/static/src/xml/base.xml
  web_translate_dialog/views/res_lang.xml
  web_translate_dialog/views/web_translate.xml
Labels: merged 🎉
