Repository OCA/web, pull requests merged in 2020-01, with the labels that each got.

#1439 [10.0][ADD] web_unclickable
  setup/web_unclickable/odoo/__init__.py
  setup/web_unclickable/odoo/addons/__init__.py
  setup/web_unclickable/odoo/addons/web_unclickable
  setup/web_unclickable/setup.py
  web_unclickable/README.rst
  web_unclickable/__init__.py
  web_unclickable/__manifest__.py
  web_unclickable/readme/CONTRIBUTORS.rst
  web_unclickable/readme/DESCRIPTION.rst
  web_unclickable/readme/USAGE.rst
  web_unclickable/static/description/icon.png
  web_unclickable/static/description/index.html
  web_unclickable/static/src/css/web_template.css
  web_unclickable/views/web_template.xml
Labels: approved, ready to merge

#1478 [12.0][IMP] web_advanced_search: contains search
  web_advanced_search/__manifest__.py
  web_advanced_search/readme/CONTRIBUTORS.rst
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: approved, ready to merge

#1490 [FIX] web_responsive: make followers dropdown usable
  web_responsive/static/src/css/web_responsive.scss
Labels: approved, bug

#1491 [FIX] web_responsive: Remove auto-focus for the document viewer modal
  web_responsive/static/src/js/web_responsive.js
Labels: approved

#1492 [IMP] web_responsive: Document Viewer key events
  web_responsive/static/src/js/web_responsive.js
Labels: approved

#1503 [FIX] web_responsive: usable search buttons in md screens
  web_responsive/static/src/css/web_responsive.scss
Labels: approved, bug

#1498 [12.0] [FIX] Tree m2o clickable: call to get_formview_action()
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
Labels: approved, ready to merge
