Repository OCA/web, pull requests merged in 2020-06, with the labels that each got.

#1602 [12.0] ADD web_pwa
  web_pwa/__init__.py
  web_pwa/__manifest__.py
  web_pwa/controllers/__init__.py
  web_pwa/controllers/main.py
  web_pwa/readme/CONFIGURE.rst
  web_pwa/readme/CONTRIBUTORS.rst
  web_pwa/readme/DESCRIPTION.rst
  web_pwa/readme/INSTALL.rst
  web_pwa/readme/ROADMAP.rst
  web_pwa/static/description/icon.png
  web_pwa/static/description/pwa.png
  web_pwa/static/img/icons/icon-128x128.png
  web_pwa/static/img/icons/icon-144x144.png
  web_pwa/static/img/icons/icon-152x152.png
  web_pwa/static/img/icons/icon-192x192.png
  web_pwa/static/img/icons/icon-256x256.png
  web_pwa/static/img/icons/icon-512x512.png
  web_pwa/static/src/js/pwa_install.js
  web_pwa/static/src/xml/pwa_install.xml
  web_pwa/views/webclient_templates.xml
Labels: approved, bot is merging ⏳

#1610 [12.0][FIX] web_translate_dialog: Search using '=' to target right field
  web_translate_dialog/models/base.py
Labels: approved, bot is merging ⏳

#1616 Rename web_pwa -> web_pwa_oca
  web_pwa/README.rst
  web_pwa/i18n/da.po
  web_pwa/i18n/web_pwa.pot
  web_pwa/readme/CONFIGURE.rst
  web_pwa/static/description/index.html
  web_pwa_oca/__init__.py
  web_pwa_oca/__manifest__.py
  web_pwa_oca/controllers/__init__.py
  web_pwa_oca/controllers/main.py
  web_pwa_oca/readme/CONFIGURE.rst
  web_pwa_oca/readme/CONTRIBUTORS.rst
  web_pwa_oca/readme/DESCRIPTION.rst
  web_pwa_oca/readme/INSTALL.rst
  web_pwa_oca/readme/ROADMAP.rst
  web_pwa_oca/static/description/icon.png
  web_pwa_oca/static/description/pwa.png
  web_pwa_oca/static/img/icons/icon-128x128.png
  web_pwa_oca/static/img/icons/icon-144x144.png
  web_pwa_oca/static/img/icons/icon-152x152.png
  web_pwa_oca/static/img/icons/icon-192x192.png
  web_pwa_oca/static/img/icons/icon-256x256.png
  web_pwa_oca/static/img/icons/icon-512x512.png
  web_pwa_oca/static/src/js/pwa_install.js
  web_pwa_oca/static/src/xml/pwa_install.xml
  web_pwa_oca/views/webclient_templates.xml
Labels: approved, bot is merging ⏳

#1500 [12.0] [ADD] m2x_options: Option open for One2Many fields
  web_m2x_options/readme/USAGE.rst
  web_m2x_options/static/src/js/form.js
Labels: approved, merged 🎉, ready to merge

#1622 web_widget_x2many_2d_matrix: Fix show_column_totals option
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
Labels: approved, bot is merging ⏳

#1624 [MIG] web_pwa_oca: Migration to V13
  setup/web_pwa_oca/odoo/addons/web_pwa_oca
  setup/web_pwa_oca/setup.py
  web_pwa_oca/README.rst
  web_pwa_oca/__init__.py
  web_pwa_oca/__manifest__.py
  web_pwa_oca/controllers/__init__.py
  web_pwa_oca/controllers/main.py
  web_pwa_oca/i18n/web_pwa_oca.pot
  web_pwa_oca/readme/CONFIGURE.rst
  web_pwa_oca/readme/CONTRIBUTORS.rst
  web_pwa_oca/readme/DESCRIPTION.rst
  web_pwa_oca/readme/INSTALL.rst
  web_pwa_oca/readme/ROADMAP.rst
  web_pwa_oca/static/description/icon.png
  web_pwa_oca/static/description/index.html
  web_pwa_oca/static/description/pwa.png
  web_pwa_oca/static/img/icons/icon-128x128.png
  web_pwa_oca/static/img/icons/icon-144x144.png
  web_pwa_oca/static/img/icons/icon-152x152.png
  web_pwa_oca/static/img/icons/icon-192x192.png
  web_pwa_oca/static/img/icons/icon-256x256.png
  web_pwa_oca/static/img/icons/icon-512x512.png
  web_pwa_oca/static/src/js/pwa_install.js
  web_pwa_oca/static/src/xml/pwa_install.xml
  web_pwa_oca/views/webclient_templates.xml
Labels: approved, bot is merging ⏳

#1619 [13.0] [MIG] web_ir_actions_act_window_message
  setup/web_ir_actions_act_window_message/odoo/addons/web_ir_actions_act_window_message
  setup/web_ir_actions_act_window_message/setup.py
  web_ir_actions_act_window_message/README.rst
  web_ir_actions_act_window_message/__init__.py
  web_ir_actions_act_window_message/__manifest__.py
  web_ir_actions_act_window_message/i18n/ar.po
  web_ir_actions_act_window_message/i18n/de.po
  web_ir_actions_act_window_message/i18n/es.po
  web_ir_actions_act_window_message/i18n/eu.po
  web_ir_actions_act_window_message/i18n/fi.po
  web_ir_actions_act_window_message/i18n/fr.po
  web_ir_actions_act_window_message/i18n/hr.po
  web_ir_actions_act_window_message/i18n/it.po
  web_ir_actions_act_window_message/i18n/nl.po
  web_ir_actions_act_window_message/i18n/nl_NL.po
  web_ir_actions_act_window_message/i18n/pt.po
  web_ir_actions_act_window_message/i18n/pt_BR.po
  web_ir_actions_act_window_message/i18n/ro.po
  web_ir_actions_act_window_message/i18n/sl.po
  web_ir_actions_act_window_message/i18n/tr.po
  web_ir_actions_act_window_message/i18n/web_ir_actions_act_window_message.pot
  web_ir_actions_act_window_message/readme/CONTRIBUTORS.rst
  web_ir_actions_act_window_message/readme/DESCRIPTION.rst
  web_ir_actions_act_window_message/readme/ROADMAP.rst
  web_ir_actions_act_window_message/readme/USAGE.rst
  web_ir_actions_act_window_message/static/description/icon.png
  web_ir_actions_act_window_message/static/description/index.html
  web_ir_actions_act_window_message/static/src/js/web_ir_actions_act_window_message.js
  web_ir_actions_act_window_message/static/src/xml/web_ir_actions_act_window_message.xml
  web_ir_actions_act_window_message/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#1627 Port/12.0/web no crawler
  web_no_crawler/README.rst
  web_no_crawler/__init__.py
  web_no_crawler/__manifest__.py
  web_no_crawler/controllers/__init__.py
  web_no_crawler/controllers/main.py
  web_no_crawler/i18n/web_no_crawler.pot
  web_no_crawler/readme/CONTRIBUTORS.rst
  web_no_crawler/readme/CREDITS.rst
  web_no_crawler/readme/DESCRIPTION.rst
  web_no_crawler/readme/INSTALL.rst
  web_no_crawler/readme/ROADMAP.rst
  web_no_crawler/readme/USAGE.rst
  web_no_crawler/static/description/icon.png
Labels: approved, bot is merging ⏳, ready to merge
