Repository OCA/web, pull requests merged in 2020-03, with the labels that each got.

#1540 pre-commit update: prettier xml indent
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  web_decimal_numpad_dot/views/web_decimal_numpad_dot.xml
  web_dialog_size/static/src/xml/web_dialog_size.xml
  web_environment_ribbon/data/ribbon_data.xml
  web_environment_ribbon/view/base_view.xml
  web_responsive/static/src/xml/apps.xml
  web_responsive/static/src/xml/document_viewer.xml
  web_responsive/static/src/xml/form_view.xml
  web_responsive/views/res_users.xml
  web_responsive/views/web.xml
  web_tree_many2one_clickable/views/assets.xml
  web_widget_bokeh_chart/views/web_widget_bokeh_chart.xml
  web_widget_image_download/views/assets.xml
Labels: approved

#1484 [13.0][MIG] web_widget_x2many_2d_matrix
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/__init__.py
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/i18n/ar.po
  web_widget_x2many_2d_matrix/i18n/de.po
  web_widget_x2many_2d_matrix/i18n/es.po
  web_widget_x2many_2d_matrix/i18n/fi.po
  web_widget_x2many_2d_matrix/i18n/fr.po
  web_widget_x2many_2d_matrix/i18n/hr.po
  web_widget_x2many_2d_matrix/i18n/it.po
  web_widget_x2many_2d_matrix/i18n/lt.po
  web_widget_x2many_2d_matrix/i18n/nl_NL.po
  web_widget_x2many_2d_matrix/i18n/pt_BR.po
  web_widget_x2many_2d_matrix/i18n/sl.po
  web_widget_x2many_2d_matrix/i18n/tr.po
  web_widget_x2many_2d_matrix/i18n/web_widget_x2many_2d_matrix.pot
  web_widget_x2many_2d_matrix/i18n/zh_CN.po
  web_widget_x2many_2d_matrix/readme/CONTRIBUTORS.rst
  web_widget_x2many_2d_matrix/readme/DESCRIPTION.rst
  web_widget_x2many_2d_matrix/readme/HISTORY.rst
  web_widget_x2many_2d_matrix/readme/ROADMAP.rst
  web_widget_x2many_2d_matrix/readme/USAGE.rst
  web_widget_x2many_2d_matrix/static/description/icon.png
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/description/screenshot.png
  web_widget_x2many_2d_matrix/static/src/js/2d_matrix_renderer.js
  web_widget_x2many_2d_matrix/static/src/js/2d_matrix_view.js
  web_widget_x2many_2d_matrix/static/src/js/abstract_view_matrix_limit_extend.js
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
  web_widget_x2many_2d_matrix/static/src/scss/web_widget_x2many_2d_matrix.scss
  web_widget_x2many_2d_matrix/views/assets.xml
  web_widget_x2many_2d_matrix_example/README.rst
  web_widget_x2many_2d_matrix_example/__init__.py
  web_widget_x2many_2d_matrix_example/__manifest__.py
  web_widget_x2many_2d_matrix_example/demo/x2m.demo.csv
  web_widget_x2many_2d_matrix_example/i18n/web_widget_x2many_2d_matrix_example.pot
  web_widget_x2many_2d_matrix_example/i18n/zh_CN.po
  web_widget_x2many_2d_matrix_example/models/__init__.py
  web_widget_x2many_2d_matrix_example/models/x2m_demo.py
  web_widget_x2many_2d_matrix_example/readme/CONTRIBUTORS.rst
  web_widget_x2many_2d_matrix_example/readme/DESCRIPTION.rst
  web_widget_x2many_2d_matrix_example/security/ir.model.access.csv
  web_widget_x2many_2d_matrix_example/static/description/icon.png
  web_widget_x2many_2d_matrix_example/static/description/index.html
  web_widget_x2many_2d_matrix_example/views/x2m_demo.xml
  web_widget_x2many_2d_matrix_example/wizard/__init__.py
  web_widget_x2many_2d_matrix_example/wizard/x2m_matrix.py
  web_widget_x2many_2d_matrix_example/wizard/x2m_matrix.xml
Labels: approved, needs review, ready to merge

#1543 [FIX] web_widget_numeric_step: Fix _onChange input fields methods disabled by the widget
  web_widget_numeric_step/static/src/js/numeric_step.js
Labels: approved

#1541 [13.0][MIG] web_widget_url_advanced
  web_widget_url_advanced/README.rst
  web_widget_url_advanced/__init__.py
  web_widget_url_advanced/__manifest__.py
  web_widget_url_advanced/i18n/web_widget_url_advanced.pot
  web_widget_url_advanced/i18n/zh_CN.po
  web_widget_url_advanced/readme/CONTRIBUTORS.rst
  web_widget_url_advanced/readme/DESCRIPTION.rst
  web_widget_url_advanced/readme/ROADMAP.rst
  web_widget_url_advanced/readme/USAGE.rst
  web_widget_url_advanced/static/description/after.png
  web_widget_url_advanced/static/description/before.png
  web_widget_url_advanced/static/description/icon.png
  web_widget_url_advanced/static/description/index.html
  web_widget_url_advanced/static/src/js/url_widget.js
  web_widget_url_advanced/templates/assets.xml
Labels: approved, needs fixing

#1519 [12.0][FIX] - advanced search, combination of several OR operators
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: approved, ready to merge

#1549 [13.0][mig] web_widget_mpld3_chart
  requirements.txt
  setup/web_widget_mpld3_chart/odoo/addons/web_widget_mpld3_chart
  setup/web_widget_mpld3_chart/setup.py
  web_widget_mpld3_chart/__init__.py
  web_widget_mpld3_chart/__manifest__.py
  web_widget_mpld3_chart/readme/CONTRIBUTORS.rst
  web_widget_mpld3_chart/readme/CREDITS.rst
  web_widget_mpld3_chart/readme/DESCRIPTION.rst
  web_widget_mpld3_chart/readme/INSTALL.rst
  web_widget_mpld3_chart/readme/USAGE.rst
  web_widget_mpld3_chart/static/src/js/web_widget_mpld3_chart.js
  web_widget_mpld3_chart/static/src/lib/d3/d3.v3.min.js
  web_widget_mpld3_chart/static/src/lib/mpld3/mpld3.v0.3.1.dev1.js
  web_widget_mpld3_chart/views/web_widget_mpld3_chart.xml
Labels: approved

#1516 [12.0][add] web_widget_mpld3_chart
  requirements.txt
  web_widget_mpld3_chart/__init__.py
  web_widget_mpld3_chart/__manifest__.py
  web_widget_mpld3_chart/readme/CONTRIBUTORS.rst
  web_widget_mpld3_chart/readme/CREDITS.rst
  web_widget_mpld3_chart/readme/DESCRIPTION.rst
  web_widget_mpld3_chart/readme/INSTALL.rst
  web_widget_mpld3_chart/readme/USAGE.rst
  web_widget_mpld3_chart/static/src/js/web_widget_mpld3_chart.js
  web_widget_mpld3_chart/static/src/lib/d3/d3.v3.min.js
  web_widget_mpld3_chart/static/src/lib/mpld3/mpld3.v0.3.1.dev1.js
  web_widget_mpld3_chart/views/web_widget_mpld3_chart.xml
Labels: merged 🎉

#1550 [13.0] freeze dependency to avoid futures issues when the library gets updated
  requirements.txt
Labels: approved

#1546 [MIG] web_refresher in v12.0
  web_refresher/README.rst
  web_refresher/__init__.py
  web_refresher/__manifest__.py
  web_refresher/i18n/web_refresher.pot
  web_refresher/images/refresh.png
  web_refresher/readme/CONTRIBUTORS.rst
  web_refresher/readme/DESCRIPTION.rst
  web_refresher/static/description/icon.png
  web_refresher/static/description/index.html
  web_refresher/static/src/js/refresher.js
  web_refresher/templates/assets.xml
Labels: approved, ready to merge

#1480 [MIG][13.0] web_tree_dynamic_colored_field
  setup/web_tree_dynamic_colored_field/odoo/addons/web_tree_dynamic_colored_field
  setup/web_tree_dynamic_colored_field/setup.py
  web_tree_dynamic_colored_field/README.rst
  web_tree_dynamic_colored_field/__init__.py
  web_tree_dynamic_colored_field/__manifest__.py
  web_tree_dynamic_colored_field/demo/res_users.xml
  web_tree_dynamic_colored_field/i18n/es.po
  web_tree_dynamic_colored_field/i18n/fi.po
  web_tree_dynamic_colored_field/i18n/nl_NL.po
  web_tree_dynamic_colored_field/i18n/sl.po
  web_tree_dynamic_colored_field/i18n/web_tree_dynamic_colored_field.pot
  web_tree_dynamic_colored_field/i18n/zh_CN.po
  web_tree_dynamic_colored_field/readme/CONTRIBUTORS.rst
  web_tree_dynamic_colored_field/readme/DESCRIPTION.rst
  web_tree_dynamic_colored_field/readme/ROADMAP.rst
  web_tree_dynamic_colored_field/readme/USAGE.rst
  web_tree_dynamic_colored_field/static/description/icon.png
  web_tree_dynamic_colored_field/static/description/index.html
  web_tree_dynamic_colored_field/static/src/js/web_tree_dynamic_colored_field.js
  web_tree_dynamic_colored_field/views/web_tree_dynamic_colored_field.xml
Labels: approved

#1547 [12.0][ADD] web_pivot_computed_measure
  web_pivot_computed_measure/README.rst
  web_pivot_computed_measure/__init__.py
  web_pivot_computed_measure/__manifest__.py
  web_pivot_computed_measure/readme/CONTRIBUTORS.rst
  web_pivot_computed_measure/readme/DESCRIPTION.rst
  web_pivot_computed_measure/readme/ROADMAP.rst
  web_pivot_computed_measure/readme/USAGE.rst
  web_pivot_computed_measure/static/description/index.html
  web_pivot_computed_measure/static/src/js/pivot_controller.js
  web_pivot_computed_measure/static/src/js/pivot_model.js
  web_pivot_computed_measure/static/src/xml/web_pivot_computed_measure.xml
  web_pivot_computed_measure/view/assets.xml
Labels: approved, ready to merge

#1554 [12.0][IMP] web_advanced_search: support hierarchy filtering
  web_advanced_search/__manifest__.py
  web_advanced_search/readme/CONTRIBUTORS.rst
  web_advanced_search/readme/ROADMAP.rst
  web_advanced_search/readme/USAGE.rst
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: approved

#1559 [FIX] web_widget_numeri_step: Change click timeout
  web_widget_numeric_step/static/src/js/numeric_step.js
Labels: approved
