Repository OCA/web, pull requests merged in 2021-03, with the labels that each got.

#1718 [14.0] Migrate module web_m2x_options to v14
  setup/web_m2x_options/odoo/addons/web_m2x_options
  setup/web_m2x_options/setup.py
  web_m2x_options/README.rst
  web_m2x_options/__init__.py
  web_m2x_options/__manifest__.py
  web_m2x_options/i18n/ar.po
  web_m2x_options/i18n/de.po
  web_m2x_options/i18n/es.po
  web_m2x_options/i18n/fi.po
  web_m2x_options/i18n/fr.po
  web_m2x_options/i18n/hr.po
  web_m2x_options/i18n/it.po
  web_m2x_options/i18n/nl_NL.po
  web_m2x_options/i18n/pt_BR.po
  web_m2x_options/i18n/sl.po
  web_m2x_options/i18n/tr.po
  web_m2x_options/i18n/web_m2x_options.pot
  web_m2x_options/i18n/zh_CN.po
  web_m2x_options/models/__init__.py
  web_m2x_options/models/ir_config_parameter.py
  web_m2x_options/readme/CONTRIBUTORS.rst
  web_m2x_options/readme/DESCRIPTION.rst
  web_m2x_options/readme/ROADMAP.rst
  web_m2x_options/readme/USAGE.rst
  web_m2x_options/static/description/icon.png
  web_m2x_options/static/description/index.html
  web_m2x_options/static/src/js/form.js
  web_m2x_options/static/src/xml/base.xml
  web_m2x_options/tests/__init__.py
  web_m2x_options/tests/test_ir_config_parameter.py
  web_m2x_options/views/view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1724 [14.0][MIG] web_notify: Migration to 14.0
  setup/web_notify/odoo/addons/web_notify
  setup/web_notify/setup.py
  web_notify/README.rst
  web_notify/__init__.py
  web_notify/__manifest__.py
  web_notify/i18n/da.po
  web_notify/i18n/de.po
  web_notify/i18n/es.po
  web_notify/i18n/hr.po
  web_notify/i18n/nl_NL.po
  web_notify/i18n/pt_BR.po
  web_notify/i18n/web_notify.pot
  web_notify/i18n/zh_CN.po
  web_notify/models/__init__.py
  web_notify/models/res_users.py
  web_notify/readme/CONTRIBUTORS.rst
  web_notify/readme/DESCRIPTION.rst
  web_notify/readme/INSTALL.rst
  web_notify/readme/USAGE.rst
  web_notify/static/description/icon.png
  web_notify/static/description/index.html
  web_notify/static/description/notifications_screenshot.png
  web_notify/static/description/test_notifications_demo.png
  web_notify/static/src/js/web_client.js
  web_notify/static/src/js/widgets/notification.js
  web_notify/static/src/scss/webclient.scss
  web_notify/tests/__init__.py
  web_notify/tests/test_res_users.py
  web_notify/views/res_users_demo.xml
  web_notify/views/web_notify.xml
Labels: approved, bot is merging ⏳, ready to merge

#1787 [13.0][web_widget_domain_editor_dialog][FIX] Error when used in wizards.
  web_widget_domain_editor_dialog/static/src/js/basic_fields.js
Labels: bot is merging ⏳

#1831 [ADD] web_calendar_slot_duration: customizable calendar slots timespan
  web_calendar_slot_duration/README.rst
  web_calendar_slot_duration/__init__.py
  web_calendar_slot_duration/__manifest__.py
  web_calendar_slot_duration/readme/CONFIGURE.rst
  web_calendar_slot_duration/readme/DESCRIPTION.rst
  web_calendar_slot_duration/readme/ROADMAP.rst
  web_calendar_slot_duration/readme/USAGE.rst
  web_calendar_slot_duration/static/description/icon.png
  web_calendar_slot_duration/static/description/index.html
  web_calendar_slot_duration/static/src/js/calendar_model.js
  web_calendar_slot_duration/templates/assets.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1844 [12.0][IMP] web_widget_one2many_product_picker: Enlarge the 'Add 1' button
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker/static/src/scss/one2many_product_picker.scss
  web_widget_one2many_product_picker/static/src/xml/one2many_product_picker.xml
Labels: approved, bot is merging ⏳

#1754 [12.0][MIG] web_sheet_full_width
  web_sheet_full_width/README.rst
  web_sheet_full_width/__init__.py
  web_sheet_full_width/__manifest__.py
  web_sheet_full_width/i18n/web_sheet_full_width.pot
  web_sheet_full_width/readme/CONTRIBUTORS.rst
  web_sheet_full_width/readme/DESCRIPTION.rst
  web_sheet_full_width/static/description/icon.png
  web_sheet_full_width/static/description/index.html
  web_sheet_full_width/static/src/css/web_sheet_full_width.scss
  web_sheet_full_width/templates/assets.xml
Labels: approved, bot is merging ⏳

#1778 [14.0][MIG] web_domain_field
  setup/web_domain_field/odoo/addons/web_domain_field
  setup/web_domain_field/setup.py
  web_domain_field/README.rst
  web_domain_field/__init__.py
  web_domain_field/__manifest__.py
  web_domain_field/i18n/es.po
  web_domain_field/i18n/web_domain_field.pot
  web_domain_field/static/description/icon.png
  web_domain_field/static/lib/js/pyeval.js
  web_domain_field/views/web_domain_field.xml
Labels: approved, bot is merging ⏳, ready to merge

#1704 [12.0][FIX] web_translate_dialog: on_button_translate load current record
  web_translate_dialog/static/src/js/web_translate_dialog.js
Labels: approved, bot is merging ⏳, ready to merge

#1804 [12.0][ADD] Web widget Datepicker full options
  web_widget_datepicker_fulloptions/__init__.py
  web_widget_datepicker_fulloptions/__manifest__.py
  web_widget_datepicker_fulloptions/readme/CONTRIBUTORS.rst
  web_widget_datepicker_fulloptions/readme/DESCRIPTION.rst
  web_widget_datepicker_fulloptions/static/description/change.png
  web_widget_datepicker_fulloptions/static/description/icon.png
  web_widget_datepicker_fulloptions/static/src/js/web_widget_datepicker_fulloptions.js
  web_widget_datepicker_fulloptions/views/web_widget_datepicker_fulloptions_assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1738 [12.0] [MIG] web domain field
  web_domain_field/README.rst
  web_domain_field/__init__.py
  web_domain_field/__manifest__.py
  web_domain_field/i18n/web_domain_field.pot
  web_domain_field/readme/CONTRIBUTORS.rst
  web_domain_field/readme/DESCRIPTION.rst
  web_domain_field/readme/USAGE.rst
  web_domain_field/static/description/icon.png
  web_domain_field/static/description/index.html
  web_domain_field/static/src/js/pyeval.js
  web_domain_field/views/web_domain_field.xml
  web_domain_field_example/README.rst
  web_domain_field_example/__init__.py
  web_domain_field_example/__manifest__.py
  web_domain_field_example/demo/product_demonstration.xml
  web_domain_field_example/models/__init__.py
  web_domain_field_example/models/product_demonstration.py
  web_domain_field_example/models/product_selection_example.py
  web_domain_field_example/readme/CONTRIBUTORS.rst
  web_domain_field_example/readme/DESCRIPTION.rst
  web_domain_field_example/readme/USAGE.rst
  web_domain_field_example/security/ir.model.access.csv
  web_domain_field_example/static/description/index.html
  web_domain_field_example/views/menu.xml
  web_domain_field_example/views/product_selection_example.xml
Labels: approved, bot is merging ⏳, ready to merge

#1523 [12.0][MIG] web_widget_child_selector
  web_widget_child_selector/README.rst
  web_widget_child_selector/__init__.py
  web_widget_child_selector/__manifest__.py
  web_widget_child_selector/models/__init__.py
  web_widget_child_selector/models/base.py
  web_widget_child_selector/readme/CONTRIBUTORS.rst
  web_widget_child_selector/readme/DESCRIPTION.rst
  web_widget_child_selector/readme/USAGE.rst
  web_widget_child_selector/static/description/edit_mode.png
  web_widget_child_selector/static/description/icon.png
  web_widget_child_selector/static/description/index.html
  web_widget_child_selector/static/src/js/widget_child_selector.js
  web_widget_child_selector/static/src/less/widget_child_selector.less
  web_widget_child_selector/static/src/xml/widget_child_selector.xml
  web_widget_child_selector/tests/__init__.py
  web_widget_child_selector/tests/test_widget_child_selector.py
  web_widget_child_selector/views/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1522 [12.0][MIG] web_view_calendar_column
  web_view_calendar_column/README.rst
  web_view_calendar_column/__init__.py
  web_view_calendar_column/__manifest__.py
  web_view_calendar_column/i18n/web_view_calendar_column.pot
  web_view_calendar_column/readme/CONTRIBUTORS.rst
  web_view_calendar_column/readme/DESCRIPTION.rst
  web_view_calendar_column/readme/USAGE.rst
  web_view_calendar_column/static/description/icon.png
  web_view_calendar_column/static/description/index.html
  web_view_calendar_column/static/lib/scheduler.min.css
  web_view_calendar_column/static/lib/scheduler.min.js
  web_view_calendar_column/static/src/js/calendar_controller.js
  web_view_calendar_column/static/src/js/calendar_model.js
  web_view_calendar_column/static/src/js/calendar_renderer.js
  web_view_calendar_column/static/src/js/calendar_view.js
  web_view_calendar_column/views/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1347 [12.0][IMP] Allow to specify a field on timeline view to define the element color.
  web_timeline/README.rst
  web_timeline/readme/CONFIGURE.rst
  web_timeline/static/src/js/timeline_renderer.js
  web_timeline/static/src/js/timeline_view.js
Labels: approved, bot is merging ⏳, ready to merge

#1537 [13.0][MIG] web_tree_image_tooltip
  setup/web_tree_image_tooltip/odoo/addons/web_tree_image_tooltip
  setup/web_tree_image_tooltip/setup.py
  web_tree_image_tooltip/README.rst
  web_tree_image_tooltip/__init__.py
  web_tree_image_tooltip/__manifest__.py
  web_tree_image_tooltip/i18n/web_tree_image.pot
  web_tree_image_tooltip/i18n/web_tree_image_tooltip.pot
  web_tree_image_tooltip/i18n/zh_CN.po
  web_tree_image_tooltip/readme/CONFIGURE.rst
  web_tree_image_tooltip/readme/CONTRIBUTORS.rst
  web_tree_image_tooltip/readme/CREDITS.rst
  web_tree_image_tooltip/readme/DESCRIPTION.rst
  web_tree_image_tooltip/readme/USAGE.rst
  web_tree_image_tooltip/static/description/icon.png
  web_tree_image_tooltip/static/description/index.html
  web_tree_image_tooltip/static/src/js/tooltip.js
  web_tree_image_tooltip/static/src/scss/common.scss
  web_tree_image_tooltip/view/assets.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1848 [12.0][IMP] web_pwa_oca: Add support for require system
  web_pwa_oca/__manifest__.py
  web_pwa_oca/controllers/__init__.py
  web_pwa_oca/controllers/main.py
  web_pwa_oca/controllers/service_worker.py
  web_pwa_oca/i18n/es.po
  web_pwa_oca/i18n/web_pwa_oca.pot
  web_pwa_oca/readme/ROADMAP.rst
  web_pwa_oca/static/src/js/worker/jquery-sw-compat.js
  web_pwa_oca/static/src/js/worker/libs/class.js
  web_pwa_oca/static/src/js/worker/pwa.js
  web_pwa_oca/templates/service_worker.xml
Labels: approved, bot is merging ⏳

#1853 [13.0][IMP] web_responsive: Scrollable dropdowns
  web_responsive/README.rst
  web_responsive/readme/DESCRIPTION.rst
  web_responsive/static/description/index.html
  web_responsive/static/img/dropdown_scroll.gif
  web_responsive/static/src/css/web_responsive.scss
Labels: approved, bot is merging ⏳

#1743 [12.0][ADD] web_widget_one2many_product_picker_sale_stock
  oca_dependencies.txt
  web_widget_one2many_product_picker_sale_stock/README.rst
  web_widget_one2many_product_picker_sale_stock/__init__.py
  web_widget_one2many_product_picker_sale_stock/__manifest__.py
  web_widget_one2many_product_picker_sale_stock/readme/CONTRIBUTORS.rst
  web_widget_one2many_product_picker_sale_stock/readme/DESCRIPTION.rst
  web_widget_one2many_product_picker_sale_stock/readme/USAGE.rst
  web_widget_one2many_product_picker_sale_stock/static/description/index.html
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/abstract_view.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker_sale_stock/static/src/scss/one2many_product_picker.scss
  web_widget_one2many_product_picker_sale_stock/static/src/xml/one2many_product_picker.xml
  web_widget_one2many_product_picker_sale_stock/templates/assets.xml
Labels: bot is merging ⏳

#1825 [12.0][FIX] web_widget_one2many_product_picker: Auto save
  web_widget_one2many_product_picker/README.rst
  web_widget_one2many_product_picker/readme/CONFIGURE.rst
  web_widget_one2many_product_picker/static/description/index.html
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_modif_price_form_view.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker/static/src/js/views/basic_model.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker/static/src/xml/one2many_product_picker.xml
Labels: bot is merging ⏳

#1856 [13.0][FIX] web_responsive: Scrollable dropdowns
  web_responsive/static/src/css/web_responsive.scss
Labels: bot is merging ⏳

#1864 [13.0][FIX] web_widget_domain_editor_dialog: Example picture not display on README
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/readme/USAGE.rst
  web_widget_domain_editor_dialog/static/description/index.html
Labels: bot is merging ⏳

#1865 [11.0][FIX] web_widget_domain_editor_dialog: Example picture not display on README
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/readme/USAGE.rst
  web_widget_domain_editor_dialog/static/description/index.html
Labels: bot is merging ⏳

#1866 [12.0][FIX] web_widget_domain_editor_dialog: Example picture not display on README
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/readme/USAGE.rst
  web_widget_domain_editor_dialog/static/description/index.html
Labels: bot is merging ⏳

#1851 [14.0] [MIG] Migrated web_timeline Module.
  setup/web_timeline/odoo/addons/web_timeline
  setup/web_timeline/setup.py
  web_timeline/README.rst
  web_timeline/__init__.py
  web_timeline/__manifest__.py
  web_timeline/i18n/es.po
  web_timeline/i18n/fr.po
  web_timeline/i18n/he.po
  web_timeline/i18n/hr.po
  web_timeline/i18n/nl_NL.po
  web_timeline/i18n/pt.po
  web_timeline/i18n/pt_BR.po
  web_timeline/i18n/web_timeline.pot
  web_timeline/i18n/zh_CN.po
  web_timeline/models/__init__.py
  web_timeline/models/ir_ui_view.py
  web_timeline/readme/CONFIGURE.rst
  web_timeline/readme/CONTRIBUTORS.rst
  web_timeline/readme/DESCRIPTION.rst
  web_timeline/readme/ROADMAP.rst
  web_timeline/readme/USAGE.rst
  web_timeline/static/description/icon.png
  web_timeline/static/description/index.html
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.css
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js
  web_timeline/static/src/js/timeline_canvas.js
  web_timeline/static/src/js/timeline_controller.js
  web_timeline/static/src/js/timeline_model.js
  web_timeline/static/src/js/timeline_renderer.js
  web_timeline/static/src/js/timeline_view.js
  web_timeline/static/src/scss/web_timeline.scss
  web_timeline/static/src/xml/web_timeline.xml
  web_timeline/views/web_timeline.xml
Labels: approved, bot is merging ⏳, ready to merge

#1860 [13.0][MIG] web_group_expand
  setup/web_group_expand/odoo/addons/web_group_expand
  setup/web_group_expand/setup.py
  web_group_expand/README.rst
  web_group_expand/__init__.py
  web_group_expand/__manifest__.py
  web_group_expand/i18n/ca.po
  web_group_expand/i18n/es.po
  web_group_expand/i18n/nl.po
  web_group_expand/i18n/pt_BR.po
  web_group_expand/i18n/web_group_expand.pot
  web_group_expand/readme/CONTRIBUTORS.rst
  web_group_expand/readme/DESCRIPTION.rst
  web_group_expand/static/description/icon.png
  web_group_expand/static/description/index.html
  web_group_expand/static/src/js/web_group_expand.js
  web_group_expand/static/src/xml/expand_buttons.xml
  web_group_expand/views/templates.xml
Labels: approved, bot is merging ⏳

#1857 [13.0][IMP] web_pwa_oca: Port changes from 12.0
  web_pwa_oca/README.rst
  web_pwa_oca/__init__.py
  web_pwa_oca/__manifest__.py
  web_pwa_oca/controllers/__init__.py
  web_pwa_oca/controllers/main.py
  web_pwa_oca/controllers/service_worker.py
  web_pwa_oca/i18n/es.po
  web_pwa_oca/i18n/web_pwa_oca.pot
  web_pwa_oca/models/__init__.py
  web_pwa_oca/models/res_config_settings.py
  web_pwa_oca/readme/CONFIGURE.rst
  web_pwa_oca/readme/CONTRIBUTORS.rst
  web_pwa_oca/readme/DESCRIPTION.rst
  web_pwa_oca/readme/INSTALL.rst
  web_pwa_oca/readme/ROADMAP.rst
  web_pwa_oca/readme/USAGE.rst
  web_pwa_oca/static/description/index.html
  web_pwa_oca/static/img/icons/odoo_logo.svg
  web_pwa_oca/static/src/js/pwa_install.js
  web_pwa_oca/static/src/js/pwa_manager.js
  web_pwa_oca/static/src/js/webclient.js
  web_pwa_oca/static/src/js/worker/jquery-sw-compat.js
  web_pwa_oca/static/src/js/worker/pwa.js
  web_pwa_oca/static/src/xml/pwa_install.xml
  web_pwa_oca/templates/assets.xml
  web_pwa_oca/tests/__init__.py
  web_pwa_oca/tests/test_web_pwa_oca_controller.py
  web_pwa_oca/views/res_config_settings_views.xml
  web_pwa_oca/views/webclient_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#1881 [FIX] web_ir_actions_act_multi: preprocess chained actions
  web_ir_actions_act_multi/static/src/js/web_ir_actions_act_multi.js
Labels: approved, bot is merging ⏳

#1862 [12.0][FIX] web_widget_one2many_product_picker: Dulicity records on mobile
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_create_form_view.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
Labels: approved

#1791 [MIG] [14.0] web_copy_confirm
  setup/web_copy_confirm/odoo/addons/web_copy_confirm
  setup/web_copy_confirm/setup.py
  web_copy_confirm/README.rst
  web_copy_confirm/__init__.py
  web_copy_confirm/__manifest__.py
  web_copy_confirm/i18n/web_copy_confirm.pot
  web_copy_confirm/readme/CONTRIBUTORS.rst
  web_copy_confirm/readme/DESCRIPTION.rst
  web_copy_confirm/readme/HISTORY.rst
  web_copy_confirm/readme/newsfragments/.gitkeep
  web_copy_confirm/static/description/icon.png
  web_copy_confirm/static/description/index.html
  web_copy_confirm/static/src/js/web_copy_confirm.js
  web_copy_confirm/static/tests/confirm_tests.js
  web_copy_confirm/views/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1885 [14.0][FIX] requirement for bokeh should specify the version
  requirements.txt
  web_widget_bokeh_chart/__manifest__.py
Labels: approved, bot is merging ⏳

#1883 [14.0][FIX] web_responsive error on grouped mobile kanban with zero groups
  web_responsive/static/src/css/web_responsive.scss
  web_responsive/static/src/js/kanban_renderer_mobile.js
Labels: approved, bot is merging ⏳
