Repository OCA/web, pull requests merged in 2021-12, with the labels that each got.

#2092 [15.0][MIG] web_refresher: Migration to 15.0
  setup/web_refresher/odoo/addons/web_refresher
  setup/web_refresher/setup.py
  web_refresher/README.rst
  web_refresher/__init__.py
  web_refresher/__manifest__.py
  web_refresher/i18n/ca.po
  web_refresher/i18n/es.po
  web_refresher/i18n/pt_BR.po
  web_refresher/i18n/web_refresher.pot
  web_refresher/readme/CONTRIBUTORS.rst
  web_refresher/readme/DESCRIPTION.rst
  web_refresher/static/description/icon.png
  web_refresher/static/description/index.html
  web_refresher/static/description/refresh.png
  web_refresher/static/src/xml/pager_button.xml
Labels: approved, bot is merging ⏳

#2004 [14.0][FIX] web_m2x_options: fix search_more behaviour
  web_m2x_options/static/src/js/form.js
Labels: approved, bot is merging ⏳

#1950 [IMP] web_tree_dynamic_colored_field : Add bg_color_field option
  web_tree_dynamic_colored_field/__manifest__.py
  web_tree_dynamic_colored_field/readme/CONTRIBUTORS.rst
  web_tree_dynamic_colored_field/readme/USAGE.rst
  web_tree_dynamic_colored_field/static/src/js/web_tree_dynamic_colored_field.js
Labels: needs review, bot is merging ⏳

#2013 [12.0][FIX] web_timeline UTC timezone and + 1 hour when adding events
  web_timeline/static/src/js/timeline_controller.js
Labels: approved, ready to merge, merged 🎉

#1757 [14.0][mig] web_ir_actions_act_window_message
  web_ir_actions_act_window_message/README.rst
  web_ir_actions_act_window_message/__init__.py
  web_ir_actions_act_window_message/__manifest__.py
  web_ir_actions_act_window_message/i18n/ar.po
  web_ir_actions_act_window_message/i18n/de.po
  web_ir_actions_act_window_message/i18n/es.po
  web_ir_actions_act_window_message/i18n/eu.po
  web_ir_actions_act_window_message/i18n/fi.po
  web_ir_actions_act_window_message/i18n/fr.po
  web_ir_actions_act_window_message/i18n/hr.po
  web_ir_actions_act_window_message/i18n/it.po
  web_ir_actions_act_window_message/i18n/nl.po
  web_ir_actions_act_window_message/i18n/nl_NL.po
  web_ir_actions_act_window_message/i18n/pt.po
  web_ir_actions_act_window_message/i18n/pt_BR.po
  web_ir_actions_act_window_message/i18n/ro.po
  web_ir_actions_act_window_message/i18n/sl.po
  web_ir_actions_act_window_message/i18n/tr.po
  web_ir_actions_act_window_message/i18n/web_ir_actions_act_window_message.pot
  web_ir_actions_act_window_message/models/__init__.py
  web_ir_actions_act_window_message/models/ir_actions.py
  web_ir_actions_act_window_message/readme/CONTRIBUTORS.rst
  web_ir_actions_act_window_message/readme/DESCRIPTION.rst
  web_ir_actions_act_window_message/readme/ROADMAP.rst
  web_ir_actions_act_window_message/readme/USAGE.rst
  web_ir_actions_act_window_message/security/ir.model.access.csv
  web_ir_actions_act_window_message/static/description/icon.png
  web_ir_actions_act_window_message/static/description/index.html
  web_ir_actions_act_window_message/static/src/js/web_ir_actions_act_window_message.js
  web_ir_actions_act_window_message/static/src/xml/web_ir_actions_act_window_message.xml
  web_ir_actions_act_window_message/views/templates.xml
Labels: bot is merging ⏳

#2108 [14.0][MIG] web_widget_plotly_chart: Migration to 14.0
  requirements.txt
  setup/web_widget_plotly_chart/odoo/addons/web_widget_plotly_chart
  setup/web_widget_plotly_chart/setup.py
  web_widget_plotly_chart/README.rst
  web_widget_plotly_chart/__init__.py
  web_widget_plotly_chart/__manifest__.py
  web_widget_plotly_chart/i18n/ca.po
  web_widget_plotly_chart/i18n/da.po
  web_widget_plotly_chart/i18n/es.po
  web_widget_plotly_chart/i18n/pt_BR.po
  web_widget_plotly_chart/i18n/web_widget_plotly_chart.pot
  web_widget_plotly_chart/readme/CONTRIBUTORS.rst
  web_widget_plotly_chart/readme/CREDITS.rst
  web_widget_plotly_chart/readme/DESCRIPTION.rst
  web_widget_plotly_chart/readme/INSTALL.rst
  web_widget_plotly_chart/readme/USAGE.rst
  web_widget_plotly_chart/static/description/example.png
  web_widget_plotly_chart/static/description/icon.png
  web_widget_plotly_chart/static/description/index.html
  web_widget_plotly_chart/static/src/js/widget_plotly.js
  web_widget_plotly_chart/static/src/lib/plotly/plotly-2.7.0.min.js
  web_widget_plotly_chart/views/web_widget_plotly_chart.xml
Labels: approved, bot is merging ⏳

#2072 [13.0][MIG] web_set_single_page_hidden
  setup/web_set_single_page_hidden/odoo/addons/web_set_single_page_hidden
  setup/web_set_single_page_hidden/setup.py
  web_set_single_page_hidden/README.rst
  web_set_single_page_hidden/__init__.py
  web_set_single_page_hidden/__manifest__.py
  web_set_single_page_hidden/i18n/pt_BR.po
  web_set_single_page_hidden/i18n/web_set_single_page_hidden.pot
  web_set_single_page_hidden/readme/CONTRIBUTORS.rst
  web_set_single_page_hidden/readme/DESCRIPTION.rst
  web_set_single_page_hidden/static/description/icon.png
  web_set_single_page_hidden/static/description/index.html
  web_set_single_page_hidden/static/src/js/pager.js
  web_set_single_page_hidden/static/src/js/relational_fields.js
  web_set_single_page_hidden/views/webclient_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#2112 [FIX][12.0] web_dashboard_tile : fix CSS
  web_dashboard_tile/__manifest__.py
  web_dashboard_tile/views/templates.xml
Labels: bot is merging ⏳

#2116 [15.0][MIG] web_company_color
  setup/web_company_color/odoo/addons/web_company_color
  setup/web_company_color/setup.py
  web_company_color/README.rst
  web_company_color/__init__.py
  web_company_color/__manifest__.py
  web_company_color/hooks.py
  web_company_color/i18n/ca.po
  web_company_color/i18n/de.po
  web_company_color/i18n/hr.po
  web_company_color/i18n/it.po
  web_company_color/i18n/nl.po
  web_company_color/i18n/web_company_color.pot
  web_company_color/i18n/zh_CN.po
  web_company_color/models/__init__.py
  web_company_color/models/assetsbundle.py
  web_company_color/models/ir_qweb.py
  web_company_color/models/res_company.py
  web_company_color/readme/CONTRIBUTORS.rst
  web_company_color/readme/DESCRIPTION.rst
  web_company_color/readme/ROADMAP.rst
  web_company_color/readme/USAGE.rst
  web_company_color/static/description/icon.png
  web_company_color/static/description/index.html
  web_company_color/tests/__init__.py
  web_company_color/tests/test_res_company.py
  web_company_color/utils.py
  web_company_color/view/assets.xml
  web_company_color/view/res_company.xml
Labels: approved, bot is merging ⏳
