Repository OCA/web, pull requests merged in 2021-09, with the labels that each got.

#1958 [MIG] web_view_calendar_list: Migration to 13.0
  setup/web_view_calendar_list/odoo/addons/web_view_calendar_list
  setup/web_view_calendar_list/setup.py
  web_view_calendar_list/README.rst
  web_view_calendar_list/__init__.py
  web_view_calendar_list/__manifest__.py
  web_view_calendar_list/i18n/ca.po
  web_view_calendar_list/i18n/es.po
  web_view_calendar_list/i18n/pt_BR.po
  web_view_calendar_list/i18n/web_view_calendar_list.pot
  web_view_calendar_list/models/__init__.py
  web_view_calendar_list/models/ir_actions_act_window_view.py
  web_view_calendar_list/models/ir_ui_view.py
  web_view_calendar_list/readme/CONTRIBUTORS.rst
  web_view_calendar_list/readme/DESCRIPTION.rst
  web_view_calendar_list/readme/USAGE.rst
  web_view_calendar_list/static/description/icon.png
  web_view_calendar_list/static/description/index.html
  web_view_calendar_list/static/src/js/calendar_list_controller.js
  web_view_calendar_list/static/src/js/calendar_list_model.js
  web_view_calendar_list/static/src/js/calendar_list_renderer.js
  web_view_calendar_list/static/src/js/calendar_list_view.js
  web_view_calendar_list/templates/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#2022 [FIX] web_widget_x2many_2d_matrix: remove console.log
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
Labels: bot is merging ⏳

#1937 [14.0] [MIG] web_widget_mpld3_chart
  requirements.txt
  setup/web_widget_mpld3_chart/odoo/addons/web_widget_mpld3_chart
  setup/web_widget_mpld3_chart/setup.py
  web_widget_mpld3_chart/README.rst
  web_widget_mpld3_chart/__init__.py
  web_widget_mpld3_chart/__manifest__.py
  web_widget_mpld3_chart/i18n/es.po
  web_widget_mpld3_chart/i18n/web_widget_mpld3_chart.pot
  web_widget_mpld3_chart/readme/CONTRIBUTORS.rst
  web_widget_mpld3_chart/readme/CREDITS.rst
  web_widget_mpld3_chart/readme/DESCRIPTION.rst
  web_widget_mpld3_chart/readme/INSTALL.rst
  web_widget_mpld3_chart/readme/USAGE.rst
  web_widget_mpld3_chart/static/description/icon.png
  web_widget_mpld3_chart/static/description/index.html
  web_widget_mpld3_chart/static/src/js/web_widget_mpld3_chart.js
  web_widget_mpld3_chart/static/src/lib/d3/d3.v3.min.js
  web_widget_mpld3_chart/static/src/lib/mpld3/mpld3.v0.3.1.dev1.js
  web_widget_mpld3_chart/views/web_widget_mpld3_chart.xml
Labels: approved, ready to merge, bot is merging ⏳

#2024 [12.0][ADD] web_widget_one2many_product_picker_sale_stock_available_info_popup
  web_widget_one2many_product_picker_sale_stock_available_info_popup/README.rst
  web_widget_one2many_product_picker_sale_stock_available_info_popup/__init__.py
  web_widget_one2many_product_picker_sale_stock_available_info_popup/__manifest__.py
  web_widget_one2many_product_picker_sale_stock_available_info_popup/readme/CONTRIBUTORS.rst
  web_widget_one2many_product_picker_sale_stock_available_info_popup/readme/DESCRIPTION.rst
  web_widget_one2many_product_picker_sale_stock_available_info_popup/static/description/icon.png
  web_widget_one2many_product_picker_sale_stock_available_info_popup/static/description/index.html
  web_widget_one2many_product_picker_sale_stock_available_info_popup/static/src/js/views/abstract_view.js
  web_widget_one2many_product_picker_sale_stock_available_info_popup/templates/assets.xml
Labels: approved, bot is merging ⏳

#1977 [14.0] [mig] web_widget_numeric_step
  setup/web_widget_numeric_step/odoo/addons/web_widget_numeric_step
  setup/web_widget_numeric_step/setup.py
  web_widget_numeric_step/README.rst
  web_widget_numeric_step/__init__.py
  web_widget_numeric_step/__manifest__.py
  web_widget_numeric_step/demo/res_users_view.xml
  web_widget_numeric_step/i18n/es.po
  web_widget_numeric_step/i18n/fr.po
  web_widget_numeric_step/i18n/it.po
  web_widget_numeric_step/i18n/web_widget_numeric_step.pot
  web_widget_numeric_step/readme/CONTRIBUTORS.rst
  web_widget_numeric_step/readme/DESCRIPTION.rst
  web_widget_numeric_step/readme/USAGE.rst
  web_widget_numeric_step/static/description/add_two_buttons.png
  web_widget_numeric_step/static/description/icon.png
  web_widget_numeric_step/static/description/index.html
  web_widget_numeric_step/static/description/step0,25andlimits.gif
  web_widget_numeric_step/static/description/step10_limit15_placeholder117_with_onchange.gif
  web_widget_numeric_step/static/src/css/numeric_step.scss
  web_widget_numeric_step/static/src/js/numeric_step.js
  web_widget_numeric_step/static/src/xml/numeric_step.xml
  web_widget_numeric_step/view/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#1959 [MIG] web_widget_child_selector: Migration to 13.0
  setup/web_widget_child_selector/odoo/addons/web_widget_child_selector
  setup/web_widget_child_selector/setup.py
  web_widget_child_selector/README.rst
  web_widget_child_selector/__init__.py
  web_widget_child_selector/__manifest__.py
  web_widget_child_selector/i18n/pt_BR.po
  web_widget_child_selector/i18n/web_widget_child_selector.pot
  web_widget_child_selector/models/__init__.py
  web_widget_child_selector/models/base.py
  web_widget_child_selector/readme/CONTRIBUTORS.rst
  web_widget_child_selector/readme/DESCRIPTION.rst
  web_widget_child_selector/readme/USAGE.rst
  web_widget_child_selector/static/description/edit_mode.png
  web_widget_child_selector/static/description/icon.png
  web_widget_child_selector/static/description/index.html
  web_widget_child_selector/static/src/js/widget_child_selector.js
  web_widget_child_selector/static/src/scss/widget_child_selector.scss
  web_widget_child_selector/static/src/xml/widget_child_selector.xml
  web_widget_child_selector/tests/__init__.py
  web_widget_child_selector/tests/test_widget_child_selector.py
  web_widget_child_selector/views/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#1974 [IMP] web_translate_dialog: fwd port to 13.0
  web_translate_dialog/static/src/js/web_translate_dialog.js
  web_translate_dialog/static/src/xml/base.xml
Labels: approved, ready to merge, bot is merging ⏳

#2027 [FIX] web_widget_bokeh_chart: remove custom-bokeh.scss
  web_widget_bokeh_chart/static/src/scss/custom-bokeh.scss
  web_widget_bokeh_chart/views/web_widget_bokeh_chart.xml
Labels: approved, ready to merge, bot is merging ⏳

#1978 [14.0][mig]web_send_message_popup
  setup/web_send_message_popup/odoo/addons/web_send_message_popup
  setup/web_send_message_popup/setup.py
  web_send_message_popup/README.rst
  web_send_message_popup/__init__.py
  web_send_message_popup/__manifest__.py
  web_send_message_popup/i18n/web_send_message_popup.pot
  web_send_message_popup/readme/CONTRIBUTORS.rst
  web_send_message_popup/readme/DESCRIPTION.rst
  web_send_message_popup/static/description/icon.png
  web_send_message_popup/static/description/index.html
  web_send_message_popup/static/src/js/chatter.js
  web_send_message_popup/templates/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#2025 [12.0] web_widget_digitized_signature: Allow employee user to set their own signature in preferences view
  web_widget_digitized_signature/models/mail_thread.py
  web_widget_digitized_signature/models/res_users.py
  web_widget_digitized_signature/tests/test_signature_tracking.py
  web_widget_digitized_signature/views/res_users_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1980 [14.0][mig]web_switch_context_warning
  setup/web_switch_context_warning/odoo/addons/web_switch_context_warning
  setup/web_switch_context_warning/setup.py
  web_switch_context_warning/README.rst
  web_switch_context_warning/__init__.py
  web_switch_context_warning/__manifest__.py
  web_switch_context_warning/i18n/fr.po
  web_switch_context_warning/i18n/web_switch_company_warning.pot
  web_switch_context_warning/i18n/web_switch_context_warning.pot
  web_switch_context_warning/i18n/zh_CN.po
  web_switch_context_warning/readme/CONTRIBUTORS.rst
  web_switch_context_warning/readme/DESCRIPTION.rst
  web_switch_context_warning/readme/ROADMAP.rst
  web_switch_context_warning/readme/USAGE.rst
  web_switch_context_warning/static/description/icon.png
  web_switch_context_warning/static/description/index.html
  web_switch_context_warning/static/src/js/switch_context_warning.js
  web_switch_context_warning/static/src/js/switch_context_warning_worker.js
  web_switch_context_warning/static/src/xml/switch_context_warning.xml
  web_switch_context_warning/view/view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2003 [14.0] [FIX] web_advanced_search: Many2one selection on Filters missing
  web_advanced_search/static/src/js/control_panel/custom_filter_item.js
  web_advanced_search/static/src/js/relational.js
  web_advanced_search/static/src/xml/web_advanced_search.xml
  web_advanced_search/views/templates.xml
Labels: approved, bot is merging ⏳

#2034 [14.0] Updated from template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/stale.yml
  .pre-commit-config.yaml
  README.md
Labels: approved

#1984 [14.0] [mig] web_widget_many2one_simple
  setup/web_widget_many2one_simple/odoo/addons/web_widget_many2one_simple
  setup/web_widget_many2one_simple/setup.py
  web_widget_many2one_simple/README.rst
  web_widget_many2one_simple/__init__.py
  web_widget_many2one_simple/__manifest__.py
  web_widget_many2one_simple/i18n/es.po
  web_widget_many2one_simple/i18n/web_widget_many2one_simple.pot
  web_widget_many2one_simple/readme/CONFIGURE.rst
  web_widget_many2one_simple/readme/CONTRIBUTORS.rst
  web_widget_many2one_simple/readme/DESCRIPTION.rst
  web_widget_many2one_simple/readme/USAGE.rst
  web_widget_many2one_simple/static/description/icon.png
  web_widget_many2one_simple/static/description/index.html
  web_widget_many2one_simple/static/img/preview.gif
  web_widget_many2one_simple/static/src/css/many2one_simple.scss
  web_widget_many2one_simple/static/src/js/many2one_simple_field.js
  web_widget_many2one_simple/static/src/xml/many2one_simple.xml
  web_widget_many2one_simple/views/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#1952 [14.0][ADD] web_widget_char_size
  setup/web_widget_char_size/odoo/addons/web_widget_char_size
  setup/web_widget_char_size/setup.py
  web_widget_char_size/__init__.py
  web_widget_char_size/__manifest__.py
  web_widget_char_size/readme/DESCRIPTION.rst
  web_widget_char_size/static/src/js/char_widget.js
  web_widget_char_size/views/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#2031 [13.0][ADD] web_time_range_menu_custom
  setup/web_time_range_menu_custom/odoo/addons/web_time_range_menu_custom
  setup/web_time_range_menu_custom/setup.py
  web_time_range_menu_custom/README.rst
  web_time_range_menu_custom/__init__.py
  web_time_range_menu_custom/__manifest__.py
  web_time_range_menu_custom/readme/CONTRIBUTORS.rst
  web_time_range_menu_custom/readme/DESCRIPTION.rst
  web_time_range_menu_custom/static/description/icon.png
  web_time_range_menu_custom/static/description/index.html
  web_time_range_menu_custom/static/src/js/control_panel_controller.js
  web_time_range_menu_custom/static/src/js/control_panel_model.js
  web_time_range_menu_custom/static/src/js/control_panel_view_parameters.js
  web_time_range_menu_custom/static/src/js/domain.js
  web_time_range_menu_custom/static/src/js/search_facet.js
  web_time_range_menu_custom/static/src/js/time_range_menu.js
  web_time_range_menu_custom/static/src/xml/time_range_menu.xml
  web_time_range_menu_custom/templates/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#2037 [ADD] github stale action: Work on oldest issues/prs first
  .copier-answers.yml
  .github/workflows/stale.yml
Labels: approved

#2036 [13.0][FIX] web_drop_target: Don't collide with odoo drag and drop implementation
  web_drop_target/README.rst
  web_drop_target/readme/CONTRIBUTORS.rst
  web_drop_target/static/description/index.html
  web_drop_target/static/src/js/web_drop_target.js
  web_drop_target/static/src/scss/web_drop_target.scss
  web_drop_target/static/src/xml/widgets.xml
Labels: approved, bot is merging ⏳
