Repository OCA/web, pull requests merged in 2021-06, with the labels that each got.

#1941 [12.0][IMP] web_widget_one2many_product_picker: self-refresh
  web_widget_one2many_product_picker/README.rst
  web_widget_one2many_product_picker/readme/CONFIGURE.rst
  web_widget_one2many_product_picker/static/description/index.html
  web_widget_one2many_product_picker/static/src/js/views/basic_controller.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker/templates/assets.xml
Labels: approved, bot is merging ⏳

#1903 [IMP] web_company_color: Support button and link customizing
  web_company_color/models/res_company.py
  web_company_color/view/res_company.xml
Labels: approved, bot is merging ⏳, ready to merge

#1801 [13.0] [mig] web_translate_dialog
  setup/web_translate_dialog/odoo/addons/web_translate_dialog
  setup/web_translate_dialog/setup.py
  web_translate_dialog/README.rst
  web_translate_dialog/__init__.py
  web_translate_dialog/__manifest__.py
  web_translate_dialog/i18n/ar.po
  web_translate_dialog/i18n/de.po
  web_translate_dialog/i18n/es.po
  web_translate_dialog/i18n/fi.po
  web_translate_dialog/i18n/fr.po
  web_translate_dialog/i18n/hr.po
  web_translate_dialog/i18n/it.po
  web_translate_dialog/i18n/nl.po
  web_translate_dialog/i18n/nl_NL.po
  web_translate_dialog/i18n/pt_BR.po
  web_translate_dialog/i18n/sl.po
  web_translate_dialog/i18n/tr.po
  web_translate_dialog/i18n/web_translate_dialog.pot
  web_translate_dialog/models/__init__.py
  web_translate_dialog/models/base.py
  web_translate_dialog/models/res_lang.py
  web_translate_dialog/readme/CONTRIBUTORS.rst
  web_translate_dialog/readme/DESCRIPTION.rst
  web_translate_dialog/readme/USAGE.rst
  web_translate_dialog/static/description/icon.png
  web_translate_dialog/static/description/index.html
  web_translate_dialog/static/src/css/base.css
  web_translate_dialog/static/src/js/web_translate_dialog.js
  web_translate_dialog/static/src/xml/base.xml
  web_translate_dialog/tests/__init__.py
  web_translate_dialog/tests/test_web_translate_dialog.py
  web_translate_dialog/views/res_lang.xml
  web_translate_dialog/views/web_translate.xml
Labels: approved, bot is merging ⏳, ready to merge

#1914 [14.0][MIG] web_group_expand
  web_group_expand/README.rst
  web_group_expand/__init__.py
  web_group_expand/__manifest__.py
  web_group_expand/i18n/ca.po
  web_group_expand/i18n/es.po
  web_group_expand/i18n/nl.po
  web_group_expand/i18n/pt_BR.po
  web_group_expand/i18n/web_group_expand.pot
  web_group_expand/readme/CONTRIBUTORS.rst
  web_group_expand/readme/DESCRIPTION.rst
  web_group_expand/static/description/icon.png
  web_group_expand/static/description/index.html
  web_group_expand/static/src/js/web_group_expand.js
  web_group_expand/static/src/xml/expand_buttons.xml
  web_group_expand/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#1845 [14.0] [MIG] web_no_bubble migration to 14.0
  setup/web_no_bubble/odoo/addons/web_no_bubble
  setup/web_no_bubble/setup.py
  web_no_bubble/README.rst
  web_no_bubble/__init__.py
  web_no_bubble/__manifest__.py
  web_no_bubble/i18n/es.po
  web_no_bubble/i18n/fr_FR.po
  web_no_bubble/i18n/hr.po
  web_no_bubble/i18n/web_no_bubble.pot
  web_no_bubble/i18n/zh_CN.po
  web_no_bubble/readme/CONTRIBUTORS.rst
  web_no_bubble/readme/DESCRIPTION.rst
  web_no_bubble/static/description/icon.png
  web_no_bubble/static/description/index.html
  web_no_bubble/static/src/css/web_no_bubble.scss
  web_no_bubble/views/web_no_bubble.xml
Labels: approved, bot is merging ⏳, ready to merge

#1811 [13.0][mig] web_send_message_popup
  .prettierrc.yml
  setup/web_send_message_popup/odoo/addons/web_send_message_popup
  setup/web_send_message_popup/setup.py
  web_send_message_popup/README.rst
  web_send_message_popup/__init__.py
  web_send_message_popup/__manifest__.py
  web_send_message_popup/readme/CONTRIBUTORS.rst
  web_send_message_popup/readme/DESCRIPTION.rst
  web_send_message_popup/static/description/icon.png
  web_send_message_popup/static/description/index.html
  web_send_message_popup/static/src/js/chatter.js
  web_send_message_popup/templates/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1951 [13.0][FIX] web_responsive: Show history section in discuss mobile
  web_responsive/static/src/css/web_responsive.scss
  web_responsive/static/src/js/discuss.js
Labels: bot is merging ⏳
