Repository OCA/web, pull requests merged in 2021-08, with the labels that each got.

#1816 [MIG] web_ir_actions_act_view_reload: Migration to 14.0
  setup/web_ir_actions_act_view_reload/odoo/addons/web_ir_actions_act_view_reload
  setup/web_ir_actions_act_view_reload/setup.py
  web_ir_actions_act_view_reload/README.rst
  web_ir_actions_act_view_reload/__init__.py
  web_ir_actions_act_view_reload/__manifest__.py
  web_ir_actions_act_view_reload/i18n/web_ir_actions_act_view_reload.pot
  web_ir_actions_act_view_reload/i18n/zh_CN.po
  web_ir_actions_act_view_reload/readme/CONTRIBUTORS.rst
  web_ir_actions_act_view_reload/readme/DESCRIPTION.rst
  web_ir_actions_act_view_reload/readme/USAGE.rst
  web_ir_actions_act_view_reload/static/description/icon.png
  web_ir_actions_act_view_reload/static/description/index.html
  web_ir_actions_act_view_reload/static/src/js/web_ir_actions_act_view_reload.js
  web_ir_actions_act_view_reload/views/web_ir_actions_act_view_reload.xml
Labels: approved, bot is merging ⏳, ready to merge

#1635 [12.0][MIG] web_advanced_filter
  web_advanced_filter/README.rst
  web_advanced_filter/__init__.py
  web_advanced_filter/__manifest__.py
  web_advanced_filter/i18n/advanced_filter.pot
  web_advanced_filter/i18n/de.po
  web_advanced_filter/i18n/nl.po
  web_advanced_filter/models/__init__.py
  web_advanced_filter/models/ir_filters.py
  web_advanced_filter/readme/CONTRIBUTORS.rst
  web_advanced_filter/readme/CREDITS.rst
  web_advanced_filter/readme/DESCRIPTION.rst
  web_advanced_filter/readme/ROADMAP.rst
  web_advanced_filter/readme/USAGE.rst
  web_advanced_filter/static/description/icon.png
  web_advanced_filter/static/description/index.html
  web_advanced_filter/static/src/css/web_advanced_filter.css
  web_advanced_filter/static/src/js/web_advanced_filter.js
  web_advanced_filter/static/src/xml/web_advanced_filter.xml
  web_advanced_filter/tests/__init__.py
  web_advanced_filter/tests/test_web_advanced_filter.py
  web_advanced_filter/views/ir_filters.xml
  web_advanced_filter/views/templates.xml
  web_advanced_filter/wizards/__init__.py
  web_advanced_filter/wizards/ir_filters_combine_with_existing.py
  web_advanced_filter/wizards/ir_filters_combine_with_existing.xml
Labels: approved, bot is merging ⏳, ready to merge

#1869 [14.0][IMP] update readme and add translation status widget
  README.md
Labels: bot is merging ⏳

#1861 [12.0] web_m2x_options: fix always show search more
  web_m2x_options/static/src/js/form.js
Labels: approved, ready to merge, bot is merging ⏳

#1755 [14.0][mig] web_ir_actions_act_multi
  setup/web_ir_actions_act_multi/odoo/addons/web_ir_actions_act_multi
  setup/web_ir_actions_act_multi/setup.py
  web_ir_actions_act_multi/README.rst
  web_ir_actions_act_multi/__init__.py
  web_ir_actions_act_multi/__manifest__.py
  web_ir_actions_act_multi/i18n/web_ir_actions_act_multi.pot
  web_ir_actions_act_multi/models/__init__.py
  web_ir_actions_act_multi/models/ir_actions.py
  web_ir_actions_act_multi/readme/CONTRIBUTORS.rst
  web_ir_actions_act_multi/readme/DESCRIPTION.rst
  web_ir_actions_act_multi/readme/USAGE.rst
  web_ir_actions_act_multi/security/ir.model.access.csv
  web_ir_actions_act_multi/static/description/icon.png
  web_ir_actions_act_multi/static/description/index.html
  web_ir_actions_act_multi/static/src/js/web_ir_actions_act_multi.js
  web_ir_actions_act_multi/views/web_ir_actions_act_multi.xml
Labels: approved, bot is merging ⏳
