Repository OCA/web, pull requests merged in 2021-11, with the labels that each got.

#2060 [FIX] web_responsive: Traceback on grouped searchpanel
  web_responsive/static/src/js/web_responsive.js
Labels: bot is merging ⏳

#2069 [MIG] web_m2x_options: Migration to 15.0
  setup/web_m2x_options/odoo/addons/web_m2x_options
  setup/web_m2x_options/setup.py
  web_m2x_options/README.rst
  web_m2x_options/__init__.py
  web_m2x_options/__manifest__.py
  web_m2x_options/i18n/ar.po
  web_m2x_options/i18n/de.po
  web_m2x_options/i18n/es.po
  web_m2x_options/i18n/fi.po
  web_m2x_options/i18n/fr.po
  web_m2x_options/i18n/hr.po
  web_m2x_options/i18n/it.po
  web_m2x_options/i18n/nl.po
  web_m2x_options/i18n/nl_NL.po
  web_m2x_options/i18n/pt_BR.po
  web_m2x_options/i18n/sl.po
  web_m2x_options/i18n/tr.po
  web_m2x_options/i18n/web_m2x_options.pot
  web_m2x_options/i18n/zh_CN.po
  web_m2x_options/models/__init__.py
  web_m2x_options/models/ir_config_parameter.py
  web_m2x_options/readme/CONTRIBUTORS.rst
  web_m2x_options/readme/DESCRIPTION.rst
  web_m2x_options/readme/ROADMAP.rst
  web_m2x_options/readme/USAGE.rst
  web_m2x_options/static/description/icon.png
  web_m2x_options/static/description/index.html
  web_m2x_options/static/src/js/form.js
  web_m2x_options/static/src/xml/base.xml
  web_m2x_options/tests/__init__.py
  web_m2x_options/tests/test_ir_config_parameter.py
Labels: approved, bot is merging ⏳

#2055 [MIG] web_environment_ribbon: Migration to 15.0
  setup/web_environment_ribbon/odoo/addons/web_environment_ribbon
  setup/web_environment_ribbon/setup.py
  web_environment_ribbon/README.rst
  web_environment_ribbon/__init__.py
  web_environment_ribbon/__manifest__.py
  web_environment_ribbon/data/ribbon_data.xml
  web_environment_ribbon/i18n/ca.po
  web_environment_ribbon/i18n/de.po
  web_environment_ribbon/i18n/es.po
  web_environment_ribbon/i18n/fr.po
  web_environment_ribbon/i18n/hr.po
  web_environment_ribbon/i18n/nl.po
  web_environment_ribbon/i18n/nl_NL.po
  web_environment_ribbon/i18n/pt.po
  web_environment_ribbon/i18n/pt_BR.po
  web_environment_ribbon/i18n/sl.po
  web_environment_ribbon/i18n/web_environment_ribbon.pot
  web_environment_ribbon/i18n/zh_CN.po
  web_environment_ribbon/models/__init__.py
  web_environment_ribbon/models/web_environment_ribbon_backend.py
  web_environment_ribbon/readme/CONFIGURE.rst
  web_environment_ribbon/readme/CONTRIBUTORS.rst
  web_environment_ribbon/readme/DESCRIPTION.rst
  web_environment_ribbon/readme/USAGE.rst
  web_environment_ribbon/static/description/icon.png
  web_environment_ribbon/static/description/index.html
  web_environment_ribbon/static/description/screenshot.png
  web_environment_ribbon/static/src/css/ribbon.css
  web_environment_ribbon/static/src/js/ribbon.js
  web_environment_ribbon/tests/__init__.py
  web_environment_ribbon/tests/test_environment_ribbon_data.py
Labels: approved, bot is merging ⏳

#2062 [13.0][ADD] web_widget_one2many_tree_line_duplicate
  setup/web_widget_one2many_tree_line_duplicate/odoo/addons/web_widget_one2many_tree_line_duplicate
  setup/web_widget_one2many_tree_line_duplicate/setup.py
  web_widget_one2many_tree_line_duplicate/README.rst
  web_widget_one2many_tree_line_duplicate/__init__.py
  web_widget_one2many_tree_line_duplicate/__manifest__.py
  web_widget_one2many_tree_line_duplicate/readme/CONTRIBUTORS.rst
  web_widget_one2many_tree_line_duplicate/readme/DESCRIPTION.rst
  web_widget_one2many_tree_line_duplicate/readme/ROADMAP.rst
  web_widget_one2many_tree_line_duplicate/readme/USAGE.rst
  web_widget_one2many_tree_line_duplicate/static/description/index.html
  web_widget_one2many_tree_line_duplicate/static/src/js/basic_model.js
  web_widget_one2many_tree_line_duplicate/static/src/js/one2many_tree_line_duplicate.js
  web_widget_one2many_tree_line_duplicate/static/src/scss/one2many_tree_line_duplicate.scss
  web_widget_one2many_tree_line_duplicate/view/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#1991 [13.0][FIX] web_advanced_search: fix error when clicking Search More in sales dashboard
  web_advanced_search/static/src/js/web_advanced_search.js
Labels: approved, ready to merge, bot is merging ⏳

#2093 [13.0][IMP] web_responsive: Adapt label width
  web_responsive/README.rst
  web_responsive/readme/DESCRIPTION.rst
  web_responsive/static/description/index.html
  web_responsive/static/src/css/web_responsive.scss
  web_responsive/static/src/scss/web_responsive.scss
  web_responsive/views/assets.xml
Labels: approved, bot is merging ⏳

#2095 [14.0][IMP] web_responsive: Adapt label width
  web_responsive/README.rst
  web_responsive/readme/DESCRIPTION.rst
  web_responsive/static/description/index.html
  web_responsive/static/img/label_size_large.png
  web_responsive/static/img/label_size_small.png
  web_responsive/static/src/scss/kanban_view_mobile.scss
  web_responsive/static/src/scss/search_view_mobile.scss
  web_responsive/static/src/scss/web_responsive.scss
  web_responsive/views/assets.xml
Labels: approved, bot is merging ⏳

#1945 [14.0][MIG] web_widget_image_download
  setup/web_widget_image_download/odoo/addons/web_widget_image_download
  setup/web_widget_image_download/setup.py
  web_widget_image_download/README.rst
  web_widget_image_download/__init__.py
  web_widget_image_download/__manifest__.py
  web_widget_image_download/i18n/es.po
  web_widget_image_download/i18n/hr.po
  web_widget_image_download/i18n/lt.po
  web_widget_image_download/i18n/nl_NL.po
  web_widget_image_download/i18n/pt.po
  web_widget_image_download/i18n/web_widget_image_download.pot
  web_widget_image_download/i18n/zh_CN.po
  web_widget_image_download/readme/CONTRIBUTORS.rst
  web_widget_image_download/readme/DESCRIPTION.rst
  web_widget_image_download/readme/USAGE.rst
  web_widget_image_download/static/description/icon.png
  web_widget_image_download/static/description/index.html
  web_widget_image_download/static/src/js/web_widget_image_download.js
  web_widget_image_download/static/src/scss/web_widget_image_download.scss
  web_widget_image_download/static/src/xml/web_widget_image_download.xml
  web_widget_image_download/views/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#1428 12.0 mig web dashboard tile
  web_dashboard_tile/README.rst
  web_dashboard_tile/__init__.py
  web_dashboard_tile/__manifest__.py
  web_dashboard_tile/controllers/__init__.py
  web_dashboard_tile/controllers/main.py
  web_dashboard_tile/demo/tile_category.xml
  web_dashboard_tile/demo/tile_tile.xml
  web_dashboard_tile/i18n/fr.po
  web_dashboard_tile/migrations/12.0.1.0.0/post-migration.py
  web_dashboard_tile/models/__init__.py
  web_dashboard_tile/models/tile_category.py
  web_dashboard_tile/models/tile_tile.py
  web_dashboard_tile/readme/CONFIGURE.rst
  web_dashboard_tile/readme/CONTRIBUTORS.rst
  web_dashboard_tile/readme/DESCRIPTION.rst
  web_dashboard_tile/readme/ROADMAP.rst
  web_dashboard_tile/readme/USAGE.rst
  web_dashboard_tile/security/ir.model.access.csv
  web_dashboard_tile/security/ir_rule.xml
  web_dashboard_tile/static/description/favorite_menu_create_tile.png
  web_dashboard_tile/static/description/favorite_menu_create_tile_result.png
  web_dashboard_tile/static/description/icon.png
  web_dashboard_tile/static/description/index.html
  web_dashboard_tile/static/description/tile_category_form.png
  web_dashboard_tile/static/description/tile_tile_2_tree_view.png
  web_dashboard_tile/static/description/tile_tile_form.png
  web_dashboard_tile/static/description/tile_tile_form_secondary_value.png
  web_dashboard_tile/static/description/tile_tile_kanban.png
  web_dashboard_tile/static/src/css/web_dashboard_tile.css
  web_dashboard_tile/tests/__init__.py
  web_dashboard_tile/tests/test_tile.py
  web_dashboard_tile/views/menu.xml
  web_dashboard_tile/views/tile_category.xml
  web_dashboard_tile/views/tile_tile.xml
Labels: approved, bot is merging ⏳

#1703 [14.0][ADD] web_calendar_color_field
  setup/web_calendar_color_field/odoo/addons/web_calendar_color_field
  setup/web_calendar_color_field/setup.py
  web_calendar_color_field/__init__.py
  web_calendar_color_field/__manifest__.py
  web_calendar_color_field/readme/CONTRIBUTORS.rst
  web_calendar_color_field/readme/DESCRIPTION.rst
  web_calendar_color_field/readme/USAGE.rst
  web_calendar_color_field/static/src/js/calendar.js
  web_calendar_color_field/views/assets.xml
Labels: bot is merging ⏳

#2101 [14.0][FIX] web_responsive: Label width on modal
  web_responsive/static/src/scss/web_responsive.scss
Labels: approved, bot is merging ⏳
