Repository OCA/web, pull requests merged in 2021-04, with the labels that each got.

#1817 [MIG] web_tree_dynamic_colored_field: Migration to 14.0
  setup/web_tree_dynamic_colored_field/odoo/addons/web_tree_dynamic_colored_field
  setup/web_tree_dynamic_colored_field/setup.py
  web_tree_dynamic_colored_field/README.rst
  web_tree_dynamic_colored_field/__init__.py
  web_tree_dynamic_colored_field/__manifest__.py
  web_tree_dynamic_colored_field/demo/res_users.xml
  web_tree_dynamic_colored_field/i18n/es.po
  web_tree_dynamic_colored_field/i18n/fi.po
  web_tree_dynamic_colored_field/i18n/nl_NL.po
  web_tree_dynamic_colored_field/i18n/sl.po
  web_tree_dynamic_colored_field/i18n/web_tree_dynamic_colored_field.pot
  web_tree_dynamic_colored_field/i18n/zh_CN.po
  web_tree_dynamic_colored_field/readme/CONTRIBUTORS.rst
  web_tree_dynamic_colored_field/readme/CREDITS.rst
  web_tree_dynamic_colored_field/readme/DESCRIPTION.rst
  web_tree_dynamic_colored_field/readme/ROADMAP.rst
  web_tree_dynamic_colored_field/readme/USAGE.rst
  web_tree_dynamic_colored_field/static/description/icon.png
  web_tree_dynamic_colored_field/static/description/index.html
  web_tree_dynamic_colored_field/static/src/js/web_tree_dynamic_colored_field.js
  web_tree_dynamic_colored_field/views/web_tree_dynamic_colored_field.xml
Labels: approved, bot is merging ⏳, ready to merge

#1859 [14.0][MIG] web_sheet_full_width
  setup/web_sheet_full_width/odoo/addons/web_sheet_full_width
  setup/web_sheet_full_width/setup.py
  web_sheet_full_width/README.rst
  web_sheet_full_width/__init__.py
  web_sheet_full_width/__manifest__.py
  web_sheet_full_width/i18n/es.po
  web_sheet_full_width/i18n/web_sheet_full_width.pot
  web_sheet_full_width/readme/CONTRIBUTORS.rst
  web_sheet_full_width/readme/DESCRIPTION.rst
  web_sheet_full_width/static/description/icon.png
  web_sheet_full_width/static/description/index.html
  web_sheet_full_width/static/src/scss/web_sheet_full_width.scss
  web_sheet_full_width/templates/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1886 [13.0][IMP] web_widget_numeric_step: Add auto_select option
  web_widget_numeric_step/README.rst
  web_widget_numeric_step/readme/USAGE.rst
  web_widget_numeric_step/static/description/index.html
  web_widget_numeric_step/static/src/js/numeric_step.js
Labels: approved, bot is merging ⏳

#1882 [14.0][MIG] web_tree_image_tooltip
  setup/web_tree_image_tooltip/odoo/addons/web_tree_image_tooltip
  setup/web_tree_image_tooltip/setup.py
  web_tree_image_tooltip/README.rst
  web_tree_image_tooltip/__init__.py
  web_tree_image_tooltip/__manifest__.py
  web_tree_image_tooltip/i18n/web_tree_image.pot
  web_tree_image_tooltip/i18n/web_tree_image_tooltip.pot
  web_tree_image_tooltip/i18n/zh_CN.po
  web_tree_image_tooltip/readme/CONFIGURE.rst
  web_tree_image_tooltip/readme/CONTRIBUTORS.rst
  web_tree_image_tooltip/readme/CREDITS.rst
  web_tree_image_tooltip/readme/DESCRIPTION.rst
  web_tree_image_tooltip/readme/USAGE.rst
  web_tree_image_tooltip/static/description/icon.png
  web_tree_image_tooltip/static/description/index.html
  web_tree_image_tooltip/static/src/js/tooltip.js
  web_tree_image_tooltip/static/src/scss/common.scss
  web_tree_image_tooltip/view/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1780 14.0 mig web tree many2one clickable
  setup/web_tree_many2one_clickable/odoo/addons/web_tree_many2one_clickable
  setup/web_tree_many2one_clickable/setup.py
  web_tree_many2one_clickable/README.rst
  web_tree_many2one_clickable/__init__.py
  web_tree_many2one_clickable/__manifest__.py
  web_tree_many2one_clickable/i18n/web_tree_many2one_clickable.pot
  web_tree_many2one_clickable/i18n/zh_CN.po
  web_tree_many2one_clickable/readme/CONFIGURATION.rst
  web_tree_many2one_clickable/readme/CONTRIBUTORS.rst
  web_tree_many2one_clickable/readme/DESCRIPTION.rst
  web_tree_many2one_clickable/readme/ROADMAP.rst
  web_tree_many2one_clickable/readme/USAGE.rst
  web_tree_many2one_clickable/static/description/icon.png
  web_tree_many2one_clickable/static/description/index.html
  web_tree_many2one_clickable/static/img/clickable.gif
  web_tree_many2one_clickable/static/src/css/web_tree_many2one_clickable.scss
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
  web_tree_many2one_clickable/views/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1892 [14.0][MIG] web_drop_target: Migration to 14.0
  setup/web_drop_target/odoo/addons/web_drop_target
  setup/web_drop_target/setup.py
  web_drop_target/README.rst
  web_drop_target/__init__.py
  web_drop_target/__manifest__.py
  web_drop_target/i18n/es.po
  web_drop_target/i18n/fr.po
  web_drop_target/i18n/it.po
  web_drop_target/i18n/web_drop_target.pot
  web_drop_target/readme/CONTRIBUTORS.rst
  web_drop_target/readme/DESCRIPTION.rst
  web_drop_target/readme/DEVELOP.rst
  web_drop_target/readme/ROADMAP.rst
  web_drop_target/readme/USAGE.rst
  web_drop_target/static/description/icon.png
  web_drop_target/static/description/index.html
  web_drop_target/static/description/screenshot.png
  web_drop_target/static/lib/base64js.min.js
  web_drop_target/static/src/js/web_drop_target.js
  web_drop_target/static/src/scss/web_drop_target.scss
  web_drop_target/static/src/xml/widgets.xml
  web_drop_target/views/templates.xml
Labels: bot is merging ⏳

#1879 [12.0][IMP] web_widget_one2many_product_picker: User experience
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_create_form_view.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker/static/src/scss/one2many_product_picker.scss
  web_widget_one2many_product_picker/static/src/xml/one2many_product_picker.xml
Labels: approved, bot is merging ⏳, ready to merge

#1896 [12.0][FIX] web_widget_one2many_product_picker_sale_stock: Force hide popup
  web_widget_one2many_product_picker_sale_stock/README.rst
  web_widget_one2many_product_picker_sale_stock/readme/USAGE.rst
  web_widget_one2many_product_picker_sale_stock/static/description/index.html
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker_sale_stock/static/src/xml/one2many_product_picker.xml
  web_widget_one2many_product_picker_sale_stock/templates/assets.xml
Labels: approved, bot is merging ⏳

#1893 [12.0][FIX] Freeze and bump matplotlib
  requirements.txt
Labels: approved, merged 🎉, ready to merge

#1894 [13.0][FW] Freeze and bump matplotlib
  requirements.txt
Labels: bot is merging ⏳

#1898 [13.0][MIG] web_refresher: Migration to 13.0
  setup/web_refresher/odoo/addons/web_refresher
  setup/web_refresher/setup.py
  web_refresher/README.rst
  web_refresher/__init__.py
  web_refresher/__manifest__.py
  web_refresher/i18n/ca.po
  web_refresher/i18n/es.po
  web_refresher/i18n/pt_BR.po
  web_refresher/i18n/web_refresher.pot
  web_refresher/readme/CONTRIBUTORS.rst
  web_refresher/readme/DESCRIPTION.rst
  web_refresher/static/description/icon.png
  web_refresher/static/description/index.html
  web_refresher/static/description/refresh.png
  web_refresher/static/src/js/refresher.js
  web_refresher/templates/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1909 [MIG] web_advanced_search: Migration to 14.0
  setup/web_advanced_search/odoo/addons/web_advanced_search
  setup/web_advanced_search/setup.py
  web_advanced_search/README.rst
  web_advanced_search/__init__.py
  web_advanced_search/__manifest__.py
  web_advanced_search/i18n/da.po
  web_advanced_search/i18n/de.po
  web_advanced_search/i18n/es.po
  web_advanced_search/i18n/fr.po
  web_advanced_search/i18n/hr.po
  web_advanced_search/i18n/nl.po
  web_advanced_search/i18n/nl_NL.po
  web_advanced_search/i18n/pt.po
  web_advanced_search/i18n/pt_BR.po
  web_advanced_search/i18n/web_advanced_search.pot
  web_advanced_search/i18n/zh_CN.po
  web_advanced_search/readme/CONTRIBUTORS.rst
  web_advanced_search/readme/DESCRIPTION.rst
  web_advanced_search/readme/HISTORY.rst
  web_advanced_search/readme/ROADMAP.rst
  web_advanced_search/readme/USAGE.rst
  web_advanced_search/static/description/icon.png
  web_advanced_search/static/description/index.html
  web_advanced_search/static/img/debug_mode.png
  web_advanced_search/static/src/js/control_panel/advanced_filter_item.js
  web_advanced_search/static/src/js/control_panel/filter_menu.js
  web_advanced_search/static/src/js/human_domain.js
  web_advanced_search/static/src/xml/web_advanced_search.xml
  web_advanced_search/views/templates.xml
Labels: approved, bot is merging ⏳, needs review

#1905 [IMP] web_widget_bokeh_chart: Upgrade library version
  requirements.txt
  web_widget_bokeh_chart/__manifest__.py
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-1.1.0.css
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-1.1.0.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-2.3.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-api-1.1.0.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-api-2.3.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-widgets-1.1.0.css
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-widgets-1.1.0.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-widgets-2.3.1.min.js
  web_widget_bokeh_chart/static/src/scss/custom-bokeh.scss
  web_widget_bokeh_chart/views/web_widget_bokeh_chart.xml
Labels: approved, bot is merging ⏳

#1913 [FIX] web_widget_bokeh_chart: Correct bokeh library version
  web_widget_bokeh_chart/readme/INSTALL.rst
Labels: bot is merging ⏳
