Repository OCA/web, pull requests merged in 2021-07, with the labels that each got.

#1918 [13.0] web_widget_url_advanced: fix display in tree view
  web_widget_url_advanced/static/src/js/url_widget.js
Labels: approved, bot is merging ⏳, ready to merge

#1761 [13.0][IMP] web_m2x_options
  web_m2x_options/static/src/js/form.js
Labels: approved, bot is merging ⏳, ready to merge

#1779 14.0 mig web listview range select
  setup/web_listview_range_select/odoo/addons/web_listview_range_select
  setup/web_listview_range_select/setup.py
  web_listview_range_select/README.rst
  web_listview_range_select/__init__.py
  web_listview_range_select/__manifest__.py
  web_listview_range_select/i18n/es.po
  web_listview_range_select/i18n/hr.po
  web_listview_range_select/i18n/web_listview_range_select.pot
  web_listview_range_select/i18n/zh_CN.po
  web_listview_range_select/readme/CONTRIBUTORS.rst
  web_listview_range_select/readme/DESCRIPTION.rst
  web_listview_range_select/readme/ROADMAP.rst
  web_listview_range_select/readme/USAGE.rst
  web_listview_range_select/static/description/icon.png
  web_listview_range_select/static/description/index.html
  web_listview_range_select/static/src/js/web_listview_range_select.js
  web_listview_range_select/templates/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1955 [ADD] new module web_responsive_company
  web_responsive_company/README.rst
  web_responsive_company/__init__.py
  web_responsive_company/__manifest__.py
  web_responsive_company/demo/res_company.xml
  web_responsive_company/demo/res_groups.xml
  web_responsive_company/i18n/fr.po
  web_responsive_company/models/__init__.py
  web_responsive_company/models/ir_http.py
  web_responsive_company/readme/CONTRIBUTORS.rst
  web_responsive_company/readme/DESCRIPTION.rst
  web_responsive_company/readme/INSTALL.rst
  web_responsive_company/readme/ROADMAP.rst
  web_responsive_company/readme/USAGE.rst
  web_responsive_company/static/description/company_menu.png
  web_responsive_company/static/img/res_company-acsone.png
  web_responsive_company/static/img/res_company-akretion.png
  web_responsive_company/static/img/res_company-camp_to_camp.svg
  web_responsive_company/static/img/res_company-coop_it_easy.png
  web_responsive_company/static/img/res_company-grap.png
  web_responsive_company/static/img/res_company-tecnativa.svg
  web_responsive_company/static/src/js/web_responsive_company.js
  web_responsive_company/static/src/scss/web_responsive_company.scss
  web_responsive_company/static/src/xml/web_responsive_company.xml
  web_responsive_company/views/assets.xml
Labels: approved, bot is merging ⏳, needs review

#1687 [MIG] web_widget_open_tab: Migration to 13.0
  setup/web_widget_open_tab/odoo/addons/web_widget_open_tab
  setup/web_widget_open_tab/setup.py
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/demo/res_users_view.xml
  web_widget_open_tab/i18n/es.po
  web_widget_open_tab/i18n/web_widget_open_tab.pot
  web_widget_open_tab/readme/CONTRIBUTORS.rst
  web_widget_open_tab/readme/DESCRIPTION.rst
  web_widget_open_tab/readme/USAGE.rst
  web_widget_open_tab/static/description/icon.png
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/static/src/js/widget.js
  web_widget_open_tab/templates/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1975 [13.0][IMP] web_disable_export_group: export all button
  web_disable_export_group/README.rst
  web_disable_export_group/readme/CONTRIBUTORS.rst
  web_disable_export_group/readme/DESCRIPTION.rst
  web_disable_export_group/static/description/index.html
  web_disable_export_group/static/src/js/disable_export_group.js
  web_disable_export_group/static/src/js/web_disable_export_group_tour.js
Labels: approved, bot is merging ⏳

#1934 [14.0] {MIG] web_widget_dropdown_dynamic
  setup/web_widget_dropdown_dynamic/odoo/addons/web_widget_dropdown_dynamic
  setup/web_widget_dropdown_dynamic/setup.py
  web_widget_dropdown_dynamic/README.rst
  web_widget_dropdown_dynamic/__init__.py
  web_widget_dropdown_dynamic/__manifest__.py
  web_widget_dropdown_dynamic/i18n/es.po
  web_widget_dropdown_dynamic/i18n/web_widget_dropdown_dynamic.pot
  web_widget_dropdown_dynamic/readme/CONTRIBUTORS.rst
  web_widget_dropdown_dynamic/readme/DESCRIPTION.rst
  web_widget_dropdown_dynamic/readme/USAGE.rst
  web_widget_dropdown_dynamic/static/description/icon.png
  web_widget_dropdown_dynamic/static/description/index.html
  web_widget_dropdown_dynamic/static/src/js/basic_model.js
  web_widget_dropdown_dynamic/static/src/js/field_dynamic_dropdown.js
  web_widget_dropdown_dynamic/static/tests/web_widget_dropdown_dynamic_tests.js
  web_widget_dropdown_dynamic/templates/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#1956 [IMP+FIX] web_responsive : fix shortcut display and add new shortcuts (u) for the User menu
  web_responsive/readme/USAGE.rst
  web_responsive/static/src/xml/menu.xml
Labels: approved, bot is merging ⏳, ready to merge

#1967 [14.0][MIG] web_widget_url_advanced
  setup/web_widget_url_advanced/odoo/addons/web_widget_url_advanced
  setup/web_widget_url_advanced/setup.py
  web_widget_url_advanced/README.rst
  web_widget_url_advanced/__init__.py
  web_widget_url_advanced/__manifest__.py
  web_widget_url_advanced/i18n/es.po
  web_widget_url_advanced/i18n/web_widget_url_advanced.pot
  web_widget_url_advanced/i18n/zh_CN.po
  web_widget_url_advanced/readme/CONTRIBUTORS.rst
  web_widget_url_advanced/readme/DESCRIPTION.rst
  web_widget_url_advanced/readme/ROADMAP.rst
  web_widget_url_advanced/readme/USAGE.rst
  web_widget_url_advanced/static/description/after.png
  web_widget_url_advanced/static/description/before.png
  web_widget_url_advanced/static/description/icon.png
  web_widget_url_advanced/static/description/index.html
  web_widget_url_advanced/static/src/js/url_widget.js
  web_widget_url_advanced/templates/assets.xml
Labels: approved, bot is merging ⏳

#1981 [IMP] Apply copier template
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  web_dialog_size/__manifest__.py
  web_group_expand/__manifest__.py
  web_ir_actions_act_multi/__manifest__.py
  web_ir_actions_act_view_reload/__manifest__.py
  web_ir_actions_act_window_message/__manifest__.py
  web_listview_range_select/__manifest__.py
  web_pwa_oca/models/res_config_settings.py
  web_widget_dropdown_dynamic/__manifest__.py
  web_widget_dropdown_dynamic_example/__manifest__.py
  web_widget_url_advanced/__manifest__.py
Labels: bot is merging ⏳

#1982 [MIG] web_calendar_slot_duration: migration to 13.0
  setup/web_calendar_slot_duration/odoo/addons/web_calendar_slot_duration
  setup/web_calendar_slot_duration/setup.py
  web_calendar_slot_duration/README.rst
  web_calendar_slot_duration/__init__.py
  web_calendar_slot_duration/__manifest__.py
  web_calendar_slot_duration/i18n/de.po
  web_calendar_slot_duration/i18n/pt_BR.po
  web_calendar_slot_duration/i18n/web_calendar_slot_duration.pot
  web_calendar_slot_duration/readme/CONFIGURE.rst
  web_calendar_slot_duration/readme/DESCRIPTION.rst
  web_calendar_slot_duration/readme/ROADMAP.rst
  web_calendar_slot_duration/readme/USAGE.rst
  web_calendar_slot_duration/static/description/icon.png
  web_calendar_slot_duration/static/description/index.html
  web_calendar_slot_duration/static/src/js/calendar_model.js
  web_calendar_slot_duration/templates/assets.xml
Labels: approved, bot is merging ⏳, migration, needs review

#1961 [14.0] [MOD] Pass context defined on tree view field
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
Labels: bot is merging ⏳

#1875 [13.0][ADD] web_widget_one2many_product_picker_sale_secondary_unit
  oca_dependencies.txt
  setup/web_widget_one2many_product_picker_sale_secondary_unit/odoo/addons/web_widget_one2many_product_picker_sale_secondary_unit
  setup/web_widget_one2many_product_picker_sale_secondary_unit/setup.py
  web_widget_one2many_product_picker_sale_secondary_unit/README.rst
  web_widget_one2many_product_picker_sale_secondary_unit/__init__.py
  web_widget_one2many_product_picker_sale_secondary_unit/__manifest__.py
  web_widget_one2many_product_picker_sale_secondary_unit/models/__init__.py
  web_widget_one2many_product_picker_sale_secondary_unit/models/sale_order_line.py
  web_widget_one2many_product_picker_sale_secondary_unit/readme/CONTRIBUTORS.rst
  web_widget_one2many_product_picker_sale_secondary_unit/readme/DESCRIPTION.rst
  web_widget_one2many_product_picker_sale_secondary_unit/static/description/index.html
  web_widget_one2many_product_picker_sale_secondary_unit/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker_sale_secondary_unit/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker_sale_secondary_unit/static/src/js/views/abstract_view.js
  web_widget_one2many_product_picker_sale_secondary_unit/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker_sale_secondary_unit/static/src/scss/_variables.scss
  web_widget_one2many_product_picker_sale_secondary_unit/static/src/xml/one2many_product_picker.xml
  web_widget_one2many_product_picker_sale_secondary_unit/templates/assets.xml
Labels: approved, bot is merging ⏳

#1873 [13.0][MIG] web_widget_one2many_product_picker_sale_stock: Migration to 13.0
  setup/web_widget_one2many_product_picker_sale_stock/odoo/addons/web_widget_one2many_product_picker_sale_stock
  setup/web_widget_one2many_product_picker_sale_stock/setup.py
  web_widget_one2many_product_picker_sale_stock/README.rst
  web_widget_one2many_product_picker_sale_stock/__init__.py
  web_widget_one2many_product_picker_sale_stock/__manifest__.py
  web_widget_one2many_product_picker_sale_stock/i18n/web_widget_one2many_product_picker_sale_stock.pot
  web_widget_one2many_product_picker_sale_stock/readme/CONTRIBUTORS.rst
  web_widget_one2many_product_picker_sale_stock/readme/DESCRIPTION.rst
  web_widget_one2many_product_picker_sale_stock/readme/USAGE.rst
  web_widget_one2many_product_picker_sale_stock/static/description/icon.png
  web_widget_one2many_product_picker_sale_stock/static/description/index.html
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/abstract_view.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker_sale_stock/static/src/scss/one2many_product_picker.scss
  web_widget_one2many_product_picker_sale_stock/static/src/xml/one2many_product_picker.xml
  web_widget_one2many_product_picker_sale_stock/templates/assets.xml
Labels: approved, bot is merging ⏳
