Repository OCA/web, pull requests merged in 2022-03, with the labels that each got.

#2115 [15.0][MIG] web_sheet_full_width
  setup/web_sheet_full_width/odoo/addons/web_sheet_full_width
  setup/web_sheet_full_width/setup.py
  web_sheet_full_width/README.rst
  web_sheet_full_width/__init__.py
  web_sheet_full_width/__manifest__.py
  web_sheet_full_width/i18n/es.po
  web_sheet_full_width/i18n/web_sheet_full_width.pot
  web_sheet_full_width/readme/CONTRIBUTORS.rst
  web_sheet_full_width/readme/DESCRIPTION.rst
  web_sheet_full_width/static/description/icon.png
  web_sheet_full_width/static/description/index.html
  web_sheet_full_width/static/src/scss/web_sheet_full_width.scss
Labels: approved, bot is merging ⏳

#2157 [13.0][FIX] web_company_color: Recalculated color when we do not want
  web_company_color/i18n/es.po
  web_company_color/i18n/web_company_color.pot
  web_company_color/models/res_company.py
  web_company_color/readme/CONTRIBUTORS.rst
  web_company_color/tests/test_res_company.py
  web_company_color/view/res_company.xml
Labels: bot is merging ⏳

#2153 [15.0][MIG] `web_advanced_search`: Migration to 15.0
  .eslintrc.yml
  setup/web_advanced_search/odoo/addons/web_advanced_search
  setup/web_advanced_search/setup.py
  web_advanced_search/README.rst
  web_advanced_search/__init__.py
  web_advanced_search/__manifest__.py
  web_advanced_search/i18n/da.po
  web_advanced_search/i18n/de.po
  web_advanced_search/i18n/es.po
  web_advanced_search/i18n/fr.po
  web_advanced_search/i18n/hr.po
  web_advanced_search/i18n/it.po
  web_advanced_search/i18n/nl.po
  web_advanced_search/i18n/nl_NL.po
  web_advanced_search/i18n/pt.po
  web_advanced_search/i18n/pt_BR.po
  web_advanced_search/i18n/web_advanced_search.pot
  web_advanced_search/i18n/zh_CN.po
  web_advanced_search/readme/CONTRIBUTORS.rst
  web_advanced_search/readme/DESCRIPTION.rst
  web_advanced_search/readme/HISTORY.rst
  web_advanced_search/readme/ROADMAP.rst
  web_advanced_search/readme/USAGE.rst
  web_advanced_search/static/description/icon.png
  web_advanced_search/static/description/index.html
  web_advanced_search/static/img/debug_mode.png
  web_advanced_search/static/src/js/AdvancedFilterItem.esm.js
  web_advanced_search/static/src/js/CustomFilterItem.esm.js
  web_advanced_search/static/src/js/FilterMenu.esm.js
  web_advanced_search/static/src/js/RecordPicker.esm.js
  web_advanced_search/static/src/js/utils.esm.js
  web_advanced_search/static/src/xml/AdvancedFilterItem.xml
  web_advanced_search/static/src/xml/CustomFilterItem.xml
  web_advanced_search/static/src/xml/FilterMenu.xml
Labels: approved, ready to merge, bot is merging ⏳

#2117 [15.0][MIG] web_widget_url_advanced
  setup/web_widget_url_advanced/odoo/addons/web_widget_url_advanced
  setup/web_widget_url_advanced/setup.py
  web_widget_url_advanced/README.rst
  web_widget_url_advanced/__init__.py
  web_widget_url_advanced/__manifest__.py
  web_widget_url_advanced/i18n/es.po
  web_widget_url_advanced/i18n/web_widget_url_advanced.pot
  web_widget_url_advanced/i18n/zh_CN.po
  web_widget_url_advanced/readme/CONTRIBUTORS.rst
  web_widget_url_advanced/readme/DESCRIPTION.rst
  web_widget_url_advanced/readme/ROADMAP.rst
  web_widget_url_advanced/readme/USAGE.rst
  web_widget_url_advanced/static/description/after.png
  web_widget_url_advanced/static/description/before.png
  web_widget_url_advanced/static/description/icon.png
  web_widget_url_advanced/static/description/index.html
  web_widget_url_advanced/static/src/js/url_widget.js
Labels: approved, ready to merge, bot is merging ⏳

#2071 [12.0][IMP] web_widget_one2many_product_picker: Backport from 13.0
  web_widget_one2many_product_picker/README.rst
  web_widget_one2many_product_picker/__manifest__.py
  web_widget_one2many_product_picker/i18n/ca.po
  web_widget_one2many_product_picker/i18n/es.po
  web_widget_one2many_product_picker/i18n/pt_BR.po
  web_widget_one2many_product_picker/i18n/web_widget_one2many_product_picker.pot
  web_widget_one2many_product_picker/models/__init__.py
  web_widget_one2many_product_picker/models/base.py
  web_widget_one2many_product_picker/models/product_product.py
  web_widget_one2many_product_picker/readme/CONFIGURE.rst
  web_widget_one2many_product_picker/readme/ROADMAP.rst
  web_widget_one2many_product_picker/static/description/index.html
  web_widget_one2many_product_picker/static/src/js/tools.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_create_form.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_create_form_view.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_modif_price_form.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_modif_price_form_view.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker/static/src/js/views/basic_controller.js
  web_widget_one2many_product_picker/static/src/js/views/basic_model.js
  web_widget_one2many_product_picker/static/src/js/views/form_controller.js
  web_widget_one2many_product_picker/static/src/js/views/form_renderer.js
  web_widget_one2many_product_picker/static/src/js/views/form_view.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker/static/src/scss/main_variables.scss
  web_widget_one2many_product_picker/static/src/scss/one2many_product_picker.scss
  web_widget_one2many_product_picker/static/src/xml/one2many_product_picker.xml
  web_widget_one2many_product_picker/static/src/xml/one2many_product_picker_quick_create.xml
  web_widget_one2many_product_picker/static/src/xml/one2many_product_picker_quick_modif_price.xml
  web_widget_one2many_product_picker/static/tests/widget_tests.js
  web_widget_one2many_product_picker/templates/assets.xml
Labels: bot is merging ⏳

#2076 [12.0][IMP] web_widget_one2many_product_picker_sale_stock: Adapt to work with product_picker
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/views/abstract_view.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker_sale_stock/static/src/js/widgets/qty_at_date_widget.js
  web_widget_one2many_product_picker_sale_stock/static/src/scss/one2many_product_picker.scss
  web_widget_one2many_product_picker_sale_stock/static/src/xml/one2many_product_picker.xml
  web_widget_one2many_product_picker_sale_stock/templates/assets.xml
Labels: bot is merging ⏳

#2127 [14.0][MIG] web_search_with_and: Migration to 14.0
  setup/web_search_with_and/odoo/addons/web_search_with_and
  setup/web_search_with_and/setup.py
  web_search_with_and/README.rst
  web_search_with_and/__init__.py
  web_search_with_and/__manifest__.py
  web_search_with_and/i18n/es.po
  web_search_with_and/i18n/it.po
  web_search_with_and/i18n/pt.po
  web_search_with_and/i18n/web_search_with_and.pot
  web_search_with_and/readme/CONTRIBUTORS.rst
  web_search_with_and/readme/DESCRIPTION.rst
  web_search_with_and/readme/USAGE.rst
  web_search_with_and/static/description/icon.png
  web_search_with_and/static/description/index.html
  web_search_with_and/static/src/js/control_panel_model_extension.js
  web_search_with_and/static/src/js/search_bar.js
  web_search_with_and/views/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#2135 [MIG] web_domain_field: Migration to 15.0
  setup/web_domain_field/odoo/addons/web_domain_field
  setup/web_domain_field/setup.py
  web_domain_field/README.rst
  web_domain_field/__init__.py
  web_domain_field/__manifest__.py
  web_domain_field/i18n/web_domain_field.pot
  web_domain_field/readme/CONTRIBUTORS.rst
  web_domain_field/readme/DESCRIPTION.rst
  web_domain_field/readme/USAGE.rst
  web_domain_field/static/description/icon.png
  web_domain_field/static/description/index.html
  web_domain_field/static/lib/js/pyeval.js
Labels: approved, bot is merging ⏳

#2074 [13.0][IMP] web_widget_one2many_product_picker: Refactor code
  web_widget_one2many_product_picker/README.rst
  web_widget_one2many_product_picker/__init__.py
  web_widget_one2many_product_picker/i18n/es.po
  web_widget_one2many_product_picker/i18n/web_widget_one2many_product_picker.pot
  web_widget_one2many_product_picker/models/__init__.py
  web_widget_one2many_product_picker/models/base.py
  web_widget_one2many_product_picker/readme/CONFIGURE.rst
  web_widget_one2many_product_picker/readme/CONTRIBUTORS.rst
  web_widget_one2many_product_picker/readme/ROADMAP.rst
  web_widget_one2many_product_picker/static/description/index.html
  web_widget_one2many_product_picker/static/src/js/tools.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_create_form.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_create_form_view.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_modif_price_form.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/quick_modif_price_form_view.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/record.js
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker/static/src/js/views/basic_controller.js
  web_widget_one2many_product_picker/static/src/js/views/basic_model.js
  web_widget_one2many_product_picker/static/src/js/views/form_controller.js
  web_widget_one2many_product_picker/static/src/js/views/form_renderer.js
  web_widget_one2many_product_picker/static/src/js/views/form_view.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
  web_widget_one2many_product_picker/static/src/scss/one2many_product_picker.scss
  web_widget_one2many_product_picker/static/src/xml/one2many_product_picker.xml
  web_widget_one2many_product_picker/static/src/xml/one2many_product_picker_quick_create.xml
  web_widget_one2many_product_picker/templates/assets.xml
Labels: bot is merging ⏳

#2177 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  web_access_rule_buttons/models/models.py
  web_company_color/models/assetsbundle.py
  web_company_color/models/ir_qweb.py
Labels: help wanted, needs review

#2178 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: help wanted, needs review
