Repository OCA/web, pull requests merged in 2022-10, with the labels that each got.

#2272 [15.0][MIG] web_ir_actions_act_view_reload
  setup/web_ir_actions_act_view_reload/odoo/addons/web_ir_actions_act_view_reload
  setup/web_ir_actions_act_view_reload/setup.py
  web_ir_actions_act_view_reload/README.rst
  web_ir_actions_act_view_reload/__init__.py
  web_ir_actions_act_view_reload/__manifest__.py
  web_ir_actions_act_view_reload/i18n/web_ir_actions_act_view_reload.pot
  web_ir_actions_act_view_reload/i18n/zh_CN.po
  web_ir_actions_act_view_reload/models/__init__.py
  web_ir_actions_act_view_reload/models/ir_actions_act_view_reload.py
  web_ir_actions_act_view_reload/readme/CONTRIBUTORS.rst
  web_ir_actions_act_view_reload/readme/DESCRIPTION.rst
  web_ir_actions_act_view_reload/readme/USAGE.rst
  web_ir_actions_act_view_reload/static/description/icon.png
  web_ir_actions_act_view_reload/static/description/index.html
  web_ir_actions_act_view_reload/static/src/js/web_ir_actions_act_view_reload.esm.js
Labels: approved, bot is merging ⏳

#2209 [14.0][IMP] web_company_color: Forward port #1903 from 12.0
  web_company_color/models/res_company.py
  web_company_color/view/res_company.xml
Labels: approved, ready to merge, bot is merging ⏳

#2251 [15.0][MIG] web_calendar_slot_duration: Migration to 15.0
  setup/web_calendar_slot_duration/odoo/addons/web_calendar_slot_duration
  setup/web_calendar_slot_duration/setup.py
  web_calendar_slot_duration/README.rst
  web_calendar_slot_duration/__init__.py
  web_calendar_slot_duration/__manifest__.py
  web_calendar_slot_duration/i18n/de.po
  web_calendar_slot_duration/i18n/pt_BR.po
  web_calendar_slot_duration/i18n/web_calendar_slot_duration.pot
  web_calendar_slot_duration/readme/CONFIGURE.rst
  web_calendar_slot_duration/readme/DESCRIPTION.rst
  web_calendar_slot_duration/readme/ROADMAP.rst
  web_calendar_slot_duration/readme/USAGE.rst
  web_calendar_slot_duration/static/description/icon.png
  web_calendar_slot_duration/static/description/index.html
  web_calendar_slot_duration/static/src/js/calendar_model.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2311 [16.0] [MIG] web_environment_ribbon
  setup/web_environment_ribbon/odoo/addons/web_environment_ribbon
  setup/web_environment_ribbon/setup.py
  web_environment_ribbon/README.rst
  web_environment_ribbon/__init__.py
  web_environment_ribbon/__manifest__.py
  web_environment_ribbon/data/ribbon_data.xml
  web_environment_ribbon/i18n/ca.po
  web_environment_ribbon/i18n/de.po
  web_environment_ribbon/i18n/es.po
  web_environment_ribbon/i18n/fr.po
  web_environment_ribbon/i18n/hr.po
  web_environment_ribbon/i18n/nl.po
  web_environment_ribbon/i18n/nl_NL.po
  web_environment_ribbon/i18n/pt.po
  web_environment_ribbon/i18n/pt_BR.po
  web_environment_ribbon/i18n/sl.po
  web_environment_ribbon/i18n/web_environment_ribbon.pot
  web_environment_ribbon/i18n/zh_CN.po
  web_environment_ribbon/models/__init__.py
  web_environment_ribbon/models/web_environment_ribbon_backend.py
  web_environment_ribbon/readme/CONFIGURE.rst
  web_environment_ribbon/readme/CONTRIBUTORS.rst
  web_environment_ribbon/readme/DESCRIPTION.rst
  web_environment_ribbon/readme/USAGE.rst
  web_environment_ribbon/static/description/icon.png
  web_environment_ribbon/static/description/index.html
  web_environment_ribbon/static/description/screenshot.png
  web_environment_ribbon/static/src/css/ribbon.css
  web_environment_ribbon/static/src/js/ribbon.js
  web_environment_ribbon/tests/__init__.py
  web_environment_ribbon/tests/test_environment_ribbon_data.py
Labels: approved, ready to merge, bot is merging ⏳

#1942 [14.0][FIX] web_widget_x2many_2d_matrix - show_column_totals and show_row_totals
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
Labels: approved, ready to merge, bot is merging ⏳

#2145 [MIG] web_tree_dynamic_colored_field: Migration to 15.0
  setup/web_tree_dynamic_colored_field/odoo/addons/web_tree_dynamic_colored_field
  setup/web_tree_dynamic_colored_field/setup.py
  web_tree_dynamic_colored_field/README.rst
  web_tree_dynamic_colored_field/__init__.py
  web_tree_dynamic_colored_field/__manifest__.py
  web_tree_dynamic_colored_field/demo/res_users.xml
  web_tree_dynamic_colored_field/i18n/es.po
  web_tree_dynamic_colored_field/i18n/fi.po
  web_tree_dynamic_colored_field/i18n/nl_NL.po
  web_tree_dynamic_colored_field/i18n/sl.po
  web_tree_dynamic_colored_field/i18n/web_tree_dynamic_colored_field.pot
  web_tree_dynamic_colored_field/i18n/zh_CN.po
  web_tree_dynamic_colored_field/readme/CONTRIBUTORS.rst
  web_tree_dynamic_colored_field/readme/CREDITS.rst
  web_tree_dynamic_colored_field/readme/DESCRIPTION.rst
  web_tree_dynamic_colored_field/readme/ROADMAP.rst
  web_tree_dynamic_colored_field/readme/USAGE.rst
  web_tree_dynamic_colored_field/static/description/icon.png
  web_tree_dynamic_colored_field/static/description/index.html
  web_tree_dynamic_colored_field/static/src/js/web_tree_dynamic_colored_field.js
Labels: bot is merging ⏳

#2323 [14.0][MIG] web_widget_image_webcam
  setup/web_widget_image_webcam/odoo/addons/web_widget_image_webcam
  setup/web_widget_image_webcam/setup.py
  web_widget_image_webcam/README.rst
  web_widget_image_webcam/__init__.py
  web_widget_image_webcam/__manifest__.py
  web_widget_image_webcam/i18n/es.po
  web_widget_image_webcam/i18n/web_widget_image_webcam.pot
  web_widget_image_webcam/models/__init__.py
  web_widget_image_webcam/models/ir_config_parameter.py
  web_widget_image_webcam/readme/CONFIGURE.rst
  web_widget_image_webcam/readme/CONTRIBUTORS.rst
  web_widget_image_webcam/readme/DESCRIPTION.rst
  web_widget_image_webcam/static/description/icon.png
  web_widget_image_webcam/static/description/index.html
  web_widget_image_webcam/static/src/css/web_widget_image_webcam.css
  web_widget_image_webcam/static/src/img/webcam_placeholder.png
  web_widget_image_webcam/static/src/js/webcam_widget.js
  web_widget_image_webcam/static/src/lib/webcam.js
  web_widget_image_webcam/static/src/lib/webcam.swf
  web_widget_image_webcam/static/src/xml/web_widget_image_webcam.xml
  web_widget_image_webcam/views/assets.xml
Labels: approved, bot is merging ⏳

#2255 [14.0][IMP] web_refresher: Work as component of control panel
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/readme/CONTRIBUTORS.rst
  web_refresher/static/description/index.html
  web_refresher/static/src/js/refresher.js
  web_refresher/static/src/scss/refresher.scss
  web_refresher/static/src/xml/refresher.xml
  web_refresher/templates/assets.xml
  web_refresher/templates/pager_button.xml
Labels: approved, bot is merging ⏳

#2313 [15.0] [IMP] `web_domain_field`: Add unit tests
  web_domain_field/__manifest__.py
  web_domain_field/static/tests/test_qunit.js
  web_domain_field/tests/__init__.py
  web_domain_field/tests/test_qunit.py
Labels: bot is merging ⏳

#2322 [14.0][IMP] web_domain_field: Promote to Production/Stable
  web_domain_field/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#2324 [12.0][FIX] web_disable_browser_autocomplete: Qweb include path
  web_disable_browser_autocomplete/__manifest__.py
Labels: bot is merging ⏳

#2293 [15.0][FIX] web_timeline: utc, create and update
  web_timeline/static/src/js/timeline_controller.js
Labels: approved, ready to merge, bot is merging ⏳
