Repository OCA/web, pull requests merged in 2022-01, with the labels that each got.

#2111 [14.0][FW] web_m2x_options: multiple ports from 12.0, 13.0
  web_m2x_options/README.rst
  web_m2x_options/models/ir_config_parameter.py
  web_m2x_options/readme/CONTRIBUTORS.rst
  web_m2x_options/readme/USAGE.rst
  web_m2x_options/static/src/js/form.js
  web_m2x_options/static/src/js/ir_options.js
  web_m2x_options/static/src/xml/base.xml
  web_m2x_options/tests/test_ir_config_parameter.py
  web_m2x_options/views/view.xml
Labels: bot is merging ⏳

#2107 [15.0][MIG] web_widget_bokeh_chart
  requirements.txt
  setup/web_widget_bokeh_chart/odoo/addons/web_widget_bokeh_chart
  setup/web_widget_bokeh_chart/setup.py
  web_environment_ribbon/static/src/js/ribbon.js
  web_m2x_options/static/src/js/form.js
  web_widget_bokeh_chart/README.rst
  web_widget_bokeh_chart/__init__.py
  web_widget_bokeh_chart/__manifest__.py
  web_widget_bokeh_chart/i18n/web_widget_bokeh_chart.pot
  web_widget_bokeh_chart/i18n/zh_CN.po
  web_widget_bokeh_chart/readme/CONTRIBUTORS.rst
  web_widget_bokeh_chart/readme/CREDITS.rst
  web_widget_bokeh_chart/readme/DESCRIPTION.rst
  web_widget_bokeh_chart/readme/INSTALL.rst
  web_widget_bokeh_chart/readme/USAGE.rst
  web_widget_bokeh_chart/static/description/example.png
  web_widget_bokeh_chart/static/description/icon.png
  web_widget_bokeh_chart/static/description/index.html
  web_widget_bokeh_chart/static/src/js/web_widget_bokeh_chart.esm.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-2.4.2.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-api-2.4.2.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-gl-2.4.2.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-mathjax-2.4.2.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-tables-2.4.2.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-widgets-2.4.2.min.js
Labels: approved, bot is merging ⏳

#2122 [MIG] web_pwa_oca: Migration to 14.0
  setup/web_pwa_oca/odoo/addons/web_pwa_oca
  setup/web_pwa_oca/setup.py
  web_pwa_oca/README.rst
  web_pwa_oca/__init__.py
  web_pwa_oca/__manifest__.py
  web_pwa_oca/controllers/__init__.py
  web_pwa_oca/controllers/main.py
  web_pwa_oca/controllers/service_worker.py
  web_pwa_oca/i18n/es.po
  web_pwa_oca/i18n/es_AR.po
  web_pwa_oca/i18n/pt_BR.po
  web_pwa_oca/i18n/web_pwa_oca.pot
  web_pwa_oca/models/__init__.py
  web_pwa_oca/models/res_config_settings.py
  web_pwa_oca/readme/CONFIGURE.rst
  web_pwa_oca/readme/CONTRIBUTORS.rst
  web_pwa_oca/readme/DESCRIPTION.rst
  web_pwa_oca/readme/INSTALL.rst
  web_pwa_oca/readme/ROADMAP.rst
  web_pwa_oca/readme/USAGE.rst
  web_pwa_oca/static/description/icon.png
  web_pwa_oca/static/description/index.html
  web_pwa_oca/static/description/pwa.png
  web_pwa_oca/static/img/icons/icon-128x128.png
  web_pwa_oca/static/img/icons/icon-144x144.png
  web_pwa_oca/static/img/icons/icon-152x152.png
  web_pwa_oca/static/img/icons/icon-192x192.png
  web_pwa_oca/static/img/icons/icon-256x256.png
  web_pwa_oca/static/img/icons/icon-512x512.png
  web_pwa_oca/static/img/icons/odoo_logo.svg
  web_pwa_oca/static/src/js/pwa_manager.js
  web_pwa_oca/static/src/js/webclient.js
  web_pwa_oca/static/src/js/worker/jquery-sw-compat.js
  web_pwa_oca/static/src/js/worker/pwa.js
  web_pwa_oca/templates/assets.xml
  web_pwa_oca/tests/__init__.py
  web_pwa_oca/tests/test_web_pwa_oca_controller.py
  web_pwa_oca/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2125 web_notify: bump dev status
  web_notify/__manifest__.py
Labels: bot is merging ⏳

#2126 [13.0] web_notify: bump dev status
  web_notify/__manifest__.py
Labels: bot is merging ⏳

#2118 [MIG] web_ir_actions_act_multi: Migration to 15.0
  setup/web_ir_actions_act_multi/odoo/addons/web_ir_actions_act_multi
  setup/web_ir_actions_act_multi/setup.py
  web_ir_actions_act_multi/README.rst
  web_ir_actions_act_multi/__init__.py
  web_ir_actions_act_multi/__manifest__.py
  web_ir_actions_act_multi/i18n/es.po
  web_ir_actions_act_multi/i18n/web_ir_actions_act_multi.pot
  web_ir_actions_act_multi/i18n/zh_CN.po
  web_ir_actions_act_multi/models/__init__.py
  web_ir_actions_act_multi/models/ir_actions.py
  web_ir_actions_act_multi/readme/CONTRIBUTORS.rst
  web_ir_actions_act_multi/readme/DESCRIPTION.rst
  web_ir_actions_act_multi/readme/USAGE.rst
  web_ir_actions_act_multi/security/ir.model.access.csv
  web_ir_actions_act_multi/static/description/icon.png
  web_ir_actions_act_multi/static/description/index.html
  web_ir_actions_act_multi/static/src/js/web_ir_actions_act_multi.esm.js
Labels: approved, bot is merging ⏳

#2132 [14.0][FIX] web_widget_ckeditor
  web_widget_ckeditor/static/src/js/field_ckeditor.js
  web_widget_ckeditor/static/src/scss/web_widget_ckeditor.scss
Labels: bot is merging ⏳

#2066 [14.0] [IMP] web_drop_target
  web_drop_target/README.rst
  web_drop_target/readme/CONTRIBUTORS.rst
  web_drop_target/static/description/index.html
  web_drop_target/static/src/js/web_drop_target.js
  web_drop_target/static/src/scss/web_drop_target.scss
  web_drop_target/static/src/xml/widgets.xml
Labels: bot is merging ⏳

#2090 [FIX] web_drop_target: Hide it when it is not the current action or has no chatter
  web_drop_target/static/src/js/web_drop_target.js
Labels: approved, bot is merging ⏳

#2098 [IMP/FIX] web_widget_domain_editor_dialog: work in dialog
  web_widget_domain_editor_dialog/static/src/js/basic_fields.js
  web_widget_domain_editor_dialog/static/src/js/widget_domain_editor_dialog.js
Labels: approved, ready to merge, bot is merging ⏳
