Repository OCA/web, pull requests merged in 2022-04, with the labels that each got.

#2103 [15.0][MIG] web_widget_dropdown_dynamic: Migration to 15.0
  setup/web_widget_dropdown_dynamic/odoo/addons/web_widget_dropdown_dynamic
  setup/web_widget_dropdown_dynamic/setup.py
  web_widget_dropdown_dynamic/README.rst
  web_widget_dropdown_dynamic/__init__.py
  web_widget_dropdown_dynamic/__manifest__.py
  web_widget_dropdown_dynamic/i18n/de.po
  web_widget_dropdown_dynamic/i18n/es.po
  web_widget_dropdown_dynamic/i18n/web_widget_dropdown_dynamic.pot
  web_widget_dropdown_dynamic/readme/CONTRIBUTORS.rst
  web_widget_dropdown_dynamic/readme/DESCRIPTION.rst
  web_widget_dropdown_dynamic/readme/USAGE.rst
  web_widget_dropdown_dynamic/static/description/icon.png
  web_widget_dropdown_dynamic/static/description/index.html
  web_widget_dropdown_dynamic/static/src/js/basic_model.js
  web_widget_dropdown_dynamic/static/src/js/field_dynamic_dropdown.js
  web_widget_dropdown_dynamic/static/tests/web_widget_dropdown_dynamic_tests.js
Labels: approved, bot is merging ⏳

#2190 [13.0][IMP] web_widget_one2many_tree_line_duplicate: Clone all fields
  web_widget_one2many_tree_line_duplicate/static/src/js/basic_model.js
  web_widget_one2many_tree_line_duplicate/static/src/js/one2many_tree_line_duplicate.js
Labels: bot is merging ⏳

#2199 [13.0]Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: approved

#2141 [15.0] [MIG] web_action_conditionable
  setup/web_action_conditionable/odoo/addons/web_action_conditionable
  setup/web_action_conditionable/setup.py
  web_action_conditionable/README.rst
  web_action_conditionable/__init__.py
  web_action_conditionable/__manifest__.py
  web_action_conditionable/i18n/es.po
  web_action_conditionable/i18n/hr.po
  web_action_conditionable/i18n/web_action_conditionable.pot
  web_action_conditionable/i18n/zh_CN.po
  web_action_conditionable/readme/CONTRIBUTORS.rst
  web_action_conditionable/readme/DESCRIPTION.rst
  web_action_conditionable/readme/USAGE.rst
  web_action_conditionable/static/description/icon.png
  web_action_conditionable/static/description/index.html
  web_action_conditionable/static/src/js/field_one2many.js
Labels: approved, ready to merge, bot is merging ⏳

#2187 [DOC] web_widget_bokeh_chart
  web_widget_bokeh_chart/readme/USAGE.rst
Labels: approved, ready to merge, bot is merging ⏳

#2201 [LIC] web_drop_target: Relicense to LGPL
  web_drop_target/README.rst
  web_drop_target/__init__.py
  web_drop_target/__manifest__.py
  web_drop_target/static/description/index.html
  web_drop_target/static/src/js/web_drop_target.js
Labels: approved, bot is merging ⏳

#2203 [12.0][FIX] web_timeline correct readme
  web_timeline/readme/CONFIGURE.rst
Labels: bot is merging ⏳

#2202 [LIC] web_drop_target: Relicense to LGPL
  web_drop_target/README.rst
  web_drop_target/__init__.py
  web_drop_target/__manifest__.py
  web_drop_target/static/src/js/web_drop_target.js
Labels: bot is merging ⏳

#2204 [15.0][MIG]web_widget_image_download
  setup/web_widget_image_download/odoo/addons/web_widget_image_download
  setup/web_widget_image_download/setup.py
  web_widget_image_download/README.rst
  web_widget_image_download/__init__.py
  web_widget_image_download/__manifest__.py
  web_widget_image_download/i18n/es.po
  web_widget_image_download/i18n/hr.po
  web_widget_image_download/i18n/it.po
  web_widget_image_download/i18n/lt.po
  web_widget_image_download/i18n/nl_NL.po
  web_widget_image_download/i18n/pt.po
  web_widget_image_download/i18n/web_widget_image_download.pot
  web_widget_image_download/i18n/zh_CN.po
  web_widget_image_download/readme/CONTRIBUTORS.rst
  web_widget_image_download/readme/DESCRIPTION.rst
  web_widget_image_download/readme/USAGE.rst
  web_widget_image_download/static/description/icon.png
  web_widget_image_download/static/description/index.html
  web_widget_image_download/static/src/js/web_widget_image_download.js
  web_widget_image_download/static/src/scss/web_widget_image_download.scss
  web_widget_image_download/static/src/xml/web_widget_image_download.xml
Labels: approved, bot is merging ⏳
