Repository OCA/web, pull requests merged in 2022-02, with the labels that each got.

#2129 [15.0][MIG] web_widget_domain_editor_dialog
  setup/web_widget_domain_editor_dialog/odoo/addons/web_widget_domain_editor_dialog
  setup/web_widget_domain_editor_dialog/setup.py
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/__init__.py
  web_widget_domain_editor_dialog/__manifest__.py
  web_widget_domain_editor_dialog/i18n/es.po
  web_widget_domain_editor_dialog/i18n/web_widget_domain_editor_dialog.pot
  web_widget_domain_editor_dialog/i18n/zh_CN.po
  web_widget_domain_editor_dialog/readme/CONTRIBUTORS.rst
  web_widget_domain_editor_dialog/readme/DESCRIPTION.rst
  web_widget_domain_editor_dialog/readme/USAGE.rst
  web_widget_domain_editor_dialog/static/description/icon.png
  web_widget_domain_editor_dialog/static/description/index.html
  web_widget_domain_editor_dialog/static/src/img/behaviour.gif
  web_widget_domain_editor_dialog/static/src/js/basic_fields.js
  web_widget_domain_editor_dialog/static/src/js/widget_domain_editor_dialog.js
Labels: bot is merging ⏳

#2142 [14.0][FIX] web_widget_ckeditor: `ir.config_paramter` permissions and typo
  web_widget_ckeditor/__init__.py
  web_widget_ckeditor/models/__init__.py
  web_widget_ckeditor/models/ir_config_parameter.py
  web_widget_ckeditor/static/src/js/field_ckeditor.js
Labels: bot is merging ⏳

#2021 [12.0][FIX] web_export_view: Remove newlines from fields having many2many_tags
  web_export_view/static/src/js/web_export_view.js
  web_export_view/static/tests/web_export_view_tests.js
  web_export_view/views/web_export_view_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2150 [15.0][UPD] web_widget_x2many_2d_matrix dev status to Production/stable
  web_widget_x2many_2d_matrix/__manifest__.py
Labels: approved, bot is merging ⏳

#2152 [14.0] [FIX] Fields with complex context
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
Labels: approved, bot is merging ⏳

#2134 [12.0][FIX] web_edit_user_filter: Use filter label when no value is set
  web_edit_user_filter/static/src/js/backend.js
  web_edit_user_filter/static/src/xml/backend.xml
Labels: bot is merging ⏳

#2097 [15.0][MIG] web_no_bubble: Migration to 15.0
  setup/web_no_bubble/odoo/addons/web_no_bubble
  setup/web_no_bubble/setup.py
  web_no_bubble/README.rst
  web_no_bubble/__init__.py
  web_no_bubble/__manifest__.py
  web_no_bubble/i18n/es.po
  web_no_bubble/i18n/fr_FR.po
  web_no_bubble/i18n/hr.po
  web_no_bubble/i18n/web_no_bubble.pot
  web_no_bubble/i18n/zh_CN.po
  web_no_bubble/readme/CONTRIBUTORS.rst
  web_no_bubble/readme/DESCRIPTION.rst
  web_no_bubble/static/description/icon.png
  web_no_bubble/static/description/index.html
  web_no_bubble/static/src/css/web_no_bubble.scss
Labels: approved, bot is merging ⏳

#1822 [13.0][ADD] Boolean Button Ported from 12 to 13
  web_boolean_button/README.rst
  web_boolean_button/__init__.py
  web_boolean_button/__manifest__.py
  web_boolean_button/readme/CONTRIBUTORS.rst
  web_boolean_button/readme/DESCRIPTION.rst
  web_boolean_button/readme/ROADMAP.rst
  web_boolean_button/readme/USAGE.rst
  web_boolean_button/static/description/index.html
  web_boolean_button/static/src/js/basic_fields.js
  web_boolean_button/static/tests/form_tests.js
  web_boolean_button/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳
