Repository OCA/web, pull requests merged in 2022-05, with the labels that each got.

#2156 [MIG] web_widget_open_tab: Migration to 15.0
  setup/web_widget_open_tab/odoo/addons/web_widget_open_tab
  setup/web_widget_open_tab/setup.py
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/demo/res_users_view.xml
  web_widget_open_tab/i18n/ca.po
  web_widget_open_tab/i18n/de.po
  web_widget_open_tab/i18n/es.po
  web_widget_open_tab/i18n/pt_BR.po
  web_widget_open_tab/i18n/web_widget_open_tab.pot
  web_widget_open_tab/readme/CONTRIBUTORS.rst
  web_widget_open_tab/readme/DESCRIPTION.rst
  web_widget_open_tab/readme/USAGE.rst
  web_widget_open_tab/static/description/icon.png
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/static/src/js/widget.js
Labels: approved, ready to merge, bot is merging ⏳

#2185 [13.0][FIX] web_widget_one2many_product_picker: auto save timer
  web_widget_one2many_product_picker/models/base.py
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
Labels: bot is merging ⏳

#2210 [13.0][FIX] web_dialog_size: resize columns from one2many tree
  web_dialog_size/static/src/js/web_dialog_size.js
Labels: approved, bot is merging ⏳

#2213 [13.0][FIX] web_dialog_size: special dialogs
  web_dialog_size/static/src/js/web_dialog_size.js
Labels: approved, bot is merging ⏳

#2139 [15.0] [MIG] web_drop_target
  setup/web_drop_target/odoo/addons/web_drop_target
  setup/web_drop_target/setup.py
  web_drop_target/README.rst
  web_drop_target/__init__.py
  web_drop_target/__manifest__.py
  web_drop_target/i18n/de.po
  web_drop_target/i18n/es.po
  web_drop_target/i18n/fr.po
  web_drop_target/i18n/it.po
  web_drop_target/i18n/nl.po
  web_drop_target/i18n/web_drop_target.pot
  web_drop_target/readme/CONTRIBUTORS.rst
  web_drop_target/readme/DESCRIPTION.rst
  web_drop_target/readme/DEVELOP.rst
  web_drop_target/readme/ROADMAP.rst
  web_drop_target/readme/USAGE.rst
  web_drop_target/static/description/icon.png
  web_drop_target/static/description/index.html
  web_drop_target/static/description/screenshot.png
  web_drop_target/static/lib/base64js.min.js
  web_drop_target/static/src/js/web_drop_target.js
  web_drop_target/static/src/scss/web_drop_target.scss
  web_drop_target/static/src/xml/widgets.xml
Labels: approved, bot is merging ⏳

#2221 [LIC] web_drop_target: Relicense to LGPL
  web_drop_target/README.rst
  web_drop_target/__init__.py
  web_drop_target/__manifest__.py
  web_drop_target/static/src/js/web_drop_target.js
Labels: bot is merging ⏳

#2222 [MIG] web_widget_json_graph: Migration to 15.0
  setup/web_widget_json_graph/odoo/addons/web_widget_json_graph
  setup/web_widget_json_graph/setup.py
  web_widget_json_graph/README.rst
  web_widget_json_graph/__init__.py
  web_widget_json_graph/__manifest__.py
  web_widget_json_graph/readme/CONTRIBUTORS.rst
  web_widget_json_graph/readme/CREDITS.rst
  web_widget_json_graph/readme/DESCRIPTION.rst
  web_widget_json_graph/readme/ROADMAP.rst
  web_widget_json_graph/readme/USAGE.rst
  web_widget_json_graph/static/description/icon.png
  web_widget_json_graph/static/description/index.html
  web_widget_json_graph/static/description/widget_in_action.png
  web_widget_json_graph/static/src/js/web_widget_json_graph.js
  web_widget_json_graph/static/src/xml/web_widget_json_graph.xml
Labels: approved, bot is merging ⏳

#2173 [MIG][15.0] web_search_with_and: Migration to 15.0
  setup/web_search_with_and/odoo/addons/web_search_with_and
  setup/web_search_with_and/setup.py
  web_search_with_and/README.rst
  web_search_with_and/__init__.py
  web_search_with_and/__manifest__.py
  web_search_with_and/i18n/es.po
  web_search_with_and/i18n/it.po
  web_search_with_and/i18n/pt.po
  web_search_with_and/i18n/web_search_with_and.pot
  web_search_with_and/readme/CONTRIBUTORS.rst
  web_search_with_and/readme/DESCRIPTION.rst
  web_search_with_and/readme/USAGE.rst
  web_search_with_and/static/description/icon.png
  web_search_with_and/static/description/index.html
  web_search_with_and/static/src/js/control_panel_model_extension.js
  web_search_with_and/static/src/js/search_bar.js
Labels: approved, bot is merging ⏳

#2109 [15.0][MIG] web_widget_numeric_step: Migration to 15.0
  setup/web_widget_numeric_step/odoo/addons/web_widget_numeric_step
  setup/web_widget_numeric_step/setup.py
  web_widget_numeric_step/README.rst
  web_widget_numeric_step/__init__.py
  web_widget_numeric_step/__manifest__.py
  web_widget_numeric_step/demo/res_users_view.xml
  web_widget_numeric_step/i18n/de.po
  web_widget_numeric_step/i18n/es.po
  web_widget_numeric_step/i18n/fr.po
  web_widget_numeric_step/i18n/it.po
  web_widget_numeric_step/i18n/web_widget_numeric_step.pot
  web_widget_numeric_step/readme/CONTRIBUTORS.rst
  web_widget_numeric_step/readme/DESCRIPTION.rst
  web_widget_numeric_step/readme/USAGE.rst
  web_widget_numeric_step/static/description/add_two_buttons.png
  web_widget_numeric_step/static/description/icon.png
  web_widget_numeric_step/static/description/index.html
  web_widget_numeric_step/static/description/step0,25andlimits.gif
  web_widget_numeric_step/static/description/step10_limit15_placeholder117_with_onchange.gif
  web_widget_numeric_step/static/src/css/numeric_step.scss
  web_widget_numeric_step/static/src/js/numeric_step.js
  web_widget_numeric_step/static/src/xml/numeric_step.xml
Labels: approved, bot is merging ⏳

#2136 [13.0][MIG] web_widget_text_markdown: Migration to 13.0
  setup/web_widget_text_markdown/odoo/addons/web_widget_text_markdown
  setup/web_widget_text_markdown/setup.py
  web_widget_text_markdown/README.rst
  web_widget_text_markdown/__init__.py
  web_widget_text_markdown/__manifest__.py
  web_widget_text_markdown/demo/bootstrap_markdown.xml
  web_widget_text_markdown/i18n/ar.po
  web_widget_text_markdown/i18n/de.po
  web_widget_text_markdown/i18n/es.po
  web_widget_text_markdown/i18n/fi.po
  web_widget_text_markdown/i18n/fr.po
  web_widget_text_markdown/i18n/pt_BR.po
  web_widget_text_markdown/i18n/sl.po
  web_widget_text_markdown/i18n/tr.po
  web_widget_text_markdown/i18n/web_widget_text_markdown.pot
  web_widget_text_markdown/readme/CONTRIBUTORS.rst
  web_widget_text_markdown/readme/CREDITS.rst
  web_widget_text_markdown/readme/DESCRIPTION.rst
  web_widget_text_markdown/readme/ROADMAP.rst
  web_widget_text_markdown/readme/USAGE.rst
  web_widget_text_markdown/static/description/icon.png
  web_widget_text_markdown/static/description/index.html
  web_widget_text_markdown/static/src/js/web_widget_text_markdown.js
  web_widget_text_markdown/static/src/lib/bootstrap-markdown.js
  web_widget_text_markdown/static/src/lib/bootstrap-markdown.min.css
  web_widget_text_markdown/static/src/lib/dropzone.js
  web_widget_text_markdown/static/src/lib/marked.js
  web_widget_text_markdown/static/src/scss/web_widget_text_markdown.scss
  web_widget_text_markdown/static/tests/js/web_widget_text_markdown.js
  web_widget_text_markdown/views/assets.xml
Labels: bot is merging ⏳
