Repository OCA/web, pull requests merged in 2022-06, with the labels that each got.

#2220 [15.0][FIX] web_responsive kanban mode for popup in Many2One fields on mobile
  web_responsive/static/src/legacy/js/web_responsive.js
  web_responsive/static/src/legacy/scss/kanban_view_mobile.scss
Labels: approved, ready to merge, bot is merging ⏳

#2229 [14.0][IMP] web_responsive: Add chatter position view_users_form
  web_responsive/views/res_users.xml
Labels: bot is merging ⏳

#2180 [15.0][MIG] web_listview_range_select: Migration to 15.0
  setup/web_listview_range_select/odoo/addons/web_listview_range_select
  setup/web_listview_range_select/setup.py
  web_listview_range_select/README.rst
  web_listview_range_select/__init__.py
  web_listview_range_select/__manifest__.py
  web_listview_range_select/i18n/es.po
  web_listview_range_select/i18n/hr.po
  web_listview_range_select/i18n/web_listview_range_select.pot
  web_listview_range_select/i18n/zh_CN.po
  web_listview_range_select/readme/CONTRIBUTORS.rst
  web_listview_range_select/readme/DESCRIPTION.rst
  web_listview_range_select/readme/ROADMAP.rst
  web_listview_range_select/readme/USAGE.rst
  web_listview_range_select/static/description/icon.png
  web_listview_range_select/static/description/index.html
  web_listview_range_select/static/src/js/web_listview_range_select.js
Labels: approved, ready to merge, bot is merging ⏳

#2232 [15.0][FIX]-web_responsive module: Go to wrong action menu when access from Root Screen Search Bar when user is set with Home Action Menu
  web_responsive/static/src/components/apps_menu/apps_menu.xml
Labels: approved, bot is merging ⏳

#2235 [13.0][FIX] web_view_calendar_list fix viewType
  web_view_calendar_list/static/src/js/calendar_list_view.js
Labels: bot is merging ⏳

#2216 [MIG] web_widget_child_selector: Migration to 15.0
  setup/web_widget_child_selector/odoo/addons/web_widget_child_selector
  setup/web_widget_child_selector/setup.py
  web_widget_child_selector/README.rst
  web_widget_child_selector/__init__.py
  web_widget_child_selector/__manifest__.py
  web_widget_child_selector/i18n/pt_BR.po
  web_widget_child_selector/i18n/web_widget_child_selector.pot
  web_widget_child_selector/models/__init__.py
  web_widget_child_selector/models/base.py
  web_widget_child_selector/readme/CONTRIBUTORS.rst
  web_widget_child_selector/readme/DESCRIPTION.rst
  web_widget_child_selector/readme/USAGE.rst
  web_widget_child_selector/static/description/edit_mode.png
  web_widget_child_selector/static/description/icon.png
  web_widget_child_selector/static/description/index.html
  web_widget_child_selector/static/src/js/widget_child_selector.js
  web_widget_child_selector/static/src/scss/widget_child_selector.scss
  web_widget_child_selector/static/src/xml/widget_child_selector.xml
  web_widget_child_selector/tests/__init__.py
  web_widget_child_selector/tests/test_widget_child_selector.py
Labels: approved, ready to merge, bot is merging ⏳
