Repository OCA/web, pull requests merged in 2022-12, with the labels that each got.

#2351 [16.0][ADD] Module web_dark_mode
  setup/web_dark_mode/odoo/addons/web_dark_mode
  setup/web_dark_mode/setup.py
  web_dark_mode/README.rst
  web_dark_mode/__init__.py
  web_dark_mode/__manifest__.py
  web_dark_mode/models/__init__.py
  web_dark_mode/models/ir_http.py
  web_dark_mode/models/res_users.py
  web_dark_mode/readme/CONTRIBUTORS.rst
  web_dark_mode/readme/DESCRIPTION.rst
  web_dark_mode/readme/ROADMAP.rst
  web_dark_mode/static/description/index.html
  web_dark_mode/static/src/js/switch_item.esm.js
  web_dark_mode/static/src/scss/variables.scss
  web_dark_mode/tests/__init__.py
  web_dark_mode/tests/test_dark_mode.py
  web_dark_mode/views/res_users_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2356 [MIG] web_domain_field: Migration to 16.0
  setup/web_domain_field/odoo/addons/web_domain_field
  setup/web_domain_field/setup.py
  web_domain_field/README.rst
  web_domain_field/__init__.py
  web_domain_field/__manifest__.py
  web_domain_field/i18n/web_domain_field.pot
  web_domain_field/readme/CONTRIBUTORS.rst
  web_domain_field/readme/DESCRIPTION.rst
  web_domain_field/readme/USAGE.rst
  web_domain_field/static/description/icon.png
  web_domain_field/static/description/index.html
  web_domain_field/static/lib/js/pyeval.js
  web_domain_field/static/tests/test_qunit.js
  web_domain_field/tests/__init__.py
  web_domain_field/tests/test_qunit.py
Labels: approved, bot is merging ⏳

#2366 [16.0] [IMP] web_refresher: Add component to pager to avoid instance for all views
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/readme/CONTRIBUTORS.rst
  web_refresher/static/description/index.html
  web_refresher/static/src/js/pager.esm.js
  web_refresher/static/src/js/refresher.esm.js
  web_refresher/static/src/scss/refresher.scss
  web_refresher/static/src/xml/pager.xml
  web_refresher/static/src/xml/pager_button.xml
  web_refresher/static/src/xml/refresher.xml
Labels: approved, bot is merging ⏳

#2365 [15.0][IMP] web_refresher: Work as component of control panel
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/readme/CONTRIBUTORS.rst
  web_refresher/static/description/index.html
  web_refresher/static/src/js/control_panel.esm.js
  web_refresher/static/src/js/refresher.esm.js
  web_refresher/static/src/scss/refresher.scss
  web_refresher/static/src/xml/control_panel.xml
  web_refresher/static/src/xml/pager_button.xml
  web_refresher/static/src/xml/refresher.xml
Labels: approved, bot is merging ⏳

#2371 [14.0][FIX] web_responsive: slashes in app names
  web_responsive/static/src/js/web_responsive.js
Labels: bot is merging ⏳
