Repository OCA/web, pull requests merged in 2022-09, with the labels that each got.

#2286 [11.0] [Fix] Error with Chrome 105
  web_export_view/static/src/js/web_export_view.js
Labels: approved, bot is merging ⏳

#2292 [15.0][FIX] web_advanced_search: Prevent error in many2one fields
  web_advanced_search/static/src/js/legacy/CustomFilterItem.esm.js
  web_advanced_search/static/src/js/owl/CustomFilterItem.esm.js
Labels: approved, bot is merging ⏳

#2164 [FIX] web_widget_x2many_2d_matrix: make the possibility to have alternative values for headers
  web_widget_x2many_2d_matrix/static/src/js/2d_matrix_renderer.js
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
  web_widget_x2many_2d_matrix_example/models/__init__.py
  web_widget_x2many_2d_matrix_example/models/res_users.py
  web_widget_x2many_2d_matrix_example/models/x2m_demo.py
  web_widget_x2many_2d_matrix_example/wizard/x2m_matrix.py
  web_widget_x2many_2d_matrix_example/wizard/x2m_matrix.xml
Labels: approved, bot is merging ⏳

#2297 [FIX] web_responsive : apply same z-index value for the menu as odoo CE
  web_responsive/static/src/css/web_responsive.scss
Labels: approved, bot is merging ⏳

#2305 [13.0][IMP] web_refresher: Remove refresh button from x2Many fields.
  web_refresher/README.rst
  web_refresher/readme/CONTRIBUTORS.rst
  web_refresher/static/description/index.html
  web_refresher/static/src/js/refresher.js
  web_refresher/static/src/xml/refresher.xml
Labels: approved, bot is merging ⏳

#2301 [15.0][FIX] web_responsive: fix keyboard navigation in Apps menu Search results
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
  web_responsive/static/src/components/apps_menu/apps_menu.xml
Labels: bot is merging ⏳

#2299 [14.0][FIX] web_drop_target: check controller is not null
  web_drop_target/static/src/js/web_drop_target.js
Labels: approved, ready to merge, bot is merging ⏳
