Repository OCA/web, pull requests merged in 2022-08, with the labels that each got.

#2256 [13.0][FIX] web_timeline: Don't crash when restoring timeline from breadcrumb
  web_timeline/static/src/js/timeline_controller.js
Labels: approved, ready to merge, bot is merging ⏳

#2268 [14.0][FIX] web_timeline: order group_by field (and update JS lib)
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.css
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js
  web_timeline/static/src/js/timeline_controller.js
  web_timeline/static/src/js/timeline_model.js
  web_timeline/static/src/js/timeline_renderer.js
  web_timeline/static/src/js/timeline_view.js
Labels: approved, bot is merging ⏳

#2247 [15.0][MIG] web_timeline: Migration to 15.0
  setup/web_timeline/odoo/addons/web_timeline
  setup/web_timeline/setup.py
  web_timeline/README.rst
  web_timeline/__init__.py
  web_timeline/__manifest__.py
  web_timeline/i18n/de.po
  web_timeline/i18n/es.po
  web_timeline/i18n/fa.po
  web_timeline/i18n/fr.po
  web_timeline/i18n/he.po
  web_timeline/i18n/hr.po
  web_timeline/i18n/nl_NL.po
  web_timeline/i18n/pt.po
  web_timeline/i18n/pt_BR.po
  web_timeline/i18n/web_timeline.pot
  web_timeline/i18n/zh_CN.po
  web_timeline/models/__init__.py
  web_timeline/models/ir_ui_view.py
  web_timeline/readme/CONFIGURE.rst
  web_timeline/readme/CONTRIBUTORS.rst
  web_timeline/readme/DESCRIPTION.rst
  web_timeline/readme/ROADMAP.rst
  web_timeline/readme/USAGE.rst
  web_timeline/static/description/icon.png
  web_timeline/static/description/index.html
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.css
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js
  web_timeline/static/src/js/timeline_canvas.js
  web_timeline/static/src/js/timeline_controller.js
  web_timeline/static/src/js/timeline_model.js
  web_timeline/static/src/js/timeline_renderer.js
  web_timeline/static/src/js/timeline_view.js
  web_timeline/static/src/scss/web_timeline.scss
  web_timeline/static/src/xml/web_timeline.xml
Labels: bot is merging ⏳

#2265 [14.0] web_widget_child_selector: try to fix image display in README
  web_widget_child_selector/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#2267 [13.0][FIX] web_widget_one2many_tree_line_duplicate: clone wisely
  web_widget_one2many_tree_line_duplicate/static/src/js/basic_model.js
Labels: bot is merging ⏳

#2163 [IMP] web_tree_image_tooltip : add the possibility to define an alternative image field
  web_tree_image_tooltip/__manifest__.py
  web_tree_image_tooltip/demo/view_res_users.xml
  web_tree_image_tooltip/readme/CONFIGURE.rst
  web_tree_image_tooltip/readme/CONTRIBUTORS.rst
  web_tree_image_tooltip/readme/DESCRIPTION.rst
  web_tree_image_tooltip/readme/USAGE.rst
  web_tree_image_tooltip/static/description/tree_view_image.png
  web_tree_image_tooltip/static/description/tree_view_image_tooltip.png
  web_tree_image_tooltip/static/src/js/tooltip.js
Labels: approved, ready to merge, bot is merging ⏳

#2271 [13.0][ADD] web_confirm_duplicate
  setup/web_confirm_duplicate/odoo/addons/web_confirm_duplicate
  setup/web_confirm_duplicate/setup.py
  web_confirm_duplicate/README.rst
  web_confirm_duplicate/__init__.py
  web_confirm_duplicate/__manifest__.py
  web_confirm_duplicate/readme/CONTRIBUTORS.rst
  web_confirm_duplicate/readme/DESCRIPTION.rst
  web_confirm_duplicate/readme/USAGE.rst
  web_confirm_duplicate/static/description/icon.png
  web_confirm_duplicate/static/description/index.html
  web_confirm_duplicate/static/src/js/basic_view.js
  web_confirm_duplicate/static/src/js/form_controller.js
  web_confirm_duplicate/templates/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#2259 [15.0] [MIG] web_ir_actions_act_window_message
  setup/web_ir_actions_act_window_message/odoo/addons/web_ir_actions_act_window_message
  setup/web_ir_actions_act_window_message/setup.py
  web_ir_actions_act_window_message/README.rst
  web_ir_actions_act_window_message/__init__.py
  web_ir_actions_act_window_message/__manifest__.py
  web_ir_actions_act_window_message/i18n/ar.po
  web_ir_actions_act_window_message/i18n/de.po
  web_ir_actions_act_window_message/i18n/es.po
  web_ir_actions_act_window_message/i18n/eu.po
  web_ir_actions_act_window_message/i18n/fi.po
  web_ir_actions_act_window_message/i18n/fr.po
  web_ir_actions_act_window_message/i18n/hr.po
  web_ir_actions_act_window_message/i18n/it.po
  web_ir_actions_act_window_message/i18n/nl.po
  web_ir_actions_act_window_message/i18n/nl_NL.po
  web_ir_actions_act_window_message/i18n/pt.po
  web_ir_actions_act_window_message/i18n/pt_BR.po
  web_ir_actions_act_window_message/i18n/ro.po
  web_ir_actions_act_window_message/i18n/sl.po
  web_ir_actions_act_window_message/i18n/tr.po
  web_ir_actions_act_window_message/i18n/web_ir_actions_act_window_message.pot
  web_ir_actions_act_window_message/models/__init__.py
  web_ir_actions_act_window_message/models/ir_actions.py
  web_ir_actions_act_window_message/readme/CONTRIBUTORS.rst
  web_ir_actions_act_window_message/readme/DESCRIPTION.rst
  web_ir_actions_act_window_message/readme/ROADMAP.rst
  web_ir_actions_act_window_message/readme/USAGE.rst
  web_ir_actions_act_window_message/security/ir.model.access.csv
  web_ir_actions_act_window_message/static/description/icon.png
  web_ir_actions_act_window_message/static/description/index.html
  web_ir_actions_act_window_message/static/src/js/web_ir_actions_act_window_message.esm.js
  web_ir_actions_act_window_message/static/src/xml/web_ir_actions_act_window_message.xml
Labels: approved, ready to merge, bot is merging ⏳

#2276 [15.0][ADD] web_tree_column_width_remember: Remember the tree view columns
  setup/web_remember_tree_column_width/odoo/addons/web_remember_tree_column_width
  setup/web_remember_tree_column_width/setup.py
  web_remember_tree_column_width/README.rst
  web_remember_tree_column_width/__init__.py
  web_remember_tree_column_width/__manifest__.py
  web_remember_tree_column_width/readme/CONTRIBUTORS.rst
  web_remember_tree_column_width/readme/CREDITS.rst
  web_remember_tree_column_width/readme/DESCRIPTION.rst
  web_remember_tree_column_width/static/description/index.html
  web_remember_tree_column_width/static/src/js/list_renderer.js
  web_remember_tree_column_width/static/src/scss/main.scss
Labels: approved, ready to merge, bot is merging ⏳

#1979 [14.0][mig] web_widget_text_markdown
  setup/web_widget_text_markdown/odoo/addons/web_widget_text_markdown
  setup/web_widget_text_markdown/setup.py
  web_widget_text_markdown/README.rst
  web_widget_text_markdown/__init__.py
  web_widget_text_markdown/__manifest__.py
  web_widget_text_markdown/demo/bootstrap_markdown.xml
  web_widget_text_markdown/readme/CONTRIBUTORS.rst
  web_widget_text_markdown/readme/CREDITS.rst
  web_widget_text_markdown/readme/DESCRIPTION.rst
  web_widget_text_markdown/readme/ROADMAP.rst
  web_widget_text_markdown/readme/USAGE.rst
  web_widget_text_markdown/static/description/icon.png
  web_widget_text_markdown/static/description/index.html
  web_widget_text_markdown/static/src/css/web_widget_text_markdown.css
  web_widget_text_markdown/static/src/js/web_widget_text_markdown.js
  web_widget_text_markdown/static/src/lib/bootstrap-markdown.js
  web_widget_text_markdown/static/src/lib/bootstrap-markdown.min.css
  web_widget_text_markdown/static/src/lib/marked.js
  web_widget_text_markdown/static/src/lib/showdown-footnotes.js
  web_widget_text_markdown/static/src/lib/showdown-table.js
  web_widget_text_markdown/static/src/lib/showdown-toc.js
  web_widget_text_markdown/static/src/lib/showdown.js
  web_widget_text_markdown/static/tests/js/web_widget_text_markdown.js
  web_widget_text_markdown/views/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#2281 [15.0][FIX] web_remember_tree_column_width: use correct module name
  web_remember_tree_column_width/__manifest__.py
  web_remember_tree_column_width/static/src/js/list_renderer.js
Labels: approved, bot is merging ⏳

#2254 [ADD] web_button_no_save
  setup/web_button_no_save/odoo/addons/web_button_no_save
  setup/web_button_no_save/setup.py
  web_button_no_save/README.rst
  web_button_no_save/__init__.py
  web_button_no_save/__manifest__.py
  web_button_no_save/readme/CONFIGURE.rst
  web_button_no_save/readme/CONTRIBUTORS.rst
  web_button_no_save/readme/DESCRIPTION.rst
  web_button_no_save/readme/ROADMAP.rst
  web_button_no_save/static/description/index.html
  web_button_no_save/static/src/js/web_button_no_save.js
  web_button_no_save/templates/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#2172 [15.0][MIG] web_dialog_size: migration
  setup/web_dialog_size/odoo/addons/web_dialog_size
  setup/web_dialog_size/setup.py
  web_dialog_size/README.rst
  web_dialog_size/__init__.py
  web_dialog_size/__manifest__.py
  web_dialog_size/i18n/de.po
  web_dialog_size/i18n/es.po
  web_dialog_size/i18n/fr.po
  web_dialog_size/i18n/it.po
  web_dialog_size/i18n/nl.po
  web_dialog_size/i18n/web_dialog_size.pot
  web_dialog_size/i18n/zh_CN.po
  web_dialog_size/models/__init__.py
  web_dialog_size/models/ir_config_parameter.py
  web_dialog_size/readme/CONFIGURATION.rst
  web_dialog_size/readme/CONFIGURE.rst
  web_dialog_size/readme/CONTRIBUTORS.rst
  web_dialog_size/readme/DESCRIPTION.rst
  web_dialog_size/readme/ROADMAP.rst
  web_dialog_size/static/description/icon.png
  web_dialog_size/static/description/index.html
  web_dialog_size/static/src/js/web_dialog_draggable.esm.js
  web_dialog_size/static/src/js/web_dialog_size.esm.js
  web_dialog_size/static/src/js/web_dialog_size.js
  web_dialog_size/static/src/scss/web_dialog_size.scss
  web_dialog_size/static/src/xml/DialogDraggable.xml
  web_dialog_size/static/src/xml/ExpandButton.xml
  web_dialog_size/static/src/xml/web_dialog_size.xml
  web_dialog_size/tests/__init__.py
  web_dialog_size/tests/test_web_dialog_size.py
Labels: approved, bot is merging ⏳

#1976 [14.0] [MIG] support_branding
  setup/support_branding/odoo/addons/support_branding
  setup/support_branding/setup.py
  support_branding/README.rst
  support_branding/__init__.py
  support_branding/__manifest__.py
  support_branding/demo/ir_config_parameter_data.xml
  support_branding/i18n/nl.po
  support_branding/i18n/sl.po
  support_branding/i18n/support_branding.pot
  support_branding/models/__init__.py
  support_branding/models/res_config_settings.py
  support_branding/readme/CONTRIBUTORS.rst
  support_branding/readme/DESCRIPTION.rst
  support_branding/static/description/icon.png
  support_branding/static/description/index.html
  support_branding/static/src/css/support_branding.css
  support_branding/static/src/js/res_config_edition.js
  support_branding/static/src/js/support_branding.js
  support_branding/static/src/js/user_menu.js
  support_branding/static/src/tests/support_branding_tests.js
  support_branding/static/src/xml/base.xml
  support_branding/views/asset.xml
  support_branding/views/res_config_settings.xml
  web_advanced_search/static/src/js/relational.js
  web_calendar_color_field/static/src/js/calendar.js
  web_calendar_slot_duration/static/src/js/calendar_model.js
  web_drop_target/static/src/js/web_drop_target.js
  web_m2x_options/static/src/js/form.js
  web_pwa_oca/static/src/js/pwa_manager.js
  web_responsive/static/src/js/kanban_renderer_mobile.js
  web_responsive/static/src/js/web_responsive.js
  web_search_with_and/static/src/js/control_panel_model_extension.js
  web_search_with_and/static/src/js/search_bar.js
  web_switch_context_warning/static/src/js/switch_context_warning_worker.js
  web_widget_numeric_step/static/src/js/numeric_step.js
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
Labels: approved, ready to merge, bot is merging ⏳
