Repository OCA/web, pull requests merged in 2023-12, with the labels that each got.

#2691 [IMP] web_widget_numeric_step: display always on mobile
  web_widget_numeric_step/static/src/js/numeric_step.esm.js
  web_widget_numeric_step/static/src/xml/numeric_step.xml
Labels: enhancement, approved, bot is merging ⏳

#2692 [FIX] web_widget_numeric_step: disable buttons on readonly fields
  web_widget_numeric_step/static/src/xml/numeric_step.xml
Labels: bug, approved, bot is merging ⏳

#2689 [IMP] web_field_required_invisible_manager: consider rel. fields with own views
  web_field_required_invisible_manager/models/custom_field_restriction.py
  web_field_required_invisible_manager/models/models.py
  web_field_required_invisible_manager/tests/test_web_field_required_invisible_manager.py
Labels: approved, bot is merging ⏳

#2694 [FIX] web_widget_numeric_step: always display on touch screens; avoid layout jumping otherwise
  web_widget_numeric_step/README.rst
  web_widget_numeric_step/__manifest__.py
  web_widget_numeric_step/static/description/index.html
  web_widget_numeric_step/static/src/numeric_step.esm.js
  web_widget_numeric_step/static/src/numeric_step.scss
  web_widget_numeric_step/static/src/numeric_step.xml
Labels: bug, approved, bot is merging ⏳

#2696 [BUILD] web_responsive: resign as maintainer
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/static/description/index.html
Labels: bot is merging ⏳

#2699 [14.0][IMP] web_field_required_invisible_manager: added menus
  web_field_required_invisible_manager/models/custom_field_restriction.py
  web_field_required_invisible_manager/tests/test_web_field_required_invisible_manager.py
  web_field_required_invisible_manager/views/views.xml
Labels: bot is merging ⏳

#2700 [FIX] web_widget_numeric_step: no input focus on touch screens
  web_widget_numeric_step/static/src/numeric_step.esm.js
Labels: bug, approved, bot is merging ⏳

#2701 [ADD] web_touchscreen: enable kanban sub-form views for tablets
  setup/web_touchscreen/odoo/addons/web_touchscreen
  setup/web_touchscreen/setup.py
  web_touchscreen/README.rst
  web_touchscreen/__init__.py
  web_touchscreen/__manifest__.py
  web_touchscreen/readme/CONTEXT.md
  web_touchscreen/readme/CONTRIBUTORS.md
  web_touchscreen/readme/CREDITS.md
  web_touchscreen/readme/DESCRIPTION.md
  web_touchscreen/readme/ROADMAP.md
  web_touchscreen/readme/USAGE.md
  web_touchscreen/static/description/icon.png
  web_touchscreen/static/description/index.html
  web_touchscreen/static/src/form_controller.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#1514 [FIX] if nocreate=1 then also see that as true
  web_m2x_options/static/src/js/form.js
Labels: needs fixing, approved, ready to merge
