Repository OCA/web, pull requests merged in 2023-08, with the labels that each got.

#2548 [16.0][MIG] web_ir_actions_act_window_page
  setup/web_ir_actions_act_window_page/odoo/addons/web_ir_actions_act_window_page
  setup/web_ir_actions_act_window_page/setup.py
  web_ir_actions_act_window_page/README.rst
  web_ir_actions_act_window_page/__init__.py
  web_ir_actions_act_window_page/__manifest__.py
  web_ir_actions_act_window_page/demo/demo_action.xml
  web_ir_actions_act_window_page/i18n/de.po
  web_ir_actions_act_window_page/i18n/web_ir_actions_act_window_page.pot
  web_ir_actions_act_window_page/models/__init__.py
  web_ir_actions_act_window_page/models/ir_actions_act_window_page.py
  web_ir_actions_act_window_page/readme/CONTRIBUTORS.rst
  web_ir_actions_act_window_page/readme/DESCRIPTION.rst
  web_ir_actions_act_window_page/readme/USAGE.rst
  web_ir_actions_act_window_page/static/description/icon.png
  web_ir_actions_act_window_page/static/description/index.html
  web_ir_actions_act_window_page/static/src/web_ir_actions_act_window_page.esm.js
Labels: approved, bot is merging ⏳

#2536 [UPD] web_dialog_size: reduce rpc call to get config
  web_dialog_size/models/__init__.py
  web_dialog_size/models/ir_http.py
  web_dialog_size/static/src/js/web_dialog_draggable.esm.js
  web_dialog_size/static/src/js/web_dialog_size.esm.js
  web_dialog_size/static/src/js/web_dialog_size.js
Labels: approved

#2582 [IMP] web_field_required_invisible_manager: get restrictions fields d…
  web_field_required_invisible_manager/models/models.py
  web_field_required_invisible_manager/tests/test_web_field_required_invisible_manager.py
Labels: bot is merging ⏳

#2583 [ADD] web_field_numeric_formatting
  setup/web_field_numeric_formatting/odoo/addons/web_field_numeric_formatting
  setup/web_field_numeric_formatting/setup.py
  web_field_numeric_formatting/README.rst
  web_field_numeric_formatting/__init__.py
  web_field_numeric_formatting/__manifest__.py
  web_field_numeric_formatting/readme/CONTRIBUTORS.rst
  web_field_numeric_formatting/readme/DESCRIPTION.rst
  web_field_numeric_formatting/static/description/index.html
  web_field_numeric_formatting/static/src/components/float_field.esm.js
  web_field_numeric_formatting/static/src/components/integer_field.esm.js
  web_field_numeric_formatting/static/src/components/list_renderer.esm.js
  web_field_numeric_formatting/static/tests/field_tests.esm.js
Labels: approved, bot is merging ⏳

#2594 [ADD] web_save_discard_button module
  setup/web_save_discard_button/odoo/addons/web_save_discard_button
  setup/web_save_discard_button/setup.py
  web_save_discard_button/README.md
  web_save_discard_button/__init__.py
  web_save_discard_button/__manifest__.py
  web_save_discard_button/i18n/fr.po
  web_save_discard_button/models/__init__.py
  web_save_discard_button/models/ir_http.py
  web_save_discard_button/readme/CONTRIBUTORS.rst
  web_save_discard_button/readme/DESCRIPTION.rst
  web_save_discard_button/static/description/icon.png
  web_save_discard_button/static/description/save_button.png
  web_save_discard_button/static/src/scss/indicator_button.scss
  web_save_discard_button/static/src/xml/template.xml
Labels: bot is merging ⏳

#2571 [16.0] [FIX] web_chatter_position: fixes JS assuming "o_form_sheet_bg" is always found
  web_chatter_position/static/src/js/web_chatter_position.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2328 [MIG] web_ir_actions_act_multi: Migration to 16.0
  setup/web_ir_actions_act_multi/odoo/addons/web_ir_actions_act_multi
  setup/web_ir_actions_act_multi/setup.py
  web_ir_actions_act_multi/README.rst
  web_ir_actions_act_multi/__init__.py
  web_ir_actions_act_multi/__manifest__.py
  web_ir_actions_act_multi/i18n/es.po
  web_ir_actions_act_multi/i18n/web_ir_actions_act_multi.pot
  web_ir_actions_act_multi/i18n/zh_CN.po
  web_ir_actions_act_multi/models/__init__.py
  web_ir_actions_act_multi/models/ir_actions.py
  web_ir_actions_act_multi/readme/CONTRIBUTORS.rst
  web_ir_actions_act_multi/readme/DESCRIPTION.rst
  web_ir_actions_act_multi/readme/USAGE.rst
  web_ir_actions_act_multi/security/ir.model.access.csv
  web_ir_actions_act_multi/static/description/icon.png
  web_ir_actions_act_multi/static/description/index.html
  web_ir_actions_act_multi/static/src/js/web_ir_actions_act_multi.esm.js
Labels: approved, bot is merging ⏳
