Repository OCA/web, pull requests merged in 2023-02, with the labels that each got.

#2401 [FIX] web_responsive: Selection of menu fails
  web_responsive/static/src/js/web_responsive.js
Labels: bot is merging ⏳

#2403 [16.0][FIX] Fix problem when uninstalling web_dark_mode
  web_dark_mode/models/ir_http.py
Labels: bot is merging ⏳

#2382 [ADD] web_notify_channel_message
  setup/web_notify_channel_message/odoo/addons/web_notify_channel_message
  setup/web_notify_channel_message/setup.py
  web_notify_channel_message/README.rst
  web_notify_channel_message/__init__.py
  web_notify_channel_message/__manifest__.py
  web_notify_channel_message/models/__init__.py
  web_notify_channel_message/models/mail_channel.py
  web_notify_channel_message/readme/CONTRIBUTORS.rst
  web_notify_channel_message/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#2411 [15.0][FIX] Fix problem of blank page when using web_responsive
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
  web_responsive/static/src/components/apps_menu/apps_menu.scss
Labels: approved, bot is merging ⏳

#2327 [16.0] [MIG] web_sheet_full_width
  setup/web_sheet_full_width/odoo/addons/web_sheet_full_width
  setup/web_sheet_full_width/setup.py
  web_sheet_full_width/README.rst
  web_sheet_full_width/__init__.py
  web_sheet_full_width/__manifest__.py
  web_sheet_full_width/i18n/es.po
  web_sheet_full_width/i18n/web_sheet_full_width.pot
  web_sheet_full_width/readme/CONTRIBUTORS.rst
  web_sheet_full_width/readme/DESCRIPTION.rst
  web_sheet_full_width/static/description/icon.png
  web_sheet_full_width/static/description/index.html
  web_sheet_full_width/static/src/scss/web_sheet_full_width.scss
Labels: bot is merging ⏳

#2414 [14.0][IMP] web_ir_actions_act_view_reload: add missing model
  web_ir_actions_act_view_reload/__init__.py
  web_ir_actions_act_view_reload/models/__init__.py
  web_ir_actions_act_view_reload/models/ir_actions_act_view_reload.py
Labels: approved, bot is merging ⏳

#2408 [ADD] web_select_all_companies
  setup/web_select_all_companies/odoo/addons/web_select_all_companies
  setup/web_select_all_companies/setup.py
  web_select_all_companies/README.rst
  web_select_all_companies/__init__.py
  web_select_all_companies/__manifest__.py
  web_select_all_companies/i18n/fr.pot
  web_select_all_companies/i18n/web_select_all_companies.pot
  web_select_all_companies/readme/CONTRIBUTORS.rst
  web_select_all_companies/readme/DESCRIPTION.rst
  web_select_all_companies/static/description/index.html
  web_select_all_companies/static/description/select_all_companies.gif
  web_select_all_companies/static/src/js/switch_all_company_menu.esm.js
  web_select_all_companies/static/src/scss/switch_all_company_menu.scss
  web_select_all_companies/static/src/xml/switch_all_company_menu.xml
Labels: approved, ready to merge, bot is merging ⏳
