Repository OCA/web, pull requests merged in 2023-06, with the labels that each got.

#2525 [16.0][FIX] web_timeline: css and styles not charged when rendering t…
  web_timeline/static/src/js/timeline_renderer.js
Labels: approved, bot is merging ⏳

#2428 [16.0][MIG] web_widget_plotly_chart
  requirements.txt
  setup/web_widget_plotly_chart/odoo/addons/web_widget_plotly_chart
  setup/web_widget_plotly_chart/setup.py
  web_widget_plotly_chart/README.rst
  web_widget_plotly_chart/__init__.py
  web_widget_plotly_chart/__manifest__.py
  web_widget_plotly_chart/i18n/ca.po
  web_widget_plotly_chart/i18n/da.po
  web_widget_plotly_chart/i18n/es.po
  web_widget_plotly_chart/i18n/pt_BR.po
  web_widget_plotly_chart/i18n/web_widget_plotly_chart.pot
  web_widget_plotly_chart/readme/CONTRIBUTORS.rst
  web_widget_plotly_chart/readme/CREDITS.rst
  web_widget_plotly_chart/readme/DESCRIPTION.rst
  web_widget_plotly_chart/readme/INSTALL.rst
  web_widget_plotly_chart/readme/USAGE.rst
  web_widget_plotly_chart/static/description/example.png
  web_widget_plotly_chart/static/description/icon.png
  web_widget_plotly_chart/static/description/index.html
  web_widget_plotly_chart/static/src/js/widget_plotly.esm.js
  web_widget_plotly_chart/static/src/js/widget_plotly.xml
  web_widget_plotly_chart/static/src/lib/plotly/plotly-2.18.2.min.js
Labels: approved, ready to merge, bot is merging ⏳

#2463 [16.0][MIG] web_widget_x2many_2d_matrix
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.xml
Labels: approved, ready to merge, merged 🎉, bot is merging ⏳

#2527 [16.0][MIG] web_company_color
  setup/web_company_color/odoo/addons/web_company_color
  setup/web_company_color/setup.py
  web_company_color/README.rst
  web_company_color/__init__.py
  web_company_color/__manifest__.py
  web_company_color/hooks.py
  web_company_color/i18n/ca.po
  web_company_color/i18n/de.po
  web_company_color/i18n/es.po
  web_company_color/i18n/hr.po
  web_company_color/i18n/it.po
  web_company_color/i18n/nl.po
  web_company_color/i18n/web_company_color.pot
  web_company_color/i18n/zh_CN.po
  web_company_color/models/__init__.py
  web_company_color/models/assetsbundle.py
  web_company_color/models/ir_qweb.py
  web_company_color/models/res_company.py
  web_company_color/readme/CONTRIBUTORS.rst
  web_company_color/readme/DESCRIPTION.rst
  web_company_color/readme/ROADMAP.rst
  web_company_color/readme/USAGE.rst
  web_company_color/static/description/icon.png
  web_company_color/static/description/index.html
  web_company_color/tests/__init__.py
  web_company_color/tests/test_res_company.py
  web_company_color/utils.py
  web_company_color/view/assets.xml
  web_company_color/view/res_company.xml
Labels: approved, bot is merging ⏳

#2530 [16.0][FIX] web_company_color: unaligned button view
  web_company_color/README.rst
  web_company_color/readme/CONTRIBUTORS.rst
  web_company_color/view/res_company.xml
Labels: approved, bot is merging ⏳

#2526 [16.0][MIG] web_widget_bokeh_chart: Migration to 16.0
  requirements.txt
  setup/web_widget_bokeh_chart/odoo/addons/web_widget_bokeh_chart
  setup/web_widget_bokeh_chart/setup.py
  web_widget_bokeh_chart/README.rst
  web_widget_bokeh_chart/__init__.py
  web_widget_bokeh_chart/__manifest__.py
  web_widget_bokeh_chart/i18n/web_widget_bokeh_chart.pot
  web_widget_bokeh_chart/i18n/zh_CN.po
  web_widget_bokeh_chart/readme/CONTRIBUTORS.rst
  web_widget_bokeh_chart/readme/CREDITS.rst
  web_widget_bokeh_chart/readme/DESCRIPTION.rst
  web_widget_bokeh_chart/readme/INSTALL.rst
  web_widget_bokeh_chart/readme/USAGE.rst
  web_widget_bokeh_chart/static/description/example.png
  web_widget_bokeh_chart/static/description/icon.png
  web_widget_bokeh_chart/static/description/index.html
  web_widget_bokeh_chart/static/src/js/web_widget_bokeh_chart.esm.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-3.1.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-api-3.1.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-gl-3.1.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-mathjax-3.1.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-tables-3.1.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-widgets-3.1.1.min.js
  web_widget_bokeh_chart/static/src/xml/bokeh.xml
Labels: approved, bot is merging ⏳

#2531 [14.0] web_search_and - Make functional again
  web_search_with_and/static/src/js/control_panel_model_extension.js
Labels: approved, bot is merging ⏳

#2533 [FIX] web_select_all_companies: Title and french translation
  web_select_all_companies/i18n/fr.po
  web_select_all_companies/i18n/web_select_all_companies.pot
  web_select_all_companies/static/src/xml/switch_all_company_menu.xml
Labels: approved, ready to merge, bot is merging ⏳

#2452 [14.0][MIG] web_remember_tree_column_width: backport from 15.0
  setup/web_remember_tree_column_width/odoo/addons/web_remember_tree_column_width
  setup/web_remember_tree_column_width/setup.py
  web_remember_tree_column_width/README.rst
  web_remember_tree_column_width/__init__.py
  web_remember_tree_column_width/__manifest__.py
  web_remember_tree_column_width/i18n/web_remember_tree_column_width.pot
  web_remember_tree_column_width/readme/CONTRIBUTORS.rst
  web_remember_tree_column_width/readme/CREDITS.rst
  web_remember_tree_column_width/readme/DESCRIPTION.rst
  web_remember_tree_column_width/static/description/icon.png
  web_remember_tree_column_width/static/description/index.html
  web_remember_tree_column_width/static/src/js/list_renderer.js
  web_remember_tree_column_width/static/src/scss/main.scss
  web_remember_tree_column_width/views/assets.xml
Labels: approved, ready to merge, bot is merging ⏳

#2502 [ADD] web_field_required_invisible_manager
  setup/web_field_required_invisible_manager/odoo/addons/web_field_required_invisible_manager
  setup/web_field_required_invisible_manager/setup.py
  web_field_required_invisible_manager/README.rst
  web_field_required_invisible_manager/__init__.py
  web_field_required_invisible_manager/__manifest__.py
  web_field_required_invisible_manager/models/__init__.py
  web_field_required_invisible_manager/models/custom_field_restriction.py
  web_field_required_invisible_manager/models/models.py
  web_field_required_invisible_manager/readme/CONTRIBUTORS.rst
  web_field_required_invisible_manager/readme/DESCRIPTION.rst
  web_field_required_invisible_manager/readme/USAGE.rst
  web_field_required_invisible_manager/security/ir.model.access.csv
  web_field_required_invisible_manager/tests/__init__.py
  web_field_required_invisible_manager/tests/test_web_field_required_invisible_manager.py
  web_field_required_invisible_manager/views/views.xml
Labels: approved, bot is merging ⏳

#2541 [15.0][FIX] web_responsive: attachment_viewer is displayed under clock of employees view
  web_responsive/static/src/components/attachment_viewer/attachment_viewer.scss
Labels: approved, bot is merging ⏳
