Repository OCA/web, pull requests merged in 2023-04, with the labels that each got.

#2473 [16.0][web_responsive] [FIX] Split button templates to show translated labels
  web_responsive/static/src/legacy/xml/form_buttons.xml
Labels: approved, bot is merging ⏳

#2446 [16.0][MIG] web_m2x_options: Migration to 16.0
  setup/web_m2x_options/odoo/addons/web_m2x_options
  setup/web_m2x_options/setup.py
  web_m2x_options/README.rst
  web_m2x_options/__init__.py
  web_m2x_options/__manifest__.py
  web_m2x_options/i18n/ar.po
  web_m2x_options/i18n/de.po
  web_m2x_options/i18n/es.po
  web_m2x_options/i18n/fi.po
  web_m2x_options/i18n/fr.po
  web_m2x_options/i18n/hr.po
  web_m2x_options/i18n/it.po
  web_m2x_options/i18n/nl.po
  web_m2x_options/i18n/nl_NL.po
  web_m2x_options/i18n/pt_BR.po
  web_m2x_options/i18n/sl.po
  web_m2x_options/i18n/tr.po
  web_m2x_options/i18n/web_m2x_options.pot
  web_m2x_options/i18n/zh_CN.po
  web_m2x_options/models/__init__.py
  web_m2x_options/models/ir_config_parameter.py
  web_m2x_options/readme/CONTRIBUTORS.rst
  web_m2x_options/readme/CREDITS.rst
  web_m2x_options/readme/DESCRIPTION.rst
  web_m2x_options/readme/ROADMAP.rst
  web_m2x_options/readme/USAGE.rst
  web_m2x_options/static/description/icon.png
  web_m2x_options/static/description/index.html
  web_m2x_options/static/src/components/base.xml
  web_m2x_options/static/src/components/form.esm.js
  web_m2x_options/static/src/components/relational_utils.esm.js
  web_m2x_options/tests/__init__.py
  web_m2x_options/tests/test_ir_config_parameter.py
Labels: approved, ready to merge, bot is merging ⏳

#2130 [12.0][FIX] web_tree_dynamic_colored_field: all colors attributes must be parsed to work properly
  web_tree_dynamic_colored_field/__manifest__.py
  web_tree_dynamic_colored_field/demo/ir_translation.xml
  web_tree_dynamic_colored_field/readme/DESCRIPTION.rst
  web_tree_dynamic_colored_field/readme/USAGE.rst
  web_tree_dynamic_colored_field/static/src/js/web_tree_dynamic_colored_field.js
Labels: bot is merging ⏳

#2480 [FIX] NOBUMP. web_dashboard_tile : reduce duration to display tiles of a category
  web_dashboard_tile/__manifest__.py
  web_dashboard_tile/migrations/12.0.2.0.0/post-migration.py
  web_dashboard_tile/migrations/post-migration.py
  web_dashboard_tile/models/tile_category.py
  web_dashboard_tile/models/tile_tile.py
Labels: bot is merging ⏳

#2412 [16.0][MIG] web_notify: Migration to 16.0
  setup/web_notify/odoo/addons/web_notify
  setup/web_notify/setup.py
  web_notify/README.rst
  web_notify/__init__.py
  web_notify/__manifest__.py
  web_notify/i18n/da.po
  web_notify/i18n/de.po
  web_notify/i18n/es.po
  web_notify/i18n/hr.po
  web_notify/i18n/it.po
  web_notify/i18n/nl.po
  web_notify/i18n/nl_NL.po
  web_notify/i18n/pt_BR.po
  web_notify/i18n/web_notify.pot
  web_notify/i18n/zh_CN.po
  web_notify/models/__init__.py
  web_notify/models/res_users.py
  web_notify/readme/CONTRIBUTORS.rst
  web_notify/readme/DESCRIPTION.rst
  web_notify/readme/INSTALL.rst
  web_notify/readme/USAGE.rst
  web_notify/static/description/icon.png
  web_notify/static/description/index.html
  web_notify/static/description/notifications_screenshot.gif
  web_notify/static/description/test_notifications_demo.png
  web_notify/static/src/js/services/notification.esm.js
  web_notify/static/src/js/services/notification_services.esm.js
  web_notify/tests/__init__.py
  web_notify/tests/test_res_users.py
  web_notify/views/res_users_demo.xml
Labels: approved, bot is merging ⏳

#2484 [15.0] [FIX] `web_advanced_search`: Exception raised with "Search more..."
  web_advanced_search/static/src/js/RecordPicker.esm.js
Labels: approved, bot is merging ⏳

#2425 [16.0][MIG] web_dialog_size
  setup/web_dialog_size/odoo/addons/web_dialog_size
  setup/web_dialog_size/setup.py
  web_dialog_size/README.rst
  web_dialog_size/__init__.py
  web_dialog_size/__manifest__.py
  web_dialog_size/i18n/de.po
  web_dialog_size/i18n/es.po
  web_dialog_size/i18n/fr.po
  web_dialog_size/i18n/it.po
  web_dialog_size/i18n/nl.po
  web_dialog_size/i18n/web_dialog_size.pot
  web_dialog_size/i18n/zh_CN.po
  web_dialog_size/models/__init__.py
  web_dialog_size/models/ir_config_parameter.py
  web_dialog_size/readme/CONFIGURE.rst
  web_dialog_size/readme/CONTRIBUTORS.rst
  web_dialog_size/readme/DESCRIPTION.rst
  web_dialog_size/readme/ROADMAP.rst
  web_dialog_size/static/description/icon.png
  web_dialog_size/static/description/index.html
  web_dialog_size/static/src/js/web_dialog_draggable.esm.js
  web_dialog_size/static/src/js/web_dialog_size.esm.js
  web_dialog_size/static/src/js/web_dialog_size.js
  web_dialog_size/static/src/scss/web_dialog_size.scss
  web_dialog_size/static/src/xml/DialogDraggable.xml
  web_dialog_size/static/src/xml/ExpandButton.xml
  web_dialog_size/static/src/xml/web_dialog_size.xml
  web_dialog_size/tests/__init__.py
  web_dialog_size/tests/test_web_dialog_size.py
Labels: bot is merging ⏳

#2485 [16.0] [IMP] web theme classic
  web_theme_classic/static/src/scss/web_theme_classic.scss
Labels: approved, ready to merge, bot is merging ⏳
