Repository OCA/web, pull requests merged in 2023-10, with the labels that each got.

#2407 [15.0][ADD] web_widget_remote_measure: New module
  setup/web_widget_remote_measure/odoo/addons/web_widget_remote_measure
  setup/web_widget_remote_measure/setup.py
  web_widget_remote_measure/README.rst
  web_widget_remote_measure/__init__.py
  web_widget_remote_measure/__manifest__.py
  web_widget_remote_measure/models/__init__.py
  web_widget_remote_measure/models/remote_measure_device.py
  web_widget_remote_measure/models/res_users.py
  web_widget_remote_measure/readme/CONFIGURE.rst
  web_widget_remote_measure/readme/CONTRIBUTORS.rst
  web_widget_remote_measure/readme/DESCRIPTION.rst
  web_widget_remote_measure/readme/ROADMAP.rst
  web_widget_remote_measure/readme/USAGE.rst
  web_widget_remote_measure/security/ir.model.access.csv
  web_widget_remote_measure/static/description/icon.png
  web_widget_remote_measure/static/description/index.html
  web_widget_remote_measure/static/src/js/remote_measure_device_kanban_widget.esm.js
  web_widget_remote_measure/static/src/js/remote_measure_widget.esm.js
  web_widget_remote_measure/static/src/scss/remote_measure_widget.scss
  web_widget_remote_measure/static/src/xml/measure_device_status.xml
  web_widget_remote_measure/views/remote_measure_device_views.xml
  web_widget_remote_measure/views/res_users_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2632 [14.0][FIX] web_field_required_invisible_manager: regenerate rest. field
  web_field_required_invisible_manager/models/custom_field_restriction.py
  web_field_required_invisible_manager/tests/test_web_field_required_invisible_manager.py
Labels: bot is merging ⏳

#2633 [14.0][FIX] web_field_required_invisible_manager: restrict fields dependency
  web_field_required_invisible_manager/models/custom_field_restriction.py
  web_field_required_invisible_manager/readme/ROADMAP.rst
  web_field_required_invisible_manager/tests/test_web_field_required_invisible_manager.py
Labels: bot is merging ⏳

#2637 [14.0][FIX] web_field_required_invisible_manager: consider portal users
  web_field_required_invisible_manager/models/models.py
Labels: bot is merging ⏳

#2617 [ADD][16.0] web_apply_field_style module
  setup/web_apply_field_style/odoo/addons/web_apply_field_style
  setup/web_apply_field_style/setup.py
  web_apply_field_style/README.rst
  web_apply_field_style/__init__.py
  web_apply_field_style/__manifest__.py
  web_apply_field_style/demo/__init__.py
  web_apply_field_style/demo/base.py
  web_apply_field_style/models/__init__.py
  web_apply_field_style/models/base.py
  web_apply_field_style/readme/CONFIGURE.rst
  web_apply_field_style/readme/CONTRIBUTORS.rst
  web_apply_field_style/readme/DESCRIPTION.rst
  web_apply_field_style/static/description/demo.png
  web_apply_field_style/static/description/icon.png
  web_apply_field_style/static/description/index.html
  web_apply_field_style/tests/__init__.py
  web_apply_field_style/tests/test_module.py
Labels: approved, ready to merge, bot is merging ⏳

#2638 [15.0][FIX] web_advanced_search: search more filters
  web_advanced_search/static/src/js/owl/dropdown.esm.js
Labels: approved, bot is merging ⏳

#2639 [16.0][FIX] web_advanced_search: search more filters
  web_advanced_search/static/src/js/dropdown.esm.js
Labels: approved, bot is merging ⏳

#2622 [16.0][IMP] web_responsive: Fixed full-screen apps menu
  web_responsive/static/src/components/apps_menu/apps_menu.scss
Labels: approved, bot is merging ⏳

#2576 [IMP] web_create_write_confirm: fix JS, usage. Minor refactoring.
  web_create_write_confirm/__manifest__.py
  web_create_write_confirm/models/base.py
  web_create_write_confirm/models/popup_message.py
  web_create_write_confirm/readme/USAGE.rst
  web_create_write_confirm/static/src/js/pop_up_confirmation.js
  web_create_write_confirm/tests/test_base_model.py
Labels: approved, ready to merge, bot is merging ⏳

#2641 [15.0][FIX] web_widget_domain_editor_dialog: keep context
  web_widget_domain_editor_dialog/static/src/js/basic_fields.js
Labels: approved, bot is merging ⏳

#2643 [13.0][FIX] web_widget_domain_editor_dialog: keep context
  web_widget_domain_editor_dialog/static/src/js/basic_fields.js
Labels: bot is merging ⏳

#2625 [15.0][FIX] web_advanced_search: Fixed changes from code editor not propagated
  web_advanced_search/static/src/js/DomainSelector.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2644 [14.0] web_edit_user_filter: Fix selection of facet
  web_edit_user_filter/static/src/js/backend.js
Labels: bot is merging ⏳

#2091 [14.0][ADD] web_widget_uom
  setup/web_widget_uom/odoo/addons/web_widget_uom
  setup/web_widget_uom/setup.py
  web_widget_uom/README.rst
  web_widget_uom/__init__.py
  web_widget_uom/__manifest__.py
  web_widget_uom/i18n/it.po
  web_widget_uom/models/__init__.py
  web_widget_uom/models/uom_uom.py
  web_widget_uom/readme/CONTRIBUTORS.rst
  web_widget_uom/readme/DESCRIPTION.rst
  web_widget_uom/readme/ROADMAP.rst
  web_widget_uom/readme/USAGE.rst
  web_widget_uom/static/description/UoMDecimalPlaces.png
  web_widget_uom/static/description/index.html
  web_widget_uom/static/src/js/widget.js
  web_widget_uom/tests/__init__.py
  web_widget_uom/tests/test_decimal_precision.py
  web_widget_uom/views/assets.xml
  web_widget_uom/views/uom_uom_views.xml
Labels: approved, bot is merging ⏳

#2347 [15.0][IMP] web_ir_actions_act_view_reload: Change IrActionsActViewReload to AbstractModel
  web_ir_actions_act_view_reload/models/ir_actions_act_view_reload.py
Labels: approved, ready to merge, bot is merging ⏳

#2649 [14.0][IMP] update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml.rej
  .github/workflows/test.yml
  .pre-commit-config.yaml
  support_branding/demo/ir_config_parameter_data.xml
  web_create_write_confirm/views/assets.xml
  web_create_write_confirm/views/popup_message.xml
  web_field_required_invisible_manager/views/views.xml
  web_m2x_options_manager/views/ir_model.xml
  web_no_bubble/views/web_no_bubble.xml
  web_pwa_oca/views/res_config_settings_views.xml
  web_switch_context_warning/view/view.xml
Labels: approved, bot is merging ⏳

#2646 [16.0][MIG] web_calendar_slot_duration: Migration to version 16.0
  setup/web_calendar_slot_duration/odoo/addons/web_calendar_slot_duration
  setup/web_calendar_slot_duration/setup.py
  web_calendar_slot_duration/README.rst
  web_calendar_slot_duration/__init__.py
  web_calendar_slot_duration/__manifest__.py
  web_calendar_slot_duration/i18n/de.po
  web_calendar_slot_duration/i18n/pt_BR.po
  web_calendar_slot_duration/i18n/web_calendar_slot_duration.pot
  web_calendar_slot_duration/readme/CONFIGURE.rst
  web_calendar_slot_duration/readme/CONTRIBUTORS.rst
  web_calendar_slot_duration/readme/DESCRIPTION.rst
  web_calendar_slot_duration/readme/ROADMAP.rst
  web_calendar_slot_duration/readme/USAGE.rst
  web_calendar_slot_duration/static/description/icon.png
  web_calendar_slot_duration/static/description/index.html
  web_calendar_slot_duration/static/src/js/calendar_common_renderer.esm.js
  web_calendar_slot_duration/static/src/js/calendar_model.esm.js
Labels: bot is merging ⏳
