Repository OCA/web, pull requests merged in 2023-03, with the labels that each got.

#2341 [15.0][MIG] web_pivot_computed_measure: Migration to 15.0
  setup/web_pivot_computed_measure/odoo/addons/web_pivot_computed_measure
  setup/web_pivot_computed_measure/setup.py
  web_pivot_computed_measure/README.rst
  web_pivot_computed_measure/__init__.py
  web_pivot_computed_measure/__manifest__.py
  web_pivot_computed_measure/i18n/ca.po
  web_pivot_computed_measure/i18n/es.po
  web_pivot_computed_measure/i18n/web_pivot_computed_measure.pot
  web_pivot_computed_measure/readme/CONTRIBUTORS.rst
  web_pivot_computed_measure/readme/DESCRIPTION.rst
  web_pivot_computed_measure/readme/ROADMAP.rst
  web_pivot_computed_measure/readme/USAGE.rst
  web_pivot_computed_measure/static/description/icon.png
  web_pivot_computed_measure/static/description/index.html
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.esm.js
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.scss
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.xml
  web_pivot_computed_measure/static/src/pivot/pivot_model.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_view.xml
  web_pivot_computed_measure/static/src/test/test.esm.js
  web_pivot_computed_measure/static/src/view.xml
  web_pivot_computed_measure/tests/__init__.py
  web_pivot_computed_measure/tests/res_users_fake.py
  web_pivot_computed_measure/tests/test_ui_pivot.py
Labels: approved, bot is merging ⏳

#2417 [16.0][ADD] web_help
  setup/web_help/odoo/addons/web_help
  setup/web_help/setup.py
  web_help/README.rst
  web_help/__init__.py
  web_help/__manifest__.py
  web_help/readme/CONTRIBUTORS.rst
  web_help/readme/DESCRIPTION.rst
  web_help/readme/ROADMAP.rst
  web_help/readme/USAGE.rst
  web_help/static/description/changepassword.png
  web_help/static/description/demo.gif
  web_help/static/description/viewswitcher.png
  web_help/static/src/change_password_trip.esm.js
  web_help/static/src/components/help_button/help_button.esm.js
  web_help/static/src/components/help_button/help_button.xml
  web_help/static/src/components/highlighter/highlighter.esm.js
  web_help/static/src/components/highlighter/highlighter.scss
  web_help/static/src/components/highlighter/highlighter.xml
  web_help/static/src/helpers.esm.js
  web_help/static/src/trip.esm.js
  web_help/static/src/trip.xml
  web_help/static/src/user_trip.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2378 [MIG] web_timeline: Migration to 16.0
  setup/web_timeline/odoo/addons/web_timeline
  setup/web_timeline/setup.py
  web_timeline/README.rst
  web_timeline/__init__.py
  web_timeline/__manifest__.py
  web_timeline/i18n/de.po
  web_timeline/i18n/es.po
  web_timeline/i18n/fa.po
  web_timeline/i18n/fr.po
  web_timeline/i18n/he.po
  web_timeline/i18n/hr.po
  web_timeline/i18n/nl_NL.po
  web_timeline/i18n/pt.po
  web_timeline/i18n/pt_BR.po
  web_timeline/i18n/web_timeline.pot
  web_timeline/i18n/zh_CN.po
  web_timeline/models/__init__.py
  web_timeline/models/ir_ui_view.py
  web_timeline/readme/CONFIGURE.rst
  web_timeline/readme/CONTRIBUTORS.rst
  web_timeline/readme/DESCRIPTION.rst
  web_timeline/readme/ROADMAP.rst
  web_timeline/readme/USAGE.rst
  web_timeline/static/description/icon.png
  web_timeline/static/description/index.html
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.css
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js
  web_timeline/static/src/js/timeline_canvas.js
  web_timeline/static/src/js/timeline_controller.esm.js
  web_timeline/static/src/js/timeline_model.js
  web_timeline/static/src/js/timeline_renderer.js
  web_timeline/static/src/js/timeline_view.js
  web_timeline/static/src/scss/web_timeline.scss
  web_timeline/static/src/xml/web_timeline.xml
Labels: approved, ready to merge, bot is merging ⏳

#2419 [16.0] [MIG] `web_chatter_position`
  setup/web_chatter_position/odoo/addons/web_chatter_position
  setup/web_chatter_position/setup.py
  web_chatter_position/README.rst
  web_chatter_position/__init__.py
  web_chatter_position/__manifest__.py
  web_chatter_position/i18n/web_chatter_position.pot
  web_chatter_position/models/__init__.py
  web_chatter_position/models/res_users.py
  web_chatter_position/readme/CONTRIBUTORS.rst
  web_chatter_position/readme/DESCRIPTION.rst
  web_chatter_position/readme/USAGE.rst
  web_chatter_position/static/description/icon.png
  web_chatter_position/static/description/index.html
  web_chatter_position/static/src/js/web_chatter_position.esm.js
  web_chatter_position/views/res_users.xml
  web_chatter_position/views/web.xml
Labels: approved, bot is merging ⏳

#2424 [15.0][FIX] Fix for attachment viewer visible on home page
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
  web_responsive/static/src/components/attachment_viewer/attachment_viewer.scss
Labels: approved, bot is merging ⏳

#2429 [14.0][FIX] web_timeline: css and styles not charged when rendering timeline
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  web_timeline/static/src/js/timeline_renderer.js
Labels: approved, bot is merging ⏳

#2430 [15.0][FIX] web_timeline: css and styles not charged when rendering timeline
  web_timeline/static/src/js/timeline_renderer.js
Labels: approved, bot is merging ⏳

#2409 [FIX] web_m2x_options: M2Dialog not working properly
  web_m2x_options/static/src/js/form.js
Labels: approved, bot is merging ⏳

#2440 [16.0][FIX] web_responsive: Align checkboxes in Favourites save current search view
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: approved, bot is merging ⏳

#2442 [16.0][FIX] web_responsive: Show View Type Always
  web_responsive/static/src/components/control_panel/control_panel.scss
Labels: bot is merging ⏳

#2441 [16.0][FIX] web_responsive: Align menu for dates in filters
  web_responsive/static/src/components/control_panel/control_panel.scss
Labels: bot is merging ⏳

#2042 [web_widget_x2many_2d_matrix][FIX] - add support for `disabled` or `hidden` attributes using field_att_
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/readme/USAGE.rst
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/src/js/2d_matrix_renderer.js
  web_widget_x2many_2d_matrix/static/src/js/abstract_view_matrix_limit_extend.js
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
Labels: approved, ready to merge, bot is merging ⏳

#2422 [MIG][16.0] web_tree_many2one_clickable
  setup/web_tree_many2one_clickable/odoo/addons/web_tree_many2one_clickable
  setup/web_tree_many2one_clickable/setup.py
  web_tree_many2one_clickable/README.rst
  web_tree_many2one_clickable/__init__.py
  web_tree_many2one_clickable/__manifest__.py
  web_tree_many2one_clickable/i18n/web_tree_many2one_clickable.pot
  web_tree_many2one_clickable/i18n/zh_CN.po
  web_tree_many2one_clickable/readme/CONFIGURATION.rst
  web_tree_many2one_clickable/readme/CONTRIBUTORS.rst
  web_tree_many2one_clickable/readme/DESCRIPTION.rst
  web_tree_many2one_clickable/readme/ROADMAP.rst
  web_tree_many2one_clickable/readme/USAGE.rst
  web_tree_many2one_clickable/static/description/icon.png
  web_tree_many2one_clickable/static/description/index.html
  web_tree_many2one_clickable/static/img/clickable.gif
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.esm.js
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.scss
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.xml
Labels: approved, ready to merge, bot is merging ⏳

#2457 [16.0][FIX] web_responsive: fix bug test ESLint
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
Labels: approved, bot is merging ⏳

#2399 [14.0][FIX] #3039 support_branding ACL bug
  support_branding/models/__init__.py
  support_branding/models/res_company.py
  support_branding/static/src/js/res_config_edition.js
  support_branding/static/src/js/support_branding.js
  support_branding/static/src/js/user_menu.js
  support_branding/tests/__init__.py
  support_branding/tests/test_support_branding.py
Labels: approved, bot is merging ⏳

#2462 [16.0][MIG] web_no_bubble
  setup/web_no_bubble/odoo/addons/web_no_bubble
  setup/web_no_bubble/setup.py
  web_no_bubble/README.rst
  web_no_bubble/__init__.py
  web_no_bubble/__manifest__.py
  web_no_bubble/i18n/es.po
  web_no_bubble/i18n/fr_FR.po
  web_no_bubble/i18n/hr.po
  web_no_bubble/i18n/web_no_bubble.pot
  web_no_bubble/i18n/zh_CN.po
  web_no_bubble/readme/CONTRIBUTORS.rst
  web_no_bubble/readme/DESCRIPTION.rst
  web_no_bubble/static/description/icon.png
  web_no_bubble/static/description/index.html
  web_no_bubble/static/src/css/web_no_bubble.scss
Labels: approved, ready to merge, bot is merging ⏳

#2471 [15.0][MIG] web_time_range_menu_custom: Migration to 15.0
  setup/web_time_range_menu_custom/odoo/addons/web_time_range_menu_custom
  setup/web_time_range_menu_custom/setup.py
  web_time_range_menu_custom/README.rst
  web_time_range_menu_custom/__init__.py
  web_time_range_menu_custom/__manifest__.py
  web_time_range_menu_custom/i18n/web_time_range_menu_custom.pot
  web_time_range_menu_custom/readme/CONTRIBUTORS.rst
  web_time_range_menu_custom/readme/DESCRIPTION.rst
  web_time_range_menu_custom/static/description/icon.png
  web_time_range_menu_custom/static/description/index.html
  web_time_range_menu_custom/static/src/js/date_selector.esm.js
  web_time_range_menu_custom/static/src/js/dates.esm.js
  web_time_range_menu_custom/static/src/scss/web_time_range_menu_custom.scss
  web_time_range_menu_custom/static/src/xml/comparison_menu.xml
  web_time_range_menu_custom/static/src/xml/date_selector.xml
  web_time_range_menu_custom/static/src/xml/filter_menu.xml
Labels: approved, bot is merging ⏳
