Repository OCA/web, pull requests merged in 2023-07, with the labels that each got.

#2466 [14.0][FIX] web_ir_action_act_*: add/fix access rights
  web_ir_actions_act_multi/security/ir.model.access.csv
  web_ir_actions_act_view_reload/__manifest__.py
  web_ir_actions_act_view_reload/security/ir.model.access.csv
  web_ir_actions_act_window_message/security/ir.model.access.csv
Labels: approved, ready to merge

#2519 [15.0][MIG] web_send_message_popup: Migration to 15.0
  setup/web_send_message_popup/odoo/addons/web_send_message_popup
  setup/web_send_message_popup/setup.py
  web_send_message_popup/README.rst
  web_send_message_popup/__init__.py
  web_send_message_popup/__manifest__.py
  web_send_message_popup/i18n/fa.po
  web_send_message_popup/i18n/web_send_message_popup.pot
  web_send_message_popup/readme/CONTRIBUTORS.rst
  web_send_message_popup/readme/DESCRIPTION.rst
  web_send_message_popup/static/description/icon.png
  web_send_message_popup/static/description/index.html
  web_send_message_popup/static/src/models/chatter/chatter.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2538 [15.0][MIG] web_disable_export_group: Migration to 15.0
  setup/web_disable_export_group/odoo/addons/web_disable_export_group
  setup/web_disable_export_group/setup.py
  web_disable_export_group/README.rst
  web_disable_export_group/__init__.py
  web_disable_export_group/__manifest__.py
  web_disable_export_group/i18n/es.po
  web_disable_export_group/i18n/hr.po
  web_disable_export_group/i18n/pt.po
  web_disable_export_group/i18n/web_disable_export_group.pot
  web_disable_export_group/i18n/zh_CN.po
  web_disable_export_group/models/__init__.py
  web_disable_export_group/models/ir_http.py
  web_disable_export_group/models/models.py
  web_disable_export_group/readme/CONFIGURE.rst
  web_disable_export_group/readme/CONTRIBUTORS.rst
  web_disable_export_group/readme/DESCRIPTION.rst
  web_disable_export_group/readme/USAGE.rst
  web_disable_export_group/security/groups.xml
  web_disable_export_group/security/ir.model.access.csv
  web_disable_export_group/static/description/icon.png
  web_disable_export_group/static/description/index.html
  web_disable_export_group/static/src/js/abstract_controller.esm.js
  web_disable_export_group/static/src/js/list_controller.esm.js
  web_disable_export_group/static/src/tours/web_disable_export_group_tour.esm.js
  web_disable_export_group/static/src/xml/export_xls_views.xml
  web_disable_export_group/tests/__init__.py
  web_disable_export_group/tests/test_tour.py
Labels: approved, bot is merging ⏳

#2557 added trim method to _selectSource
  web_search_with_and/static/src/js/search_bar.js
Labels: approved, bot is merging ⏳

#2565 [15.0][FIX] web_responsive: increase z-index of attachment_viewer
  web_responsive/static/src/components/attachment_viewer/attachment_viewer.scss
Labels: approved, bot is merging ⏳

#2500 [16.0][MIG] web_action_conditionable: Migration to 16.0
  setup/web_action_conditionable/odoo/addons/web_action_conditionable
  setup/web_action_conditionable/setup.py
  web_action_conditionable/README.rst
  web_action_conditionable/__init__.py
  web_action_conditionable/__manifest__.py
  web_action_conditionable/i18n/es.po
  web_action_conditionable/i18n/hr.po
  web_action_conditionable/i18n/web_action_conditionable.pot
  web_action_conditionable/i18n/zh_CN.po
  web_action_conditionable/readme/CONTRIBUTORS.rst
  web_action_conditionable/readme/CREDITS.rst
  web_action_conditionable/readme/DESCRIPTION.rst
  web_action_conditionable/readme/USAGE.rst
  web_action_conditionable/static/description/icon.png
  web_action_conditionable/static/description/index.html
  web_action_conditionable/static/src/components/field_one2many.esm.js
Labels: approved, bot is merging ⏳

#2508 [15.0][FIX] web_pivot_computed_measure: Not found measures whan changing to pivot view
  web_pivot_computed_measure/static/src/pivot/pivot_model.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_renderer.esm.js
Labels: bot is merging ⏳

#2510 [16.0][MIG] web_remember_tree_column_width: Migration to 16.0
  setup/web_remember_tree_column_width/odoo/addons/web_remember_tree_column_width
  setup/web_remember_tree_column_width/setup.py
  web_remember_tree_column_width/README.rst
  web_remember_tree_column_width/__init__.py
  web_remember_tree_column_width/__manifest__.py
  web_remember_tree_column_width/i18n/web_remember_tree_column_width.pot
  web_remember_tree_column_width/readme/CONTRIBUTORS.rst
  web_remember_tree_column_width/readme/CREDITS.rst
  web_remember_tree_column_width/readme/DESCRIPTION.rst
  web_remember_tree_column_width/static/description/icon.png
  web_remember_tree_column_width/static/description/index.html
  web_remember_tree_column_width/static/src/js/list_renderer.esm.js
  web_remember_tree_column_width/static/src/scss/main.scss
Labels: approved, ready to merge, bot is merging ⏳

#2487 [14.0][ADD] web_create_write_confirm
  setup/web_create_write_confirm/odoo/addons/web_create_write_confirm
  setup/web_create_write_confirm/setup.py
  web_create_write_confirm/README.rst
  web_create_write_confirm/__init__.py
  web_create_write_confirm/__manifest__.py
  web_create_write_confirm/models/__init__.py
  web_create_write_confirm/models/base.py
  web_create_write_confirm/models/popup_message.py
  web_create_write_confirm/readme/CONTRIBUTORS.rst
  web_create_write_confirm/readme/DESCRIPTION.rst
  web_create_write_confirm/readme/USAGE.rst
  web_create_write_confirm/security/ir.model.access.csv
  web_create_write_confirm/static/description/icon.png
  web_create_write_confirm/static/src/js/pop_up_confirmation.js
  web_create_write_confirm/tests/__init__.py
  web_create_write_confirm/tests/test_base_model.py
  web_create_write_confirm/views/assets.xml
  web_create_write_confirm/views/popup_message.xml
Labels: bot is merging ⏳

#2453 [16.0][mig] web_widget_open_tab: Migration to 16.0
  setup/web_widget_open_tab/odoo/addons/web_widget_open_tab
  setup/web_widget_open_tab/setup.py
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/demo/res_users_view.xml
  web_widget_open_tab/i18n/ca.po
  web_widget_open_tab/i18n/de.po
  web_widget_open_tab/i18n/es.po
  web_widget_open_tab/i18n/pt_BR.po
  web_widget_open_tab/i18n/web_widget_open_tab.pot
  web_widget_open_tab/readme/CONTRIBUTORS.rst
  web_widget_open_tab/readme/DESCRIPTION.rst
  web_widget_open_tab/readme/USAGE.rst
  web_widget_open_tab/static/description/icon.png
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/static/src/js/open_tab_widget.esm.js
  web_widget_open_tab/static/src/xml/open_tab_widget.xml
Labels: approved, bot is merging ⏳

#2569 [13.0][MIG] web_chatter_position
  setup/web_chatter_position/odoo/addons/web_chatter_position
  setup/web_chatter_position/setup.py
  web_chatter_position/README.rst
  web_chatter_position/__init__.py
  web_chatter_position/__manifest__.py
  web_chatter_position/i18n/web_chatter_position.pot
  web_chatter_position/models/__init__.py
  web_chatter_position/models/res_users.py
  web_chatter_position/readme/CONTRIBUTORS.rst
  web_chatter_position/readme/DESCRIPTION.rst
  web_chatter_position/readme/ROADMAP.rst
  web_chatter_position/readme/USAGE.rst
  web_chatter_position/static/description/icon.png
  web_chatter_position/static/description/index.html
  web_chatter_position/static/src/js/form_chatter_position.js
  web_chatter_position/static/src/scss/attachment_viewer.scss
  web_chatter_position/static/src/scss/chatter_position.scss
  web_chatter_position/static/src/xml/form_buttons.xml
  web_chatter_position/views/assets.xml
  web_chatter_position/views/res_users.xml
  web_chatter_position/views/web.xml
Labels: approved, ready to merge, bot is merging ⏳

#2208 [13.0][FIX] web_m2x_options: Scroll dance
  web_m2x_options/README.rst
  web_m2x_options/readme/CONTRIBUTORS.rst
  web_m2x_options/static/src/js/form.js
Labels: bot is merging ⏳

#2574 [FIX] web_widget_bokeh_chart : bad image path in description, break readme file
  web_widget_bokeh_chart/readme/DESCRIPTION.rst
Labels: needs review, bot is merging ⏳

#2575 [16.0][FIX] web_m2x_options: Avoid constant RPC calls
  web_m2x_options/models/__init__.py
  web_m2x_options/models/ir_http.py
  web_m2x_options/static/src/components/form.esm.js
  web_m2x_options/static/src/components/relational_utils.esm.js
Labels: approved, bot is merging ⏳
