Repository OCA/web, pull requests merged in 2023-11, with the labels that each got.

#2654 [16.0][FIX] web_responsive: overlapping issue
  web_responsive/static/src/components/apps_menu/apps_menu.scss
Labels: approved, bot is merging ⏳

#2658 [16.0][FIX] web_responsive: overlapping issue
  web_responsive/static/src/components/apps_menu/apps_menu.scss
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: approved, bot is merging ⏳

#2645 [FIX][16.0] web_chatter_position: special case of sided chatter pos in mass mailing module
  web_chatter_position/static/src/js/web_chatter_position.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2534 [16.0][IMP] web_company_color: Forward port #2209 from 14.0
  web_company_color/models/res_company.py
  web_company_color/view/res_company.xml
Labels: approved, ready to merge, bot is merging ⏳

#2543 [16.0][MIG] web_notify_channel_message
  setup/web_notify_channel_message/odoo/addons/web_notify_channel_message
  setup/web_notify_channel_message/setup.py
  web_notify_channel_message/README.rst
  web_notify_channel_message/__init__.py
  web_notify_channel_message/__manifest__.py
  web_notify_channel_message/i18n/fr.po
  web_notify_channel_message/i18n/web_notify_channel_message.pot
  web_notify_channel_message/models/__init__.py
  web_notify_channel_message/models/mail_channel.py
  web_notify_channel_message/readme/CONTRIBUTORS.rst
  web_notify_channel_message/readme/DESCRIPTION.rst
  web_notify_channel_message/static/description/icon.png
  web_notify_channel_message/static/description/index.html
  web_notify_channel_message/tests/__init__.py
  web_notify_channel_message/tests/test_notify_channel_message.py
Labels: approved, ready to merge, bot is merging ⏳

#2655 [16.0][FIX] web_calendar_slot_duration: custom event length
  web_calendar_slot_duration/static/src/js/calendar_model.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2662 [16.0][FIX] web_dark_mode: Add fields to field lists
  web_dark_mode/models/res_users.py
Labels: approved, bot is merging ⏳

#2369 [FIX] drag_drop element cannot be seen, if check for undefined value
  web_drop_target/static/src/js/web_drop_target.js
Labels: approved, ready to merge, bot is merging ⏳

#2664 [16.0] web_m2x_options: impossible to open a mass mailing
  web_m2x_options/static/src/components/form.esm.js
Labels: bot is merging ⏳

#2553 [ADD] web_field_tooltip : new module to manage tooltips
  setup/web_field_tooltip/odoo/addons/web_field_tooltip
  setup/web_field_tooltip/setup.py
  web_field_tooltip/README.rst
  web_field_tooltip/__init__.py
  web_field_tooltip/__manifest__.py
  web_field_tooltip/i18n/fr.po
  web_field_tooltip/i18n/web_field_tooltip.pot
  web_field_tooltip/models/__init__.py
  web_field_tooltip/models/ir_http.py
  web_field_tooltip/models/ir_model_fields_tooltip.py
  web_field_tooltip/models/res_users.py
  web_field_tooltip/readme/CONTRIBUTORS.rst
  web_field_tooltip/readme/DESCRIPTION.rst
  web_field_tooltip/readme/ROADMAP.rst
  web_field_tooltip/readme/USAGE.rst
  web_field_tooltip/security/ir_model_access.xml
  web_field_tooltip/security/res_groups.xml
  web_field_tooltip/static/description/icon.png
  web_field_tooltip/static/description/index.html
  web_field_tooltip/static/src/css/web_field_tooltip.css
  web_field_tooltip/static/src/js/controller.js
  web_field_tooltip/static/src/js/renderer.js
  web_field_tooltip/static/src/js/web_field_tooltip.js
  web_field_tooltip/tests/__init__.py
  web_field_tooltip/tests/test_web_field_tooltip.py
  web_field_tooltip/views/ir_model_fields_tooltip.xml
  web_field_tooltip/views/res_users.xml
  web_field_tooltip/views/template.xml
Labels: approved, ready to merge, bot is merging ⏳

#2678 [REF] copier update v1.17.2 -> v1.19.2
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: approved

#2631 [14.0][ADD] web_button_invisible
  setup/web_button_visibility/odoo/addons/web_button_visibility
  setup/web_button_visibility/setup.py
  web_button_visibility/README.rst
  web_button_visibility/__init__.py
  web_button_visibility/__manifest__.py
  web_button_visibility/data/demo.xml
  web_button_visibility/models/__init__.py
  web_button_visibility/models/base.py
  web_button_visibility/models/hide_button_rule.py
  web_button_visibility/models/ir_model.py
  web_button_visibility/readme/CONTEXT.rst
  web_button_visibility/readme/CONTRIBUTORS.rst
  web_button_visibility/readme/DESCRIPTION.rst
  web_button_visibility/readme/USAGE.rst
  web_button_visibility/security/ir.model.access.csv
  web_button_visibility/static/description/index.html
  web_button_visibility/tests/__init__.py
  web_button_visibility/tests/test_button_invisible.py
  web_button_visibility/views/views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2675 [15.0][IMP] web_notify
  web_notify/models/res_users.py
Labels: approved, bot is merging ⏳

#2554 [16.0][MIG] web_tree_duplicate
  setup/web_tree_duplicate/odoo/addons/web_tree_duplicate
  setup/web_tree_duplicate/setup.py
  web_tree_duplicate/README.rst
  web_tree_duplicate/__init__.py
  web_tree_duplicate/__manifest__.py
  web_tree_duplicate/i18n/ca.po
  web_tree_duplicate/i18n/es.po
  web_tree_duplicate/i18n/fr.po
  web_tree_duplicate/i18n/he_IL.po
  web_tree_duplicate/i18n/pt.po
  web_tree_duplicate/i18n/pt_BR.po
  web_tree_duplicate/i18n/web_tree_duplicate.pot
  web_tree_duplicate/i18n/zh_CN.po
  web_tree_duplicate/readme/CONFIGURE.rst
  web_tree_duplicate/readme/CONTRIBUTORS.rst
  web_tree_duplicate/readme/DESCRIPTION.rst
  web_tree_duplicate/readme/USAGE.rst
  web_tree_duplicate/static/description/icon.png
  web_tree_duplicate/static/description/index.html
  web_tree_duplicate/static/description/screenshot-duplicate.png
  web_tree_duplicate/static/src/web_tree_duplicate.esm.js
Labels: approved, bot is merging ⏳

#2659 [FIX] web_field_required_invisible_manager: fix depend. domain compute
  web_field_required_invisible_manager/models/custom_field_restriction.py
Labels: approved, ready to merge, bot is merging ⏳

#2443 [FIX][12.0] web_tree_dynamic_colored_field : return first color that match with valid expression.
  web_tree_dynamic_colored_field/static/src/js/web_tree_dynamic_colored_field.js
Labels: approved, bot is merging ⏳

#2669 [17.0][MIG] web_refresher: Migration to 17.0
  web_refresher/README.rst
  web_refresher/__init__.py
  web_refresher/__manifest__.py
  web_refresher/i18n/ca.po
  web_refresher/i18n/de.po
  web_refresher/i18n/es.po
  web_refresher/i18n/fr.po
  web_refresher/i18n/hr.po
  web_refresher/i18n/pt_BR.po
  web_refresher/i18n/uk_UA.po
  web_refresher/i18n/web_refresher.pot
  web_refresher/pyproject.toml
  web_refresher/readme/CONTRIBUTORS.md
  web_refresher/readme/DESCRIPTION.md
  web_refresher/static/description/icon.png
  web_refresher/static/description/index.html
  web_refresher/static/description/refresh.png
  web_refresher/static/src/js/control_panel.esm.js
  web_refresher/static/src/js/refresher.esm.js
  web_refresher/static/src/scss/refresher.scss
  web_refresher/static/src/xml/control_panel.xml
  web_refresher/static/src/xml/refresher.xml
Labels: approved, ready to merge, bot is merging ⏳

#1521 [IMP] web_environment_ribbon: Allow to generate ribbon name with code
  web_environment_ribbon/models/web_environment_ribbon_backend.py
  web_environment_ribbon/readme/CONFIGURE.rst
Labels: approved, bot is merging ⏳, stale

#2312 [14.0] Add web_fix_modules_load
  setup/web_fix_modules_load/odoo/addons/web_fix_modules_load
  setup/web_fix_modules_load/setup.py
  web_fix_modules_load/README.rst
  web_fix_modules_load/__init__.py
  web_fix_modules_load/__manifest__.py
  web_fix_modules_load/controllers/__init__.py
  web_fix_modules_load/controllers/main.py
  web_fix_modules_load/models/__init__.py
  web_fix_modules_load/models/ir_module.py
  web_fix_modules_load/models/ir_translation.py
  web_fix_modules_load/readme/CONTRIBUTORS.rst
  web_fix_modules_load/readme/DESCRIPTION.rst
  web_fix_modules_load/static/src/js/session.js
  web_fix_modules_load/templates/assets.xml
Labels: approved, bot is merging ⏳

#2679 [15.0][FIX] web_pivot_computed_measure: Use js eval to avoid different types operation error
  web_pivot_computed_measure/static/src/helpers/utils.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_model.esm.js
Labels: approved, bot is merging ⏳
