Repository OCA/web, pull requests merged in 2024-02, with the labels that each got.

#2168 [12.0] [FIX] web_advanced_filter: prevent error on filter delete
  web_advanced_filter/wizards/ir_filters_combine_with_existing.py
Labels: bot is merging ⏳

#2593 [12.0][FIX] web_translate_dialog dataset context not always filled
  web_translate_dialog/static/src/js/web_translate_dialog.js
Labels: bot is merging ⏳

#2740 [15.0][IMP] web_refresher: Provide the ability to reload information from a report view
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/static/description/index.html
  web_refresher/static/src/js/client_action_adapter.esm.js
  web_refresher/static/src/js/refresher.esm.js
Labels: approved, bot is merging ⏳

#2743 [16.0][IMP] web_refresher: Provide the ability to reload information from a report view
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/static/description/index.html
  web_refresher/static/src/js/control_panel.esm.js
  web_refresher/static/src/js/refresher.esm.js
  web_refresher/static/src/scss/refresher.scss
  web_refresher/static/src/xml/control_panel.xml
Labels: approved, bot is merging ⏳

#2739 [14.0][IMP] web_field_required_invisible_manager: compatibility with tier v…
  web_field_required_invisible_manager/models/__init__.py
  web_field_required_invisible_manager/models/base.py
  web_field_required_invisible_manager/models/ir_model.py
  web_field_required_invisible_manager/models/ir_ui_view.py
  web_field_required_invisible_manager/static/description/index.html
Labels: approved, bot is merging ⏳

#2561 [16.0][FIX]: web_widget_x2many_2d_matrix: Editable boolean
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
  web_widget_x2many_2d_matrix/static/src/views/fields/boolean/boolean_field.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2738 [16.0][MIG] web_widget_datepicker_fulloptions
  setup/web_widget_datepicker_fulloptions/odoo/addons/web_widget_datepicker_fulloptions
  setup/web_widget_datepicker_fulloptions/setup.py
  web_widget_datepicker_fulloptions/README.rst
  web_widget_datepicker_fulloptions/__init__.py
  web_widget_datepicker_fulloptions/__manifest__.py
  web_widget_datepicker_fulloptions/i18n/pt_BR.po
  web_widget_datepicker_fulloptions/i18n/web_widget_datepicker_fulloptions.pot
  web_widget_datepicker_fulloptions/readme/CONTRIBUTORS.rst
  web_widget_datepicker_fulloptions/readme/DESCRIPTION.rst
  web_widget_datepicker_fulloptions/static/description/change.png
  web_widget_datepicker_fulloptions/static/description/icon.png
  web_widget_datepicker_fulloptions/static/description/index.html
  web_widget_datepicker_fulloptions/static/src/js/web_widget_datepicker_fulloptions.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2386 [15.0][UPD] web_tree_dynamic_colored_field: readme usage section
  web_tree_dynamic_colored_field/README.rst
  web_tree_dynamic_colored_field/readme/USAGE.rst
  web_tree_dynamic_colored_field/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#2751 [16.0][FIX] web_responsive: chatter with _mail_post_access read
  web_responsive/static/src/components/chatter_topbar/chatter_topbar.xml
Labels: approved, bot is merging ⏳

#2640 [16.0][MIG] web_pwa_oca: Migration to 16.0
  setup/web_pwa_oca/odoo/addons/web_pwa_oca
  setup/web_pwa_oca/setup.py
  web_pwa_oca/README.rst
  web_pwa_oca/__init__.py
  web_pwa_oca/__manifest__.py
  web_pwa_oca/controllers/__init__.py
  web_pwa_oca/controllers/main.py
  web_pwa_oca/controllers/service_worker.py
  web_pwa_oca/i18n/es.po
  web_pwa_oca/i18n/es_AR.po
  web_pwa_oca/i18n/pt_BR.po
  web_pwa_oca/i18n/web_pwa_oca.pot
  web_pwa_oca/models/__init__.py
  web_pwa_oca/models/res_config_settings.py
  web_pwa_oca/readme/CONFIGURE.rst
  web_pwa_oca/readme/CONTRIBUTORS.rst
  web_pwa_oca/readme/DESCRIPTION.rst
  web_pwa_oca/readme/INSTALL.rst
  web_pwa_oca/readme/ROADMAP.rst
  web_pwa_oca/readme/USAGE.rst
  web_pwa_oca/static/description/icon.png
  web_pwa_oca/static/description/index.html
  web_pwa_oca/static/description/pwa.png
  web_pwa_oca/static/img/icons/icon-128x128.png
  web_pwa_oca/static/img/icons/icon-144x144.png
  web_pwa_oca/static/img/icons/icon-152x152.png
  web_pwa_oca/static/img/icons/icon-192x192.png
  web_pwa_oca/static/img/icons/icon-256x256.png
  web_pwa_oca/static/img/icons/icon-512x512.png
  web_pwa_oca/static/img/icons/odoo_logo.svg
  web_pwa_oca/static/src/js/pwa_manager.js
  web_pwa_oca/static/src/js/webclient.js
  web_pwa_oca/static/src/js/worker/jquery-sw-compat.js
  web_pwa_oca/static/src/js/worker/pwa.js
  web_pwa_oca/templates/assets.xml
  web_pwa_oca/tests/__init__.py
  web_pwa_oca/tests/test_web_pwa_oca_controller.py
  web_pwa_oca/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#2707 [14.0][ADD] New module web_custom_modifier
  setup/web_custom_modifier/odoo/addons/web_custom_modifier
  setup/web_custom_modifier/setup.py
  web_custom_modifier/README.rst
  web_custom_modifier/__init__.py
  web_custom_modifier/__manifest__.py
  web_custom_modifier/i18n/fr.po
  web_custom_modifier/models/__init__.py
  web_custom_modifier/models/base.py
  web_custom_modifier/models/common.py
  web_custom_modifier/models/ir_ui_view.py
  web_custom_modifier/models/web_custom_modifier.py
  web_custom_modifier/readme/CONTEXT.md
  web_custom_modifier/readme/CONTRIBUTOR.md
  web_custom_modifier/readme/DESCRIPTION.md
  web_custom_modifier/readme/ROADMAP.md
  web_custom_modifier/readme/USAGE.md
  web_custom_modifier/security/ir.model.access.csv
  web_custom_modifier/static/description/button_modifier.png
  web_custom_modifier/static/description/contact_form_type_not_selected.png
  web_custom_modifier/static/description/contact_form_without_selection_item.png
  web_custom_modifier/static/description/custom_modifier_menu.png
  web_custom_modifier/static/description/custom_widget.png
  web_custom_modifier/static/description/excluded_groups.png
  web_custom_modifier/static/description/force_save_modifier.png
  web_custom_modifier/static/description/hide_selection_item_modifier.png
  web_custom_modifier/static/description/icon.png
  web_custom_modifier/static/description/index.html
  web_custom_modifier/static/description/new_custom_modifier.png
  web_custom_modifier/static/description/number_lines_per_page_modifier.png
  web_custom_modifier/static/description/optional_modifier.png
  web_custom_modifier/static/description/optional_modifier_applied.png
  web_custom_modifier/static/description/product_form.png
  web_custom_modifier/static/description/sale_order_with_limited_sol_per_page.png
  web_custom_modifier/static/description/task_form_with_custom_widget.png
  web_custom_modifier/tests/__init__.py
  web_custom_modifier/tests/test_view_rendering.py
  web_custom_modifier/utils.py
  web_custom_modifier/views/web_custom_modifier.xml
Labels: bot is merging ⏳
