Repository OCA/web, pull requests merged in 2024-10, with the labels that each got.

#2944 [FIX] web_company_color: Colors where not shown correctly
  web_company_color/models/res_company.py
Labels: approved, bot is merging ⏳

#2949 [16.0][FW] Porting missing commits from 14.0
  .oca/oca-port/blacklist/web_notify.json
  web_notify/models/res_users.py
  web_notify/tests/test_res_users.py
Labels: approved, bot is merging ⏳

#2933 [15.0][FIX] web_notify: don't ignore actions without custom params
  web_notify/static/src/js/services/notification_services.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2950 [15.0] Update copier template
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#2948 [17.0][MIG] web_notify: Migration to 17.0
  web_notify/README.rst
  web_notify/__init__.py
  web_notify/__manifest__.py
  web_notify/i18n/da.po
  web_notify/i18n/de.po
  web_notify/i18n/es.po
  web_notify/i18n/hr.po
  web_notify/i18n/it.po
  web_notify/i18n/nl.po
  web_notify/i18n/nl_NL.po
  web_notify/i18n/pt_BR.po
  web_notify/i18n/web_notify.pot
  web_notify/i18n/zh_CN.po
  web_notify/models/__init__.py
  web_notify/models/res_users.py
  web_notify/pyproject.toml
  web_notify/readme/CONTRIBUTORS.md
  web_notify/readme/DESCRIPTION.md
  web_notify/readme/INSTALL.md
  web_notify/readme/USAGE.md
  web_notify/static/description/icon.png
  web_notify/static/description/index.html
  web_notify/static/img/notifications_screenshot.gif
  web_notify/static/img/test_notifications_demo.png
  web_notify/static/src/js/services/notification.esm.js
  web_notify/static/src/js/services/notification_services.esm.js
  web_notify/tests/__init__.py
  web_notify/tests/test_res_users.py
  web_notify/views/res_users_demo.xml
Labels: approved, bot is merging ⏳

#2957 [17.0][FIX] web_m2x_options: add fieldColor to ListMany2ManyTagsAvatarField and Many2ManyTagsAvatarField
  web_m2x_options/static/description/index.html
  web_m2x_options/static/src/components/form.esm.js
Labels: approved, bot is merging ⏳

#2958 [17.0][IMP] web_m2x_options: remove unneeded fieldColor on ListMany2ManyTagsAvatarField
  web_m2x_options/static/src/components/form.esm.js
Labels: approved, bot is merging ⏳

#2959 [17.0][FIX] web_m2x_options: add fieldColor to KanbanMany2ManyTagsAvatarField
  web_m2x_options/static/src/components/form.esm.js
Labels: approved, bot is merging ⏳

#2964 [16.0][FIX] web_advanced_search: Fixed changes from code editor not propagated
  web_advanced_search/static/src/js/DomainSelector.esm.js
Labels: approved, bot is merging ⏳

#2858 [ADD] web_widget_text_count
  setup/web_widget_text_count/odoo/addons/web_widget_text_count
  setup/web_widget_text_count/setup.py
  web_widget_text_count/README.rst
  web_widget_text_count/__init__.py
  web_widget_text_count/__manifest__.py
  web_widget_text_count/readme/CONTRIBUTORS.rst
  web_widget_text_count/readme/DESCRIPTION.rst
  web_widget_text_count/readme/ROADMAP.rst
  web_widget_text_count/readme/USAGE.rst
  web_widget_text_count/static/description/index.html
  web_widget_text_count/static/src/js/fields_text_count.js
  web_widget_text_count/static/src/scss/field_text_count.scss
  web_widget_text_count/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#2969 [17.0][MIG] web_timeline: Migration to version 17.0
  web_timeline/README.rst
  web_timeline/__init__.py
  web_timeline/__manifest__.py
  web_timeline/demo/ir_cron_view.xml
  web_timeline/i18n/de.po
  web_timeline/i18n/es.po
  web_timeline/i18n/fa.po
  web_timeline/i18n/fr.po
  web_timeline/i18n/he.po
  web_timeline/i18n/hr.po
  web_timeline/i18n/it.po
  web_timeline/i18n/nl_NL.po
  web_timeline/i18n/pt.po
  web_timeline/i18n/pt_BR.po
  web_timeline/i18n/tr.po
  web_timeline/i18n/web_timeline.pot
  web_timeline/i18n/zh_CN.po
  web_timeline/models/__init__.py
  web_timeline/models/ir_action.py
  web_timeline/models/ir_ui_view.py
  web_timeline/pyproject.toml
  web_timeline/readme/CONFIGURE.md
  web_timeline/readme/CONTRIBUTORS.md
  web_timeline/readme/DESCRIPTION.md
  web_timeline/readme/ROADMAP.md
  web_timeline/readme/USAGE.md
  web_timeline/static/description/icon.png
  web_timeline/static/description/index.html
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.css
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js
  web_timeline/static/src/views/timeline/timeline_arch_parser.esm.js
  web_timeline/static/src/views/timeline/timeline_canvas.esm.js
  web_timeline/static/src/views/timeline/timeline_canvas.scss
  web_timeline/static/src/views/timeline/timeline_controller.esm.js
  web_timeline/static/src/views/timeline/timeline_controller.xml
  web_timeline/static/src/views/timeline/timeline_model.esm.js
  web_timeline/static/src/views/timeline/timeline_renderer.esm.js
  web_timeline/static/src/views/timeline/timeline_renderer.xml
  web_timeline/static/src/views/timeline/timeline_view.esm.js
  web_timeline/static/src/views/timeline/timeline_view.scss
  web_timeline/static/tests/helpers.esm.js
  web_timeline/static/tests/web_timeline_arch_parser_tests.esm.js
  web_timeline/static/tests/web_timeline_view_tests.esm.js
  web_timeline/tests/__init__.py
  web_timeline/tests/test_web_timeline.py
Labels: approved, bot is merging ⏳

#2956 [18.0][MIG] web_notify: Migration to 18.0
  web_notify/README.rst
  web_notify/__init__.py
  web_notify/__manifest__.py
  web_notify/i18n/da.po
  web_notify/i18n/de.po
  web_notify/i18n/es.po
  web_notify/i18n/hr.po
  web_notify/i18n/it.po
  web_notify/i18n/nl.po
  web_notify/i18n/nl_NL.po
  web_notify/i18n/pt_BR.po
  web_notify/i18n/web_notify.pot
  web_notify/i18n/zh_CN.po
  web_notify/models/__init__.py
  web_notify/models/res_users.py
  web_notify/pyproject.toml
  web_notify/readme/CONTRIBUTORS.md
  web_notify/readme/CREDITS.md
  web_notify/readme/DESCRIPTION.md
  web_notify/readme/INSTALL.md
  web_notify/readme/USAGE.md
  web_notify/static/description/icon.png
  web_notify/static/description/index.html
  web_notify/static/img/notifications_screenshot.gif
  web_notify/static/img/test_notifications_demo.png
  web_notify/static/src/js/services/notification.esm.js
  web_notify/static/src/js/services/notification_services.esm.js
  web_notify/tests/__init__.py
  web_notify/tests/test_res_users.py
  web_notify/views/res_users_demo.xml
Labels: approved, bot is merging ⏳

#2938 [MIG] web_select_all_companies: Backporting from 15.0 to 14.0
  setup/web_select_all_companies/odoo/addons/web_select_all_companies
  setup/web_select_all_companies/setup.py
  web_select_all_companies/README.rst
  web_select_all_companies/__init__.py
  web_select_all_companies/__manifest__.py
  web_select_all_companies/i18n/fr.po
  web_select_all_companies/i18n/web_select_all_companies.pot
  web_select_all_companies/readme/CONTRIBUTORS.rst
  web_select_all_companies/readme/DESCRIPTION.rst
  web_select_all_companies/static/description/icon.png
  web_select_all_companies/static/description/index.html
  web_select_all_companies/static/description/select_all_companies.gif
  web_select_all_companies/static/src/js/switch_all_company_menu.js
  web_select_all_companies/static/src/scss/switch_all_company_menu.scss
  web_select_all_companies/static/src/xml/switch_all_company_menu.xml
  web_select_all_companies/views/web_select_all_companies.xml
Labels: approved, ready to merge, bot is merging ⏳

#2854 [14.0][FIX] web_edit_user_filter: Modified search facet for field type
  web_edit_user_filter/static/src/js/backend.js
  web_edit_user_filter/static/src/xml/backend.xml
Labels: approved, ready to merge, bot is merging ⏳

#2972 [17.0][IMP] web_timeline: Update vis-timeline-graph2d lib: 7.7.0 -> 7.7.3
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.css
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js
Labels: approved, bot is merging ⏳
