Repository OCA/web, pull requests merged in 2024-09, with the labels that each got.

#2859 [15.0][REM] web_widget_remote_measure: Moved to OCA/stock-weighing
  setup/web_widget_remote_measure/odoo/addons/web_widget_remote_measure
  setup/web_widget_remote_measure/setup.py
  web_widget_remote_measure/README.rst
  web_widget_remote_measure/__init__.py
  web_widget_remote_measure/__manifest__.py
  web_widget_remote_measure/i18n/es.po
  web_widget_remote_measure/i18n/web_widget_remote_measure.pot
  web_widget_remote_measure/models/__init__.py
  web_widget_remote_measure/models/remote_measure_device.py
  web_widget_remote_measure/models/res_users.py
  web_widget_remote_measure/readme/CONFIGURE.rst
  web_widget_remote_measure/readme/CONTRIBUTORS.rst
  web_widget_remote_measure/readme/DESCRIPTION.rst
  web_widget_remote_measure/readme/ROADMAP.rst
  web_widget_remote_measure/readme/USAGE.rst
  web_widget_remote_measure/security/ir.model.access.csv
  web_widget_remote_measure/static/description/icon.png
  web_widget_remote_measure/static/description/index.html
  web_widget_remote_measure/static/src/js/remote_measure_device_kanban_widget.esm.js
  web_widget_remote_measure/static/src/js/remote_measure_widget.esm.js
  web_widget_remote_measure/static/src/scss/remote_measure_widget.scss
  web_widget_remote_measure/static/src/xml/measure_device_status.xml
  web_widget_remote_measure/views/remote_measure_device_views.xml
  web_widget_remote_measure/views/res_users_views.xml
Labels: approved, bot is merging ⏳

#2921 [17.0][FIX] web_m2x_options: Error when installing employee module
  web_m2x_options/static/src/components/form.esm.js
Labels: bot is merging ⏳

#2789 [15.0][IMP] web_notify: action button name and close
  web_notify/README.rst
  web_notify/readme/USAGE.rst
  web_notify/static/description/index.html
  web_notify/static/description/notifications_screenshot.gif
  web_notify/static/img/notifications_screenshot.gif
  web_notify/static/img/test_notifications_demo.png
  web_notify/static/src/js/services/notification_services.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2932 [16.0][IMP] web_notify: action button name and close
  web_notify/README.rst
  web_notify/models/res_users.py
  web_notify/readme/USAGE.rst
  web_notify/static/description/index.html
  web_notify/static/description/notifications_screenshot.gif
  web_notify/static/img/notifications_screenshot.gif
  web_notify/static/img/test_notifications_demo.png
  web_notify/static/src/js/services/notification_services.esm.js
Labels: approved, bot is merging ⏳

#2936 [16.0][ADD] web_editor_class_selector: New module
  setup/web_editor_class_selector/odoo/addons/web_editor_class_selector
  setup/web_editor_class_selector/setup.py
  web_editor_class_selector/README.rst
  web_editor_class_selector/__init__.py
  web_editor_class_selector/__manifest__.py
  web_editor_class_selector/demo/web_editor_class_demo.xml
  web_editor_class_selector/models/__init__.py
  web_editor_class_selector/models/web_editor_class.py
  web_editor_class_selector/readme/DESCRIPTION.rst
  web_editor_class_selector/readme/ROADMAP.rst
  web_editor_class_selector/readme/USAGE.rst
  web_editor_class_selector/security/ir.model.access.csv
  web_editor_class_selector/static/description/index.html
  web_editor_class_selector/static/src/js/backend/html_field.esm.js
  web_editor_class_selector/static/src/js/odoo-editor/OdooEditor.esm.js
  web_editor_class_selector/static/src/js/odoo-editor/commands.esm.js
  web_editor_class_selector/static/src/js/odoo-editor/utils.esm.js
  web_editor_class_selector/static/src/js/wysiwyg/wysiwyg.esm.js
  web_editor_class_selector/static/src/scss/demo_styles.scss
  web_editor_class_selector/static/src/xml/web_editor.xml
  web_editor_class_selector/views/menus.xml
  web_editor_class_selector/views/web_editor_class_views.xml
Labels: approved, bot is merging ⏳

#2774 [16.0][IMP] web_timeline: Handle inverted date ranges
  web_timeline/static/src/js/timeline_renderer.js
Labels: approved, bot is merging ⏳

#2778 [16.0][FIX] web_timeline: Redraw issues with initial mode
  web_timeline/static/src/js/timeline_renderer.js
  web_timeline/static/src/js/timeline_view.js
Labels: approved, bot is merging ⏳

#2791 [16.0][IMP] web_timeline: Follow create/edit/delete attrs
  web_timeline/readme/ROADMAP.rst
  web_timeline/static/src/js/timeline_controller.esm.js
  web_timeline/static/src/js/timeline_renderer.js
  web_timeline/static/src/js/timeline_view.js
Labels: approved, ready to merge, bot is merging ⏳

#2939 [16.0][FIX] web_editor_class_selector: Avoid errors when custom CSS class is not present
  web_editor_class_selector/static/src/js/odoo-editor/OdooEditor.esm.js
Labels: bot is merging ⏳
