Repository OCA/web, pull requests merged in 2024-06, with the labels that each got.

#2756 [17.0][MIG] web_widget_x2many_2d_matrix: Migration to 17.0
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/__init__.py
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/i18n/ar.po
  web_widget_x2many_2d_matrix/i18n/de.po
  web_widget_x2many_2d_matrix/i18n/es.po
  web_widget_x2many_2d_matrix/i18n/fi.po
  web_widget_x2many_2d_matrix/i18n/fr.po
  web_widget_x2many_2d_matrix/i18n/hr.po
  web_widget_x2many_2d_matrix/i18n/it.po
  web_widget_x2many_2d_matrix/i18n/lt.po
  web_widget_x2many_2d_matrix/i18n/nl.po
  web_widget_x2many_2d_matrix/i18n/nl_NL.po
  web_widget_x2many_2d_matrix/i18n/pt_BR.po
  web_widget_x2many_2d_matrix/i18n/sl.po
  web_widget_x2many_2d_matrix/i18n/tr.po
  web_widget_x2many_2d_matrix/i18n/web_widget_x2many_2d_matrix.pot
  web_widget_x2many_2d_matrix/i18n/zh_CN.po
  web_widget_x2many_2d_matrix/pyproject.toml
  web_widget_x2many_2d_matrix/readme/CONTRIBUTORS.md
  web_widget_x2many_2d_matrix/readme/DESCRIPTION.md
  web_widget_x2many_2d_matrix/readme/HISTORY.md
  web_widget_x2many_2d_matrix/readme/ROADMAP.md
  web_widget_x2many_2d_matrix/readme/USAGE.md
  web_widget_x2many_2d_matrix/static/description/icon.png
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/description/screenshot.png
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.esm.js
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.scss
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.xml
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.xml
Labels: approved, ready to merge, bot is merging ⏳

#2843 [16.0][FIX] web_dialog_size: Fixes on legacy Dialogs
  web_dialog_size/static/src/js/web_dialog_size.js
  web_dialog_size/static/src/xml/web_dialog_size.xml
Labels: approved, bot is merging ⏳

#2809 [16.0][MIG] web_widget_one2many_tree_line_duplicate: Migration to 16.0
  setup/web_widget_one2many_tree_line_duplicate/odoo/addons/web_widget_one2many_tree_line_duplicate
  setup/web_widget_one2many_tree_line_duplicate/setup.py
  web_widget_one2many_tree_line_duplicate/README.rst
  web_widget_one2many_tree_line_duplicate/__init__.py
  web_widget_one2many_tree_line_duplicate/__manifest__.py
  web_widget_one2many_tree_line_duplicate/i18n/web_widget_one2many_tree_line_duplicate.pot
  web_widget_one2many_tree_line_duplicate/readme/CONTRIBUTORS.rst
  web_widget_one2many_tree_line_duplicate/readme/DESCRIPTION.rst
  web_widget_one2many_tree_line_duplicate/readme/ROADMAP.rst
  web_widget_one2many_tree_line_duplicate/readme/USAGE.rst
  web_widget_one2many_tree_line_duplicate/static/description/icon.png
  web_widget_one2many_tree_line_duplicate/static/description/index.html
  web_widget_one2many_tree_line_duplicate/static/src/basic_relational_model/basic_relational_model.esm.js
  web_widget_one2many_tree_line_duplicate/static/src/legacy/basic_model/basic_model.js
  web_widget_one2many_tree_line_duplicate/static/src/list/list_renderer.esm.js
  web_widget_one2many_tree_line_duplicate/static/src/list/list_renderer.xml
Labels: bot is merging ⏳

#2846 [17.0][MIG] web_widget_bokeh_chart
  requirements.txt
  web_widget_bokeh_chart/README.rst
  web_widget_bokeh_chart/__init__.py
  web_widget_bokeh_chart/__manifest__.py
  web_widget_bokeh_chart/i18n/it.po
  web_widget_bokeh_chart/i18n/web_widget_bokeh_chart.pot
  web_widget_bokeh_chart/i18n/zh_CN.po
  web_widget_bokeh_chart/pyproject.toml
  web_widget_bokeh_chart/readme/CONTRIBUTORS.md
  web_widget_bokeh_chart/readme/CREDITS.md
  web_widget_bokeh_chart/readme/DESCRIPTION.md
  web_widget_bokeh_chart/readme/INSTALL.md
  web_widget_bokeh_chart/readme/ROADMAP.md
  web_widget_bokeh_chart/readme/USAGE.md
  web_widget_bokeh_chart/static/description/example.png
  web_widget_bokeh_chart/static/description/icon.png
  web_widget_bokeh_chart/static/description/index.html
  web_widget_bokeh_chart/static/src/js/web_widget_bokeh_chart.esm.js
  web_widget_bokeh_chart/static/src/js/web_widget_bokeh_json_chart.esm.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-api-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-gl-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-mathjax-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-tables-3.4.1.min.js
  web_widget_bokeh_chart/static/src/lib/bokeh/bokeh-widgets-3.4.1.min.js
  web_widget_bokeh_chart/static/src/xml/bokeh.xml
Labels: approved, bot is merging ⏳

#2852 [17.0][FIX] web_favicon: Fix when having more than one company and one of them don't have a favicon set
  web_favicon/models/res_company.py
Labels: approved, bot is merging ⏳

#2857 [15.0][FIX] web_filter_header_button: compatibility issues
  web_filter_header_button/static/src/control_panel/control_panel.xml
Labels: approved, bot is merging ⏳

#2844 [15.0][MIG] web_widget_one2many_tree_line_duplicate
  setup/web_widget_one2many_tree_line_duplicate/odoo/addons/web_widget_one2many_tree_line_duplicate
  setup/web_widget_one2many_tree_line_duplicate/setup.py
  web_widget_one2many_tree_line_duplicate/README.rst
  web_widget_one2many_tree_line_duplicate/__init__.py
  web_widget_one2many_tree_line_duplicate/__manifest__.py
  web_widget_one2many_tree_line_duplicate/i18n/web_widget_one2many_tree_line_duplicate.pot
  web_widget_one2many_tree_line_duplicate/readme/CONTRIBUTORS.rst
  web_widget_one2many_tree_line_duplicate/readme/DESCRIPTION.rst
  web_widget_one2many_tree_line_duplicate/readme/ROADMAP.rst
  web_widget_one2many_tree_line_duplicate/readme/USAGE.rst
  web_widget_one2many_tree_line_duplicate/static/description/icon.png
  web_widget_one2many_tree_line_duplicate/static/description/index.html
  web_widget_one2many_tree_line_duplicate/static/src/list/list_renderer.esm.js
  web_widget_one2many_tree_line_duplicate/static/src/list/list_renderer.scss
Labels: approved, ready to merge, bot is merging ⏳

#2862 [16.0][FIX] web_responsive: Remove view that does not allow zooming in mobile view
  web_responsive/__manifest__.py
  web_responsive/views/web.xml
Labels: approved, bot is merging ⏳
