Repository OCA/web, pull requests merged in 2024-01, with the labels that each got.

#2683 [FIX][16.0] web_responsive: broken delete message confirm dialog UI
  web_responsive/static/src/components/attachment_viewer/attachment_viewer.scss
Labels: approved, bot is merging ⏳

#2705 [16.0][FIX] web_widget_x2many_2d_matrix: cells with no data error
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#2697 [15.0][IMP] web_notify html format
  web_notify/models/res_users.py
  web_notify/static/src/js/services/notification_services.esm.js
  web_notify/tests/test_res_users.py
Labels: approved, ready to merge, bot is merging ⏳

#2716 [DOCS] web_touchscreen: add screenshot
  web_touchscreen/README.rst
  web_touchscreen/readme/DESCRIPTION.md
  web_touchscreen/static/description/index.html
Labels: needs review, bot is merging ⏳

#2614 [14.0][ADD] web_assets_warmup
  setup/web_assets_warmup/odoo/addons/web_assets_warmup
  setup/web_assets_warmup/setup.py
  web_assets_warmup/README.rst
  web_assets_warmup/__init__.py
  web_assets_warmup/__manifest__.py
  web_assets_warmup/data/ir_cron.xml
  web_assets_warmup/hooks.py
  web_assets_warmup/models/__init__.py
  web_assets_warmup/models/ir_actions_report.py
  web_assets_warmup/readme/CONTRIBUTORS.rst
  web_assets_warmup/readme/DESCRIPTION.rst
  web_assets_warmup/static/description/index.html
Labels: bot is merging ⏳

#2274 [15.0][ADD] web_hide_user_menu_item
  setup/web_hide_user_menu_item/odoo/addons/web_hide_user_menu_item
  setup/web_hide_user_menu_item/setup.py
  web_hide_user_menu_item/README.rst
  web_hide_user_menu_item/__init__.py
  web_hide_user_menu_item/__manifest__.py
  web_hide_user_menu_item/readme/CONTRIBUTORS.rst
  web_hide_user_menu_item/readme/DESCRIPTION.rst
  web_hide_user_menu_item/readme/USAGE.rst
  web_hide_user_menu_item/static/description/index.html
  web_hide_user_menu_item/static/img/userscreen.png
  web_hide_user_menu_item/static/src/webclient/user_menu/user_menu.xml
Labels: bot is merging ⏳

#2718 [FIX] web_widget_numeric_step: restore tab navigation
  web_widget_numeric_step/static/src/numeric_step.xml
Labels: needs review, approved, bot is merging ⏳

#2389 [16.0][MIG] web_ir_actions_act_window_message: Migration to 16.0
  setup/web_ir_actions_act_window_message/odoo/addons/web_ir_actions_act_window_message
  setup/web_ir_actions_act_window_message/setup.py
  web_ir_actions_act_window_message/README.rst
  web_ir_actions_act_window_message/__init__.py
  web_ir_actions_act_window_message/__manifest__.py
  web_ir_actions_act_window_message/i18n/ar.po
  web_ir_actions_act_window_message/i18n/de.po
  web_ir_actions_act_window_message/i18n/es.po
  web_ir_actions_act_window_message/i18n/eu.po
  web_ir_actions_act_window_message/i18n/fi.po
  web_ir_actions_act_window_message/i18n/fr.po
  web_ir_actions_act_window_message/i18n/hr.po
  web_ir_actions_act_window_message/i18n/it.po
  web_ir_actions_act_window_message/i18n/nl.po
  web_ir_actions_act_window_message/i18n/nl_NL.po
  web_ir_actions_act_window_message/i18n/pt.po
  web_ir_actions_act_window_message/i18n/pt_BR.po
  web_ir_actions_act_window_message/i18n/ro.po
  web_ir_actions_act_window_message/i18n/sl.po
  web_ir_actions_act_window_message/i18n/tr.po
  web_ir_actions_act_window_message/i18n/web_ir_actions_act_window_message.pot
  web_ir_actions_act_window_message/models/__init__.py
  web_ir_actions_act_window_message/models/ir_actions.py
  web_ir_actions_act_window_message/readme/CONTRIBUTORS.rst
  web_ir_actions_act_window_message/readme/DESCRIPTION.rst
  web_ir_actions_act_window_message/readme/ROADMAP.rst
  web_ir_actions_act_window_message/readme/USAGE.rst
  web_ir_actions_act_window_message/security/ir.model.access.csv
  web_ir_actions_act_window_message/static/description/icon.png
  web_ir_actions_act_window_message/static/description/index.html
  web_ir_actions_act_window_message/static/src/js/web_ir_actions_act_window_message.esm.js
  web_ir_actions_act_window_message/static/src/xml/web_ir_actions_act_window_message.xml
Labels: approved, bot is merging ⏳

#2708 [17.0][MIG] web_no_bubble
  web_no_bubble/README.rst
  web_no_bubble/__init__.py
  web_no_bubble/__manifest__.py
  web_no_bubble/i18n/es.po
  web_no_bubble/i18n/fr_FR.po
  web_no_bubble/i18n/hr.po
  web_no_bubble/i18n/it.po
  web_no_bubble/i18n/web_no_bubble.pot
  web_no_bubble/i18n/zh_CN.po
  web_no_bubble/pyproject.toml
  web_no_bubble/readme/CONTRIBUTORS.md
  web_no_bubble/readme/DESCRIPTION.md
  web_no_bubble/static/description/icon.png
  web_no_bubble/static/description/index.html
  web_no_bubble/static/src/css/web_no_bubble.scss
Labels: approved, bot is merging ⏳

#2728 [14.0][FIX] web_field_required_invisible_manager: decode only bytes
  web_field_required_invisible_manager/models/models.py
  web_field_required_invisible_manager/tests/test_web_field_required_invisible_manager.py
Labels: bot is merging ⏳

#2729 [FIX] web_widget_numeric_step: list view column min width
  web_widget_numeric_step/static/src/numeric_step.scss
Labels: approved, bot is merging ⏳

#2361 [15.0][FIX] web_widget_x2many_2d_matrix: fix totals option
  web_widget_x2many_2d_matrix/static/src/js/widget_x2many_2d_matrix.js
Labels: bot is merging ⏳

#2325 [16.0][MIG] web_dashboard_tile (from 15.0)
  setup/web_dashboard_tile/odoo/addons/web_dashboard_tile
  setup/web_dashboard_tile/setup.py
  web_dashboard_tile/README.rst
  web_dashboard_tile/__init__.py
  web_dashboard_tile/__manifest__.py
  web_dashboard_tile/demo/tile_category.xml
  web_dashboard_tile/demo/tile_tile.xml
  web_dashboard_tile/i18n/fr.po
  web_dashboard_tile/i18n/web_dashboard_tile.pot
  web_dashboard_tile/models/__init__.py
  web_dashboard_tile/models/tile_category.py
  web_dashboard_tile/models/tile_tile.py
  web_dashboard_tile/readme/CONFIGURE.rst
  web_dashboard_tile/readme/CONTRIBUTORS.rst
  web_dashboard_tile/readme/DESCRIPTION.rst
  web_dashboard_tile/readme/ROADMAP.rst
  web_dashboard_tile/readme/USAGE.rst
  web_dashboard_tile/security/ir.model.access.csv
  web_dashboard_tile/security/ir_rule.xml
  web_dashboard_tile/static/description/icon.png
  web_dashboard_tile/static/description/index.html
  web_dashboard_tile/static/description/tile_category_form.png
  web_dashboard_tile/static/description/tile_tile_2_tree_view.png
  web_dashboard_tile/static/description/tile_tile_form.png
  web_dashboard_tile/static/description/tile_tile_form_secondary_value.png
  web_dashboard_tile/static/description/tile_tile_kanban.png
  web_dashboard_tile/static/src/css/web_dashboard_tile.css
  web_dashboard_tile/tests/__init__.py
  web_dashboard_tile/tests/test_tile.py
  web_dashboard_tile/views/menu.xml
  web_dashboard_tile/views/tile_category.xml
  web_dashboard_tile/views/tile_tile.xml
Labels: approved, bot is merging ⏳
