Repository OCA/web, pull requests merged in 2024-11, with the labels that each got.

#2818 [16.0][FIX] web_calendar_slot_duration: fixing behavior on slot duration
  web_calendar_slot_duration/README.rst
  web_calendar_slot_duration/readme/CONFIGURE.rst
  web_calendar_slot_duration/static/description/index.html
  web_calendar_slot_duration/static/src/js/calendar_common_renderer.esm.js
  web_calendar_slot_duration/static/src/js/calendar_model.esm.js
Labels: bot is merging ⏳

#2963 [18.0][MIG] web_tree_dynamic_colored_field: Migration to 18.0
  web_tree_dynamic_colored_field/README.rst
  web_tree_dynamic_colored_field/__init__.py
  web_tree_dynamic_colored_field/__manifest__.py
  web_tree_dynamic_colored_field/demo/res_users.xml
  web_tree_dynamic_colored_field/i18n/es.po
  web_tree_dynamic_colored_field/i18n/fi.po
  web_tree_dynamic_colored_field/i18n/fr.po
  web_tree_dynamic_colored_field/i18n/it.po
  web_tree_dynamic_colored_field/i18n/nl_NL.po
  web_tree_dynamic_colored_field/i18n/sl.po
  web_tree_dynamic_colored_field/i18n/web_tree_dynamic_colored_field.pot
  web_tree_dynamic_colored_field/i18n/zh_CN.po
  web_tree_dynamic_colored_field/pyproject.toml
  web_tree_dynamic_colored_field/readme/CONTRIBUTORS.md
  web_tree_dynamic_colored_field/readme/CREDITS.md
  web_tree_dynamic_colored_field/readme/DESCRIPTION.md
  web_tree_dynamic_colored_field/readme/ROADMAP.md
  web_tree_dynamic_colored_field/readme/USAGE.md
  web_tree_dynamic_colored_field/static/description/icon.png
  web_tree_dynamic_colored_field/static/description/index.html
  web_tree_dynamic_colored_field/static/src/js/list_renderer.esm.js
  web_tree_dynamic_colored_field/static/src/xml/list.xml
Labels: approved, ready to merge, bot is merging ⏳

#2978 [17.0][FIX] web_responsive: Fix test related to ir.actions.act_window
  web_responsive/tests/test_res_users.py
Labels: approved, bot is merging ⏳

#2974 [18.0] help on web repo to apply last pre-commit changes
  .copier-answers.yml
  .eslintrc.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  eslint.config.cjs
  prettier.config.cjs
  web_environment_ribbon/static/src/components/environment_ribbon/ribbon.esm.js
  web_notify/views/res_users_demo.xml
Labels: approved, ready to merge, bot is merging ⏳

#2983 [FIX] web_advanced_search: display label name in partners search
  web_advanced_search/static/src/search/filter_menu/custom_filter_item.esm.js
Labels: approved, bot is merging ⏳

#2988 [16.0][FIX] web_responsive: avoid break style of Sales Teams
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: approved, bot is merging ⏳

#2587 [16.0][MIG] web_m2x_options_manager : Migrate to 16.0
  setup/web_m2x_options_manager/odoo/addons/web_m2x_options_manager
  setup/web_m2x_options_manager/setup.py
  web_m2x_options_manager/README.rst
  web_m2x_options_manager/__init__.py
  web_m2x_options_manager/__manifest__.py
  web_m2x_options_manager/demo/res_partner_demo_view.xml
  web_m2x_options_manager/i18n/web_m2x_options_manager.pot
  web_m2x_options_manager/models/__init__.py
  web_m2x_options_manager/models/ir_model.py
  web_m2x_options_manager/models/ir_ui_view.py
  web_m2x_options_manager/models/m2x_create_edit_option.py
  web_m2x_options_manager/readme/CONTRIBUTORS.rst
  web_m2x_options_manager/readme/DESCRIPTION.rst
  web_m2x_options_manager/readme/USAGE.rst
  web_m2x_options_manager/security/ir.model.access.csv
  web_m2x_options_manager/static/description/icon.png
  web_m2x_options_manager/static/description/index.html
  web_m2x_options_manager/tests/__init__.py
  web_m2x_options_manager/tests/test_m2x_create_edit_option.py
  web_m2x_options_manager/views/ir_model.xml
Labels: bot is merging ⏳

#2989 [16.0][ADD] web_widget_progressbar_gradient
  setup/web_widget_progressbar_gradient/odoo/addons/web_widget_progressbar_gradient
  setup/web_widget_progressbar_gradient/setup.py
  web_widget_progressbar_gradient/README.rst
  web_widget_progressbar_gradient/__init__.py
  web_widget_progressbar_gradient/__manifest__.py
  web_widget_progressbar_gradient/readme/CONTRIBUTORS.md
  web_widget_progressbar_gradient/readme/DESCRIPTION.md
  web_widget_progressbar_gradient/readme/ROADMAP.md
  web_widget_progressbar_gradient/readme/USAGE.md
  web_widget_progressbar_gradient/static/description/icon.png
  web_widget_progressbar_gradient/static/description/index.html
  web_widget_progressbar_gradient/static/description/progressbar_gradient.png
  web_widget_progressbar_gradient/static/description/progressbar_gradient_inverse.png
  web_widget_progressbar_gradient/static/src/js/progressbar.esm.js
  web_widget_progressbar_gradient/static/src/scss/progressbar.scss
  web_widget_progressbar_gradient/static/src/xml/progressbar.xml
Labels: approved, bot is merging ⏳

#2993 [16.0][MIG] web_time_range_menu_custom: Migration to 16.0
  setup/web_time_range_menu_custom/odoo/addons/web_time_range_menu_custom
  setup/web_time_range_menu_custom/setup.py
  web_time_range_menu_custom/README.rst
  web_time_range_menu_custom/__init__.py
  web_time_range_menu_custom/__manifest__.py
  web_time_range_menu_custom/i18n/es.po
  web_time_range_menu_custom/i18n/web_time_range_menu_custom.pot
  web_time_range_menu_custom/readme/CONTRIBUTORS.rst
  web_time_range_menu_custom/readme/DESCRIPTION.rst
  web_time_range_menu_custom/readme/USAGE.rst
  web_time_range_menu_custom/static/description/custom_period_option.png
  web_time_range_menu_custom/static/description/icon.png
  web_time_range_menu_custom/static/description/index.html
  web_time_range_menu_custom/static/src/js/comparison_menu.esm.js
  web_time_range_menu_custom/static/src/js/date_selector.esm.js
  web_time_range_menu_custom/static/src/js/dates.esm.js
  web_time_range_menu_custom/static/src/js/filter_menu.esm.js
  web_time_range_menu_custom/static/src/scss/web_time_range_menu_custom.scss
  web_time_range_menu_custom/static/src/xml/comparison_menu.xml
  web_time_range_menu_custom/static/src/xml/date_selector.xml
  web_time_range_menu_custom/static/src/xml/filter_menu.xml
Labels: approved, bot is merging ⏳

#2991 [17.0][MIG] web_editor_class_selector: Migration to version 17.0
  web_editor_class_selector/README.rst
  web_editor_class_selector/__init__.py
  web_editor_class_selector/__manifest__.py
  web_editor_class_selector/demo/web_editor_class_demo.xml
  web_editor_class_selector/i18n/it.po
  web_editor_class_selector/i18n/web_editor_class_selector.pot
  web_editor_class_selector/models/__init__.py
  web_editor_class_selector/models/web_editor_class.py
  web_editor_class_selector/pyproject.toml
  web_editor_class_selector/readme/DESCRIPTION.md
  web_editor_class_selector/readme/ROADMAP.md
  web_editor_class_selector/readme/USAGE.md
  web_editor_class_selector/security/ir.model.access.csv
  web_editor_class_selector/static/description/icon.png
  web_editor_class_selector/static/description/index.html
  web_editor_class_selector/static/src/js/backend/html_field.esm.js
  web_editor_class_selector/static/src/js/odoo-editor/OdooEditor.esm.js
  web_editor_class_selector/static/src/js/odoo-editor/commands.esm.js
  web_editor_class_selector/static/src/js/odoo-editor/toolbar.esm.js
  web_editor_class_selector/static/src/js/odoo-editor/utils.esm.js
  web_editor_class_selector/static/src/js/wysiwyg/wysiwyg.esm.js
  web_editor_class_selector/static/src/scss/demo_styles.scss
  web_editor_class_selector/static/src/xml/web_editor.xml
  web_editor_class_selector/views/menus.xml
  web_editor_class_selector/views/web_editor_class_views.xml
Labels: approved, bot is merging ⏳

#3005 [18.0][MIG] web_pivot_computed_measure: Migration to 18.0
  test-requirements.txt
  web_pivot_computed_measure.zip
  web_pivot_computed_measure/README.rst
  web_pivot_computed_measure/__init__.py
  web_pivot_computed_measure/__manifest__.py
  web_pivot_computed_measure/i18n/ca.po
  web_pivot_computed_measure/i18n/es.po
  web_pivot_computed_measure/i18n/it.po
  web_pivot_computed_measure/i18n/web_pivot_computed_measure.pot
  web_pivot_computed_measure/pyproject.toml
  web_pivot_computed_measure/readme/CONTRIBUTORS.md
  web_pivot_computed_measure/readme/DESCRIPTION.md
  web_pivot_computed_measure/readme/ROADMAP.md
  web_pivot_computed_measure/readme/USAGE.md
  web_pivot_computed_measure/static/description/icon.png
  web_pivot_computed_measure/static/description/index.html
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.esm.js
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.scss
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.xml
  web_pivot_computed_measure/static/src/helpers/utils.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_controller.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_model.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_renderer.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_view.xml
  web_pivot_computed_measure/static/src/report_view_measures/report_view_measures.esm.js
  web_pivot_computed_measure/static/src/report_view_measures/report_view_measures.xml
  web_pivot_computed_measure/static/src/test/test.esm.js
  web_pivot_computed_measure/tests/__init__.py
  web_pivot_computed_measure/tests/res_users_fake.py
  web_pivot_computed_measure/tests/test_ui_pivot.py
Labels: approved, bot is merging ⏳
