Repository OCA/web, pull requests merged in 2024-05, with the labels that each got.

#2723 [17.0][MIG] web_remember_tree_column_width
  web_remember_tree_column_width/README.rst
  web_remember_tree_column_width/__init__.py
  web_remember_tree_column_width/__manifest__.py
  web_remember_tree_column_width/i18n/it.po
  web_remember_tree_column_width/i18n/web_remember_tree_column_width.pot
  web_remember_tree_column_width/pyproject.toml
  web_remember_tree_column_width/readme/CONTRIBUTORS.md
  web_remember_tree_column_width/readme/CREDITS.md
  web_remember_tree_column_width/readme/DESCRIPTION.md
  web_remember_tree_column_width/static/description/icon.png
  web_remember_tree_column_width/static/description/index.html
  web_remember_tree_column_width/static/src/js/list_renderer.esm.js
  web_remember_tree_column_width/static/src/scss/main.scss
Labels: approved, ready to merge, bot is merging ⏳

#2815 [17.0][MIG] Migrate web_widget_plotly_chart
  requirements.txt
  web_widget_plotly_chart/README.rst
  web_widget_plotly_chart/__init__.py
  web_widget_plotly_chart/__manifest__.py
  web_widget_plotly_chart/i18n/ca.po
  web_widget_plotly_chart/i18n/da.po
  web_widget_plotly_chart/i18n/es.po
  web_widget_plotly_chart/i18n/it.po
  web_widget_plotly_chart/i18n/pt_BR.po
  web_widget_plotly_chart/i18n/web_widget_plotly_chart.pot
  web_widget_plotly_chart/pyproject.toml
  web_widget_plotly_chart/readme/CONTRIBUTORS.md
  web_widget_plotly_chart/readme/CREDITS.md
  web_widget_plotly_chart/readme/DESCRIPTION.md
  web_widget_plotly_chart/readme/INSTALL.md
  web_widget_plotly_chart/readme/USAGE.md
  web_widget_plotly_chart/static/description/example.png
  web_widget_plotly_chart/static/description/icon.png
  web_widget_plotly_chart/static/description/index.html
  web_widget_plotly_chart/static/src/js/widget_plotly.esm.js
  web_widget_plotly_chart/static/src/js/widget_plotly.xml
  web_widget_plotly_chart/static/src/lib/plotly/plotly-2.32.0.min.js
Labels: approved, ready to merge, bot is merging ⏳

#2720 [16.0][IMP] web_remember_tree_column_width: adjust SCSS selector
  web_remember_tree_column_width/static/src/scss/main.scss
Labels: approved, bot is merging ⏳

#2026 [12.0][FIX]web_widget_digitized_signature:Respect custom width-height set f…
  web_widget_digitized_signature/static/src/js/digital_sign.js
  web_widget_digitized_signature/views/web_digital_sign_view.xml
Labels: bot is merging ⏳

#2821 [15.0][IMP] web_dialog_size: hide restore button when opening dialog
  web_dialog_size/README.rst
  web_dialog_size/readme/CONTRIBUTORS.rst
  web_dialog_size/static/description/index.html
  web_dialog_size/static/src/js/web_dialog_size.js
Labels: approved, bot is merging ⏳

#2094 [15.0][MIG] web_widget_char_size: Migration to 15.0
  setup/web_widget_char_size/odoo/addons/web_widget_char_size
  setup/web_widget_char_size/setup.py
  web_widget_char_size/README.rst
  web_widget_char_size/__init__.py
  web_widget_char_size/__manifest__.py
  web_widget_char_size/i18n/web_widget_char_size.pot
  web_widget_char_size/readme/CONTRIBUTERS.rst
  web_widget_char_size/readme/DESCRIPTION.rst
  web_widget_char_size/static/description/icon.png
  web_widget_char_size/static/description/index.html
  web_widget_char_size/static/src/js/char_widget.js
Labels: approved, ready to merge, bot is merging ⏳

#2113 [11.0][FIX] Modal window suddenly closes
  web_widget_color/static/src/js/widget.js
Labels: bot is merging ⏳

#2241 [12.0][IMP] web_ir_actions_act_view_reload: support wizards
  web_ir_actions_act_view_reload/static/src/js/web_ir_actions_act_view_reload.js
Labels: bot is merging ⏳

#2828 [12.0][FIX] web_widget_one2many_product_picker: auto save timer
  web_widget_one2many_product_picker/models/base.py
  web_widget_one2many_product_picker/static/src/js/views/One2ManyProductPicker/renderer.js
  web_widget_one2many_product_picker/static/src/js/widgets/field_one2many_product_picker.js
Labels: bot is merging ⏳

#2660 [17.0] mig web_theme_classic
  web_theme_classic/README.rst
  web_theme_classic/__init__.py
  web_theme_classic/__manifest__.py
  web_theme_classic/i18n/web_theme_classic.pot
  web_theme_classic/pyproject.toml
  web_theme_classic/readme/CONTRIBUTORS.md
  web_theme_classic/readme/DESCRIPTION.md
  web_theme_classic/static/description/icon.png
  web_theme_classic/static/description/index.html
  web_theme_classic/static/description/product_template_form_with_module.png
  web_theme_classic/static/description/product_template_form_without_module.png
  web_theme_classic/static/src/scss/web_theme_classic.scss
Labels: bot is merging ⏳

#2806 [16.0][ADD] web_widget_pattern
  setup/web_widget_pattern/odoo/addons/web_widget_pattern
  setup/web_widget_pattern/setup.py
  setup/web_widget_pattern_partner_autocomplete/odoo/addons/web_widget_pattern_partner_autocomplete
  setup/web_widget_pattern_partner_autocomplete/setup.py
  web_widget_pattern/README.rst
  web_widget_pattern/__init__.py
  web_widget_pattern/__manifest__.py
  web_widget_pattern/demo/res_partner_views.xml
  web_widget_pattern/models/__init__.py
  web_widget_pattern/models/base.py
  web_widget_pattern/readme/CONTRIBUTORS.md
  web_widget_pattern/readme/DESCRIPTION.md
  web_widget_pattern/readme/ROADMAP.md
  web_widget_pattern/readme/USAGE.md
  web_widget_pattern/static/description/icon.png
  web_widget_pattern/static/description/index.html
  web_widget_pattern/static/src/autocomplete.esm.js
  web_widget_pattern/static/src/autocomplete.xml
  web_widget_pattern/static/src/char_field.esm.js
  web_widget_pattern/static/src/char_field.xml
  web_widget_pattern/tests/__init__.py
  web_widget_pattern/tests/test_web_widget_pattern.py
  web_widget_pattern_partner_autocomplete/README.rst
  web_widget_pattern_partner_autocomplete/__init__.py
  web_widget_pattern_partner_autocomplete/__manifest__.py
  web_widget_pattern_partner_autocomplete/demo/res_partner_views.xml
  web_widget_pattern_partner_autocomplete/models/__init__.py
  web_widget_pattern_partner_autocomplete/models/base.py
  web_widget_pattern_partner_autocomplete/readme/CONTRIBUTORS.md
  web_widget_pattern_partner_autocomplete/readme/DESCRIPTION.md
  web_widget_pattern_partner_autocomplete/static/description/icon.png
  web_widget_pattern_partner_autocomplete/static/description/index.html
  web_widget_pattern_partner_autocomplete/static/src/autocomplete.xml
Labels: approved, ready to merge, bot is merging ⏳

#2829 [16.0][REF] pre-commit fix
  web_dashboard_tile/migrations/post-migration.py
  web_dashboard_tile/models/tile_tile.py
  web_tree_image_tooltip/readme/CONFIGURE.rst
  web_tree_image_tooltip/readme/CONTRIBUTORS.rst
  web_tree_image_tooltip/readme/CREDITS.rst
  web_tree_image_tooltip/readme/DESCRIPTION.rst
  web_tree_image_tooltip/readme/USAGE.rst
  web_view_calendar_column/static/src/js/calendar_model.js
  web_view_searchpanel/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2823 [16.0][FIX] web_field_tooltip: access to ir.model and ir.model.fields…
  web_field_tooltip/security/ir_model_access.xml
  web_field_tooltip/views/ir_model_fields_tooltip.xml
Labels: approved, bot is merging ⏳

#2671 [17.0][MIG] web_widget_open_tab: Migration to 17.0
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/demo/res_users_view.xml
  web_widget_open_tab/i18n/ca.po
  web_widget_open_tab/i18n/de.po
  web_widget_open_tab/i18n/es.po
  web_widget_open_tab/i18n/ja.po
  web_widget_open_tab/i18n/pt_BR.po
  web_widget_open_tab/i18n/web_widget_open_tab.pot
  web_widget_open_tab/models/__init__.py
  web_widget_open_tab/models/ir_model.py
  web_widget_open_tab/models/ir_ui_view.py
  web_widget_open_tab/pyproject.toml
  web_widget_open_tab/readme/CONTRIBUTORS.md
  web_widget_open_tab/readme/DESCRIPTION.md
  web_widget_open_tab/readme/ROADMAP.md
  web_widget_open_tab/readme/USAGE.md
  web_widget_open_tab/static/description/icon.png
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/static/src/js/open_tab_widget.esm.js
  web_widget_open_tab/static/src/xml/open_tab_widget.xml
  web_widget_open_tab/tests/__init__.py
  web_widget_open_tab/tests/test_main.py
  web_widget_open_tab/views/ir_model_views.xml
Labels: approved, bot is merging ⏳

#1855 [14.0][ADD] New addon web_pivot_hide_total
  setup/web_pivot_hide_total/odoo/addons/web_pivot_hide_total
  setup/web_pivot_hide_total/setup.py
  web_pivot_hide_total/README.rst
  web_pivot_hide_total/__init__.py
  web_pivot_hide_total/__manifest__.py
  web_pivot_hide_total/readme/CONFIGURATION.rst
  web_pivot_hide_total/readme/CONFIGURE.rst
  web_pivot_hide_total/readme/CONTRIBUTORS.rst
  web_pivot_hide_total/readme/DESCRIPTION.rst
  web_pivot_hide_total/readme/ROADMAP.rst
  web_pivot_hide_total/static/description/after.png
  web_pivot_hide_total/static/description/before.png
  web_pivot_hide_total/static/description/icon.png
  web_pivot_hide_total/static/src/js/views/pivot/pivot_model_hide_total.js
  web_pivot_hide_total/static/src/js/views/pivot/pivot_view_hide_total.js
  web_pivot_hide_total/views/web_pivot_hide_total_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2790 [16.0][IMP] web_timeline: Align to top instead of bottom
  web_timeline/static/src/js/timeline_view.js
Labels: approved, ready to merge, bot is merging ⏳

#2832 [16.0][FIX] web_responsive: Remove unnecessary media query
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: approved, bot is merging ⏳

#2824 [16.0][FIX] web_m2x_options: fix usage errors
  web_m2x_options/readme/USAGE.rst
Labels: approved, ready to merge, bot is merging ⏳

#2835 [15.0][IMP] web_filter_header_button: show groupBy filters
  web_filter_header_button/README.rst
  web_filter_header_button/demo/ir_module_module_view.xml
  web_filter_header_button/readme/ROADMAP.md
  web_filter_header_button/static/description/index.html
  web_filter_header_button/static/src/control_panel/control_panel.xml
  web_filter_header_button/static/src/control_panel/control_panel_model_extension.esm.js
  web_filter_header_button/static/src/filter_button/filter_button.esm.js
  web_filter_header_button/static/src/filter_button/filter_button.xml
Labels: approved, bot is merging ⏳
