Repository OCA/web, pull requests merged in 2024-12, with the labels that each got.

#2893 [17.0][MIG] web_chatter_position: Migration to 17.0
  web_chatter_position/README.rst
  web_chatter_position/__init__.py
  web_chatter_position/__manifest__.py
  web_chatter_position/i18n/ca.po
  web_chatter_position/i18n/de.po
  web_chatter_position/i18n/es.po
  web_chatter_position/i18n/fr.po
  web_chatter_position/i18n/hr.po
  web_chatter_position/i18n/it.po
  web_chatter_position/i18n/nl.po
  web_chatter_position/i18n/pt_BR.po
  web_chatter_position/i18n/tr.po
  web_chatter_position/i18n/web_chatter_position.pot
  web_chatter_position/models/__init__.py
  web_chatter_position/models/res_users.py
  web_chatter_position/pyproject.toml
  web_chatter_position/readme/CONTRIBUTORS.md
  web_chatter_position/readme/DESCRIPTION.md
  web_chatter_position/readme/USAGE.md
  web_chatter_position/static/description/icon.png
  web_chatter_position/static/description/index.html
  web_chatter_position/static/src/js/web_chatter_position.esm.js
  web_chatter_position/static/src/scss/form_controller.scss
  web_chatter_position/static/src/scss/form_renderer.scss
  web_chatter_position/static/src/scss/form_statusbar.scss
  web_chatter_position/views/res_users.xml
  web_chatter_position/views/web.xml
Labels: bot is merging ⏳

#3009 [16.0][ADD] web_widget_product_label_section_and_note: New module to unify …
  setup/web_widget_product_label_section_and_note/odoo/addons/web_widget_product_label_section_and_note
  setup/web_widget_product_label_section_and_note/setup.py
  web_widget_product_label_section_and_note/README.rst
  web_widget_product_label_section_and_note/__init__.py
  web_widget_product_label_section_and_note/__manifest__.py
  web_widget_product_label_section_and_note/readme/CONFIGURE.rst
  web_widget_product_label_section_and_note/readme/CONTRIBUTORS.rst
  web_widget_product_label_section_and_note/readme/DESCRIPTION.rst
  web_widget_product_label_section_and_note/readme/ROADMAP.rst
  web_widget_product_label_section_and_note/readme/USAGE.rst
  web_widget_product_label_section_and_note/static/description/index.html
  web_widget_product_label_section_and_note/static/src/components/product_label_section_and_note_field/product_label_section_and_note_field.esm.js
  web_widget_product_label_section_and_note/static/src/components/product_label_section_and_note_field/product_label_section_and_note_field.scss
  web_widget_product_label_section_and_note/static/src/components/product_label_section_and_note_field/product_label_section_and_note_field.xml
  web_widget_product_label_section_and_note/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#3014 [17.0][FIX] web_responsive: Add support to serve menu icon in image url
  web_responsive/static/src/components/apps_menu_tools.esm.js
Labels: approved, bot is merging ⏳

#3016 [16.0][IMP] web_widget_product_label_section_and_note: Auto-resize textarea for multiline text.
  web_widget_product_label_section_and_note/README.rst
  web_widget_product_label_section_and_note/__manifest__.py
  web_widget_product_label_section_and_note/readme/ROADMAP.rst
  web_widget_product_label_section_and_note/static/description/index.html
  web_widget_product_label_section_and_note/static/src/components/product_label_section_and_note_field/product_label_section_and_note_field.esm.js
  web_widget_product_label_section_and_note/static/src/core/utils/autoresize.esm.js
  web_widget_product_label_section_and_note/static/src/core/utils/product_and_label_autoresize.esm.js
Labels: bot is merging ⏳

#3018 [14.0] [IMP] web_m2x_options: use the correct context in search function
  web_m2x_options/static/src/js/form.js
Labels: approved, bot is merging ⏳

#3027 [18.0] help on web repo to apply last pre-commit changes
  web_pivot_computed_measure/static/src/dropdown_item_custom_measure/dropdown_item_custom_measure.esm.js
  web_pivot_computed_measure/static/src/helpers/utils.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_controller.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_model.esm.js
  web_pivot_computed_measure/static/src/pivot/pivot_renderer.esm.js
  web_pivot_computed_measure/static/src/report_view_measures/report_view_measures.esm.js
  web_pivot_computed_measure/static/src/test/test.esm.js
  web_tree_dynamic_colored_field/static/src/js/list_renderer.esm.js
Labels: approved, bot is merging ⏳

#3035 [18.0][MIG] web_tree_many2one_clickable: Migration to 18.0
  web_tree_many2one_clickable/README.rst
  web_tree_many2one_clickable/__init__.py
  web_tree_many2one_clickable/__manifest__.py
  web_tree_many2one_clickable/i18n/it.po
  web_tree_many2one_clickable/i18n/web_tree_many2one_clickable.pot
  web_tree_many2one_clickable/i18n/zh_CN.po
  web_tree_many2one_clickable/pyproject.toml
  web_tree_many2one_clickable/readme/CONFIGURE.md
  web_tree_many2one_clickable/readme/CONTRIBUTORS.md
  web_tree_many2one_clickable/readme/DESCRIPTION.md
  web_tree_many2one_clickable/readme/ROADMAP.md
  web_tree_many2one_clickable/readme/USAGE.md
  web_tree_many2one_clickable/static/description/icon.png
  web_tree_many2one_clickable/static/description/index.html
  web_tree_many2one_clickable/static/img/clickable.gif
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.esm.js
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.scss
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.xml
Labels: approved, bot is merging ⏳

#3034 [18.0][MIG] web_no_bubble: Migration to 18.0
  web_no_bubble/README.rst
  web_no_bubble/__init__.py
  web_no_bubble/__manifest__.py
  web_no_bubble/i18n/es.po
  web_no_bubble/i18n/fr_FR.po
  web_no_bubble/i18n/hr.po
  web_no_bubble/i18n/it.po
  web_no_bubble/i18n/web_no_bubble.pot
  web_no_bubble/i18n/zh_CN.po
  web_no_bubble/pyproject.toml
  web_no_bubble/readme/CONTRIBUTORS.md
  web_no_bubble/readme/DESCRIPTION.md
  web_no_bubble/static/description/icon.png
  web_no_bubble/static/description/index.html
  web_no_bubble/static/src/css/web_no_bubble.scss
Labels: approved, bot is merging ⏳

#3033 [16.0][IMP] web_widget_numeric_step: throttle update calls when scrolling on field
  web_widget_numeric_step/static/src/numeric_step.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#3044 [18.0] help on web repo to apply last pre-commit changes
  web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.esm.js
Labels: approved, bot is merging ⏳
