Repository OCA/web, pull requests merged in 2024-04, with the labels that each got.

#2598 [16.0][IMP][web_notify] Add possibility to return an action in a notification (forward port from 10.0)
  web_notify/README.rst
  web_notify/models/res_users.py
  web_notify/readme/USAGE.rst
  web_notify/static/src/js/services/notification_services.esm.js
  web_notify/tests/test_res_users.py
Labels: approved, bot is merging ⏳

#2713 [16.0][FIX] web_timeline: Wrap fields_get arg into a list
  web_timeline/readme/CONTRIBUTORS.rst
  web_timeline/static/src/js/timeline_renderer.js
Labels: approved, ready to merge, bot is merging ⏳

#2771 [17.0][MIG] web_tree_dynamic_colored_field
  web_tree_dynamic_colored_field/README.rst
  web_tree_dynamic_colored_field/__init__.py
  web_tree_dynamic_colored_field/__manifest__.py
  web_tree_dynamic_colored_field/demo/res_users.xml
  web_tree_dynamic_colored_field/i18n/es.po
  web_tree_dynamic_colored_field/i18n/fi.po
  web_tree_dynamic_colored_field/i18n/fr.po
  web_tree_dynamic_colored_field/i18n/nl_NL.po
  web_tree_dynamic_colored_field/i18n/sl.po
  web_tree_dynamic_colored_field/i18n/web_tree_dynamic_colored_field.pot
  web_tree_dynamic_colored_field/i18n/zh_CN.po
  web_tree_dynamic_colored_field/pyproject.toml
  web_tree_dynamic_colored_field/readme/CONTRIBUTORS.md
  web_tree_dynamic_colored_field/readme/CREDITS.md
  web_tree_dynamic_colored_field/readme/DESCRIPTION.md
  web_tree_dynamic_colored_field/readme/ROADMAP.md
  web_tree_dynamic_colored_field/readme/USAGE.md
  web_tree_dynamic_colored_field/static/description/icon.png
  web_tree_dynamic_colored_field/static/description/index.html
  web_tree_dynamic_colored_field/static/src/js/list_renderer.esm.js
  web_tree_dynamic_colored_field/static/src/xml/list.xml
Labels: approved, ready to merge, bot is merging ⏳

#2768 [15.0][ADD] web_filter_header_button: New module
  setup/web_filter_header_button/odoo/addons/web_filter_header_button
  setup/web_filter_header_button/setup.py
  web_filter_header_button/README.rst
  web_filter_header_button/__init__.py
  web_filter_header_button/__manifest__.py
  web_filter_header_button/demo/ir_module_module_view.xml
  web_filter_header_button/readme/CONFIGURE.md
  web_filter_header_button/readme/CONTEXT.md
  web_filter_header_button/readme/CONTRIBUTORS.md
  web_filter_header_button/readme/DESCRIPTION.md
  web_filter_header_button/readme/ROADMAP.md
  web_filter_header_button/readme/USAGE.md
  web_filter_header_button/static/description/index.html
  web_filter_header_button/static/src/control_panel/control_panel.esm.js
  web_filter_header_button/static/src/control_panel/control_panel.xml
  web_filter_header_button/static/src/control_panel/control_panel_model_extension.esm.js
  web_filter_header_button/static/src/filter_button/filter_button.esm.js
  web_filter_header_button/static/src/filter_button/filter_button.xml
Labels: approved, ready to merge, bot is merging ⏳

#2788 [16.0][FIX] web_tree_duplicate: adapt readme to behavior
  web_tree_duplicate/README.rst
  web_tree_duplicate/readme/CONFIGURE.rst
  web_tree_duplicate/static/description/index.html
Labels: approved, bot is merging ⏳

#2792 [16.0][FIX] web_responsive: fix status widget visibility
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: approved, bot is merging ⏳

#2775 [16.0][IMP] web_timeline: Overflow text, add hover colors
  web_timeline/readme/ROADMAP.rst
  web_timeline/static/src/scss/web_timeline.scss
Labels: approved, ready to merge, bot is merging ⏳

#2783 [16.0][MIG] web_field_tooltip: Migration to 16.0
  setup/web_field_tooltip/odoo/addons/web_field_tooltip
  setup/web_field_tooltip/setup.py
  web_field_tooltip/README.rst
  web_field_tooltip/__init__.py
  web_field_tooltip/__manifest__.py
  web_field_tooltip/i18n/fr.po
  web_field_tooltip/i18n/web_field_tooltip.pot
  web_field_tooltip/models/__init__.py
  web_field_tooltip/models/base.py
  web_field_tooltip/models/ir_http.py
  web_field_tooltip/models/ir_model_fields_tooltip.py
  web_field_tooltip/models/res_users.py
  web_field_tooltip/readme/CONTRIBUTORS.rst
  web_field_tooltip/readme/DESCRIPTION.rst
  web_field_tooltip/readme/ROADMAP.rst
  web_field_tooltip/readme/USAGE.rst
  web_field_tooltip/security/ir_model_access.xml
  web_field_tooltip/security/res_groups.xml
  web_field_tooltip/static/description/icon.png
  web_field_tooltip/static/description/index.html
  web_field_tooltip/static/src/components/field_tooltip/field_tooltip.esm.js
  web_field_tooltip/static/src/components/field_tooltip/field_tooltip.scss
  web_field_tooltip/static/src/components/field_tooltip/field_tooltip.xml
  web_field_tooltip/static/src/views/form/form_controller.esm.js
  web_field_tooltip/static/src/views/form/form_label.esm.js
  web_field_tooltip/static/src/views/form/form_label.xml
  web_field_tooltip/static/src/views/list/list_renderer.esm.js
  web_field_tooltip/static/src/views/list/list_renderer.xml
  web_field_tooltip/tests/__init__.py
  web_field_tooltip/tests/test_web_field_tooltip.py
  web_field_tooltip/views/ir_model_fields_tooltip.xml
  web_field_tooltip/views/res_users.xml
  web_field_tooltip/views/template.xml
Labels: approved, ready to merge, bot is merging ⏳

#2523 [15.0][IMP] web_widget_open_tab
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/models/__init__.py
  web_widget_open_tab/models/ir_model.py
  web_widget_open_tab/models/ir_ui_view.py
  web_widget_open_tab/readme/CONTRIBUTORS.rst
  web_widget_open_tab/readme/USAGE.rst
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/views/ir_model_views.xml
Labels: approved, bot is merging ⏳

#2362 [14.0][FIX]support_branding: change support_company name
  support_branding/models/res_config_settings.py
Labels: approved, bot is merging ⏳

#2511 [16.0][MIG] web_ir_actions_close_wizard_refresh_view
  setup/web_ir_actions_close_wizard_refresh_view/odoo/addons/web_ir_actions_close_wizard_refresh_view
  setup/web_ir_actions_close_wizard_refresh_view/setup.py
  web_ir_actions_close_wizard_refresh_view/README.rst
  web_ir_actions_close_wizard_refresh_view/__init__.py
  web_ir_actions_close_wizard_refresh_view/__manifest__.py
  web_ir_actions_close_wizard_refresh_view/models/__init__.py
  web_ir_actions_close_wizard_refresh_view/models/ir_actions.py
  web_ir_actions_close_wizard_refresh_view/readme/DESCRIPTION.rst
  web_ir_actions_close_wizard_refresh_view/readme/USAGE.rst
  web_ir_actions_close_wizard_refresh_view/security/ir.model.access.csv
  web_ir_actions_close_wizard_refresh_view/static/description/icon.png
  web_ir_actions_close_wizard_refresh_view/static/description/index.html
  web_ir_actions_close_wizard_refresh_view/static/src/js/web_ir_actions_close_wizard_refresh_view.esm.js
Labels: approved, bot is merging ⏳

#2796 [15.0][FIX] web_pivot_computed_measure: Avoid Infinity errors by comparisons
  web_pivot_computed_measure/static/src/pivot/pivot_renderer.esm.js
Labels: approved, bot is merging ⏳

#2797 [16.0][IMP] web_responsive: Set viewer width to 100% to better use the space
  web_responsive/static/src/components/attachment_viewer/attachment_viewer.scss
Labels: approved, bot is merging ⏳

#2787 [16.0][IMP] web_refresher: Backport refresh way from v17
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/static/description/index.html
  web_refresher/static/src/js/control_panel.esm.js
  web_refresher/static/src/js/pager.esm.js
  web_refresher/static/src/js/refresher.esm.js
  web_refresher/static/src/scss/refresher.scss
  web_refresher/static/src/xml/control_panel.xml
  web_refresher/static/src/xml/pager.xml
  web_refresher/static/src/xml/refresher.xml
Labels: approved, ready to merge, merged 🎉

#2800 [17.0][IMP] web_refresher: Be able to refresh from report views
  web_refresher/static/src/js/refresher.esm.js
  web_refresher/static/src/xml/refresher.xml
Labels: approved, bot is merging ⏳

#2770 [17.0][MIG] web_favicon: Migration to 17.0
  web_favicon/README.rst
  web_favicon/__init__.py
  web_favicon/__manifest__.py
  web_favicon/models/__init__.py
  web_favicon/models/res_company.py
  web_favicon/pyproject.toml
  web_favicon/readme/CONFIGURE.md
  web_favicon/readme/CONTRIBUTORS.md
  web_favicon/readme/DESCRIPTION.md
  web_favicon/readme/ROADMAP.md
  web_favicon/static/description/icon.png
  web_favicon/static/description/index.html
  web_favicon/tests/__init__.py
  web_favicon/tests/test_web_favicon.py
  web_favicon/views/res_company_views.xml
  web_favicon/views/templates.xml
Labels: approved, bot is merging ⏳

#2795 [17.0][FIX] web_responsive: disable default file preview
  web_responsive/__manifest__.py
  web_responsive/static/description/index.html
  web_responsive/static/src/components/file_viewer/file_viewer.esm.js
  web_responsive/static/src/views/form/form_renderer.esm.js
  web_responsive/static/src/views/form/form_statusbar.scss
Labels: bot is merging ⏳

#2804 [16.0][IMP] web_refresher: Charge t-inherit-mode extension views just after the main
  web_refresher/README.rst
  web_refresher/__manifest__.py
  web_refresher/static/description/index.html
  web_refresher/static/src/xml/control_panel.xml
  web_refresher/static/src/xml/form_control_panel.xml
Labels: approved, bot is merging ⏳

#2807 [17.0][IMP] web_refresher: Charge t-inherit-mode extension views just after the main
  web_refresher/__manifest__.py
  web_refresher/static/description/index.html
Labels: approved, bot is merging ⏳
