Repository OCA/web, pull requests merged in 2024-08, with the labels that each got.

#2897 [16.0][MIG] web_widget_image_download: migration to 16.0
  setup/web_widget_image_download/odoo/addons/web_widget_image_download
  setup/web_widget_image_download/setup.py
  web_widget_image_download/README.rst
  web_widget_image_download/__init__.py
  web_widget_image_download/__manifest__.py
  web_widget_image_download/i18n/es.po
  web_widget_image_download/i18n/hr.po
  web_widget_image_download/i18n/it.po
  web_widget_image_download/i18n/lt.po
  web_widget_image_download/i18n/nl_NL.po
  web_widget_image_download/i18n/pt.po
  web_widget_image_download/i18n/web_widget_image_download.pot
  web_widget_image_download/i18n/zh_CN.po
  web_widget_image_download/readme/CONTRIBUTORS.rst
  web_widget_image_download/readme/DESCRIPTION.rst
  web_widget_image_download/readme/USAGE.rst
  web_widget_image_download/static/description/icon.png
  web_widget_image_download/static/description/index.html
  web_widget_image_download/static/src/components/image_field.esm.js
  web_widget_image_download/static/src/xml/web_widget_image_download.xml
Labels: approved, bot is merging ⏳

#2902 [16.0][FIX] web_company_color: Set defaults hardcoded to avoid errors charging the assetbundle
  web_company_color/__manifest__.py
  web_company_color/migrations/16.0.1.2.1/post-migration.py
  web_company_color/models/res_company.py
  web_company_color/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#2905 [16.0][MIG] web notify upgrade
  setup/web_notify_upgrade/odoo/addons/web_notify_upgrade
  setup/web_notify_upgrade/setup.py
  web_notify_upgrade/README.rst
  web_notify_upgrade/__init__.py
  web_notify_upgrade/__manifest__.py
  web_notify_upgrade/i18n/fr.po
  web_notify_upgrade/i18n/web_notify_upgrade.pot
  web_notify_upgrade/models/__init__.py
  web_notify_upgrade/models/ir_model.py
  web_notify_upgrade/readme/CONTRIBUTORS.rst
  web_notify_upgrade/readme/DESCRIPTION.rst
  web_notify_upgrade/static/description/index.html
  web_notify_upgrade/static/description/notify.png
Labels: approved, bot is merging ⏳

#2903 [17.0][MIG] web_widget_image_download: Migration to 17.0
  web_widget_image_download/README.rst
  web_widget_image_download/__init__.py
  web_widget_image_download/__manifest__.py
  web_widget_image_download/i18n/es.po
  web_widget_image_download/i18n/hr.po
  web_widget_image_download/i18n/it.po
  web_widget_image_download/i18n/lt.po
  web_widget_image_download/i18n/nl_NL.po
  web_widget_image_download/i18n/pt.po
  web_widget_image_download/i18n/web_widget_image_download.pot
  web_widget_image_download/i18n/zh_CN.po
  web_widget_image_download/pyproject.toml
  web_widget_image_download/readme/CONTRIBUTORS.md
  web_widget_image_download/readme/DESCRIPTION.md
  web_widget_image_download/readme/USAGE.md
  web_widget_image_download/static/description/icon.png
  web_widget_image_download/static/description/index.html
  web_widget_image_download/static/src/components/image_field.esm.js
  web_widget_image_download/static/src/xml/web_widget_image_download.xml
Labels: approved, bot is merging ⏳

#2910 [16.0][FIX] web_responsive: Remove overflow:visible to tables to avoid side effects
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: approved, bot is merging ⏳

#2911 [FIX] web_responsive: Can't access web using superuser
  .copier-answers.yml
  .eslintrc.yml
  .gitignore
  .pre-commit-config.yaml
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
Labels: approved, bot is merging ⏳

#2906 [17.0][MIG] web_widget_numeric_step: Migration to 17.0
  web_widget_numeric_step/README.rst
  web_widget_numeric_step/__init__.py
  web_widget_numeric_step/__manifest__.py
  web_widget_numeric_step/demo/ir_cron.xml
  web_widget_numeric_step/i18n/de.po
  web_widget_numeric_step/i18n/es.po
  web_widget_numeric_step/i18n/fr.po
  web_widget_numeric_step/i18n/it.po
  web_widget_numeric_step/i18n/web_widget_numeric_step.pot
  web_widget_numeric_step/pyproject.toml
  web_widget_numeric_step/readme/CONTRIBUTORS.md
  web_widget_numeric_step/readme/DESCRIPTION.md
  web_widget_numeric_step/readme/USAGE.md
  web_widget_numeric_step/static/description/add_two_buttons.png
  web_widget_numeric_step/static/description/icon.png
  web_widget_numeric_step/static/description/index.html
  web_widget_numeric_step/static/description/step0,25andlimits.gif
  web_widget_numeric_step/static/description/step10_limit15_placeholder117_with_onchange.gif
  web_widget_numeric_step/static/src/numeric_step.esm.js
  web_widget_numeric_step/static/src/numeric_step.scss
  web_widget_numeric_step/static/src/numeric_step.xml
Labels: approved, bot is merging ⏳

#2913 [16.0][FIX] web_refresher: bug when clicking on production plan
  web_refresher/__manifest__.py
Labels: approved, bot is merging ⏳

#2914 [17.0][FIX] web_refresher: bug when clicking report
  web_refresher/__manifest__.py
Labels: approved, bot is merging ⏳

#2915 [17.0][MIG] web_widget_dropdown_dynamic: Migration to 17.0
  web_m2x_options/static/src/components/form.esm.js
  web_widget_dropdown_dynamic/README.rst
  web_widget_dropdown_dynamic/__init__.py
  web_widget_dropdown_dynamic/__manifest__.py
  web_widget_dropdown_dynamic/demo/ir_filters_view.xml
  web_widget_dropdown_dynamic/demo/ir_model_fields.xml
  web_widget_dropdown_dynamic/i18n/de.po
  web_widget_dropdown_dynamic/i18n/es.po
  web_widget_dropdown_dynamic/i18n/it.po
  web_widget_dropdown_dynamic/i18n/web_widget_dropdown_dynamic.pot
  web_widget_dropdown_dynamic/models/__init__.py
  web_widget_dropdown_dynamic/models/ir_filters.py
  web_widget_dropdown_dynamic/pyproject.toml
  web_widget_dropdown_dynamic/readme/CONTRIBUTORS.md
  web_widget_dropdown_dynamic/readme/CREDITS.md
  web_widget_dropdown_dynamic/readme/DESCRIPTION.md
  web_widget_dropdown_dynamic/readme/USAGE.md
  web_widget_dropdown_dynamic/static/description/icon.png
  web_widget_dropdown_dynamic/static/description/index.html
  web_widget_dropdown_dynamic/static/src/js/field_dynamic_dropdown.esm.js
  web_widget_dropdown_dynamic/static/tests/web_widget_dropdown_dynamic_tests.esm.js
Labels: approved, bot is merging ⏳

#2916 [16.0][ADD] web_widget_remaining_days_exact_date: New module to show exact date when remaining days shown
  setup/web_widget_remaining_days_exact_date/odoo/addons/web_widget_remaining_days_exact_date
  setup/web_widget_remaining_days_exact_date/setup.py
  web_widget_remaining_days_exact_date/README.rst
  web_widget_remaining_days_exact_date/__init__.py
  web_widget_remaining_days_exact_date/__manifest__.py
  web_widget_remaining_days_exact_date/readme/CONTRIBUTORS.rst
  web_widget_remaining_days_exact_date/readme/DESCRIPTION.rst
  web_widget_remaining_days_exact_date/readme/USAGE.rst
  web_widget_remaining_days_exact_date/static/description/index.html
  web_widget_remaining_days_exact_date/static/src/remaining_days/remaining_days.esm.js
Labels: approved, bot is merging ⏳

#2918 [17.0][MIG] web_widget_url_advanced: Migration to 17.0
  web_widget_url_advanced/README.rst
  web_widget_url_advanced/__init__.py
  web_widget_url_advanced/__manifest__.py
  web_widget_url_advanced/i18n/es.po
  web_widget_url_advanced/i18n/web_widget_url_advanced.pot
  web_widget_url_advanced/i18n/zh_CN.po
  web_widget_url_advanced/pyproject.toml
  web_widget_url_advanced/readme/CONTRIBUTORS.md
  web_widget_url_advanced/readme/DESCRIPTION.md
  web_widget_url_advanced/readme/USAGE.md
  web_widget_url_advanced/static/description/after.png
  web_widget_url_advanced/static/description/before.png
  web_widget_url_advanced/static/description/icon.png
  web_widget_url_advanced/static/description/index.html
  web_widget_url_advanced/static/src/fields/url_field.esm.js
  web_widget_url_advanced/static/src/fields/url_field.xml
Labels: bot is merging ⏳

#2879 [16.0] Create module web_datetime_picker_default_time
  setup/web_datetime_picker_default_time/odoo/addons/web_datetime_picker_default_time
  setup/web_datetime_picker_default_time/setup.py
  web_datetime_picker_default_time/README.rst
  web_datetime_picker_default_time/__init__.py
  web_datetime_picker_default_time/__manifest__.py
  web_datetime_picker_default_time/readme/CONTRIBUTORS.md
  web_datetime_picker_default_time/readme/DESCRIPTION.md
  web_datetime_picker_default_time/readme/ROADMAP.md
  web_datetime_picker_default_time/readme/USAGE.md
  web_datetime_picker_default_time/static/description/index.html
  web_datetime_picker_default_time/static/src/js/datepicker.esm.js
  web_datetime_picker_default_time/static/src/js/datetime_field.esm.js
  web_datetime_picker_default_time/static/src/xml/datetime_field.xml
Labels: approved, ready to merge, bot is merging ⏳
