Repository OCA/web, pull requests merged in 2025-06, with the labels that each got.

#3184 [16.0][IMP] web_notify: license change
  web_notify/README.rst
  web_notify/__init__.py
  web_notify/__manifest__.py
  web_notify/models/res_users.py
  web_notify/static/description/index.html
  web_notify/tests/__init__.py
  web_notify/tests/test_res_users.py
  web_notify/views/res_users_demo.xml
Labels: approved, bot is merging ⏳

#3188 [18.0][IMP] web_notify: license change
  web_notify/README.rst
  web_notify/__init__.py
  web_notify/__manifest__.py
  web_notify/models/res_users.py
  web_notify/static/description/index.html
  web_notify/tests/__init__.py
  web_notify/tests/test_res_users.py
  web_notify/views/res_users_demo.xml
Labels: approved, bot is merging ⏳

#3101 [18.0][MIG] web_session_auto_close
  web_session_auto_close/README.rst
  web_session_auto_close/__init__.py
  web_session_auto_close/__manifest__.py
  web_session_auto_close/controllers/__init__.py
  web_session_auto_close/controllers/main.py
  web_session_auto_close/i18n/web_session_auto_close.pot
  web_session_auto_close/models/__init__.py
  web_session_auto_close/models/res_config_settings.py
  web_session_auto_close/pyproject.toml
  web_session_auto_close/readme/CONFIGURE.md
  web_session_auto_close/readme/CONTRIBUTORS.md
  web_session_auto_close/readme/DESCRIPTION.md
  web_session_auto_close/static/description/icon.png
  web_session_auto_close/static/description/index.html
  web_session_auto_close/static/src/js/session_auto_close.esm.js
  web_session_auto_close/views/res_config_settings.xml
Labels: needs review, approved, migration, bot is merging ⏳

#3190 [16.0][FIX] web_responsive: Do not duplicate buttons
  web_responsive/__manifest__.py
  web_responsive/static/src/components/chatter_topbar/chatter_topbar.scss
  web_responsive/static/src/components/chatter_topbar/chatter_topbar.xml
Labels: approved, bot is merging ⏳

#3202 [18.0][FIX] web_widget_x2many_2d_matrix: don't break non-many2one value fields
  .copier-answers.yml
  eslint.config.cjs
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
  web_widget_x2many_2d_matrix/static/tests/web_widget_x2many_2d_matrix.test.js
  web_widget_x2many_2d_matrix/tests/__init__.py
  web_widget_x2many_2d_matrix/tests/test_web_widget_x2many_2d_matrix.py
Labels: approved, bot is merging ⏳

#3191 [18.0][FIX] web_m2x_options: prevent crash on Many2OneReferenceField
  web_m2x_options/README.rst
  web_m2x_options/readme/CONTRIBUTORS.md
  web_m2x_options/readme/ROADMAP.md
  web_m2x_options/static/description/index.html
  web_m2x_options/static/src/components/form.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#3206 [17.0] [ADD] web_widget_section_and_note_text_scrollable
  web_widget_section_and_note_text_scrollable/README.rst
  web_widget_section_and_note_text_scrollable/__init__.py
  web_widget_section_and_note_text_scrollable/__manifest__.py
  web_widget_section_and_note_text_scrollable/pyproject.toml
  web_widget_section_and_note_text_scrollable/readme/CONTRIBUTORS.md
  web_widget_section_and_note_text_scrollable/readme/DESCRIPTION.md
  web_widget_section_and_note_text_scrollable/static/description/scroll_line_description.gif
  web_widget_section_and_note_text_scrollable/static/description/scroll_note.gif
  web_widget_section_and_note_text_scrollable/static/src/section_and_note_text_scrollable.scss
Labels: approved, ready to merge, bot is merging ⏳
