Repository OCA/web, pull requests merged in 2025-09, with the labels that each got.

#3275 [18.0][REF] web_responsive: set as rebel module
  .github/workflows/test.yml
Labels: approved, bot is merging ⏳

#3268 [18.0][FIX] web_company_color: fix systray icon color
  web_company_color/models/res_company.py
Labels: approved, bot is merging ⏳

#2977 [16.0][IMP] web_field_tooltip: Enable translation
  web_field_tooltip/models/ir_model_fields_tooltip.py
Labels: approved, ready to merge

#3216 [18.0][MIG] web_notify_upgrade
  web_notify_upgrade/README.rst
  web_notify_upgrade/__init__.py
  web_notify_upgrade/__manifest__.py
  web_notify_upgrade/i18n/fr.po
  web_notify_upgrade/i18n/it.po
  web_notify_upgrade/i18n/web_notify_upgrade.pot
  web_notify_upgrade/models/__init__.py
  web_notify_upgrade/models/ir_model.py
  web_notify_upgrade/pyproject.toml
  web_notify_upgrade/readme/CONTRIBUTORS.md
  web_notify_upgrade/readme/DESCRIPTION.md
  web_notify_upgrade/static/description/icon.png
  web_notify_upgrade/static/description/index.html
  web_notify_upgrade/static/description/notify.png
Labels: approved, bot is merging ⏳

#3259 [16.0][ADD] web_export_html_as_text
  setup/web_export_html_as_text/odoo/addons/web_export_html_as_text
  setup/web_export_html_as_text/setup.py
  web_export_html_as_text/README.rst
  web_export_html_as_text/__init__.py
  web_export_html_as_text/__manifest__.py
  web_export_html_as_text/models/__init__.py
  web_export_html_as_text/models/models.py
  web_export_html_as_text/readme/CONFIGURE.rst
  web_export_html_as_text/readme/CONTRIBUTORS.rst
  web_export_html_as_text/readme/DESCRIPTION.rst
  web_export_html_as_text/readme/ROADMAP.rst
  web_export_html_as_text/static/description/index.html
  web_export_html_as_text/static/src/js/export_html_to_text.esm.js
  web_export_html_as_text/static/src/xml/export_dialog.xml
  web_export_html_as_text/tests/__init__.py
  web_export_html_as_text/tests/test_export_html_text.py
  web_export_html_as_text/tests/test_models.py
Labels: approved, bot is merging ⏳

#3221 [16.0][MIG] web_group_by_percentage
  setup/web_group_by_percentage/odoo/addons/web_group_by_percentage
  setup/web_group_by_percentage/setup.py
  web_group_by_percentage/README.rst
  web_group_by_percentage/__init__.py
  web_group_by_percentage/__manifest__.py
  web_group_by_percentage/i18n/ca.po
  web_group_by_percentage/i18n/es.po
  web_group_by_percentage/i18n/pt_BR.po
  web_group_by_percentage/i18n/web_group_by_percentage.pot
  web_group_by_percentage/i18n/zh_CN.po
  web_group_by_percentage/readme/CONTRIBUTORS.rst
  web_group_by_percentage/readme/DESCRIPTION.rst
  web_group_by_percentage/readme/USAGE.rst
  web_group_by_percentage/static/description/icon.png
  web_group_by_percentage/static/description/index.html
  web_group_by_percentage/static/description/screenshot.png
  web_group_by_percentage/static/src/js/backend.esm.js
  web_group_by_percentage/static/src/legacy/js/backend_legacy.js
  web_group_by_percentage/static/src/scss/backend.scss
  web_group_by_percentage/static/src/xml/list_grouprow_percentage.xml
Labels: bot is merging ⏳

#3021 [18.0][MIG] web_widget_url_advanced: Migration to 18.0
  web_widget_url_advanced/README.rst
  web_widget_url_advanced/__init__.py
  web_widget_url_advanced/__manifest__.py
  web_widget_url_advanced/i18n/es.po
  web_widget_url_advanced/i18n/web_widget_url_advanced.pot
  web_widget_url_advanced/i18n/zh_CN.po
  web_widget_url_advanced/pyproject.toml
  web_widget_url_advanced/readme/CONTRIBUTORS.md
  web_widget_url_advanced/readme/DESCRIPTION.md
  web_widget_url_advanced/readme/USAGE.md
  web_widget_url_advanced/static/description/after.png
  web_widget_url_advanced/static/description/before.png
  web_widget_url_advanced/static/description/icon.png
  web_widget_url_advanced/static/description/index.html
  web_widget_url_advanced/static/src/fields/url_field.esm.js
  web_widget_url_advanced/static/src/fields/url_field.xml
Labels: approved, bot is merging ⏳

#3281 Fix CI in 14.0
  web_edit_user_filter/tests/test_edit_user_filter.py
Labels: bot is merging ⏳

#3292 [16.0][FIX] web_dialog_size: fix dialog shrink issue
  web_dialog_size/static/src/js/web_dialog_size.esm.js
  web_dialog_size/static/src/xml/ExpandButton.xml
Labels: approved, bot is merging ⏳
