Repository OCA/web, pull requests merged in 2025-07, with the labels that each got.

#3198 [18.0][IMP] web_responsive: Fix bug submenu on mobile
  web_responsive/static/src/components/apps_menu/apps_menu.esm.js
  web_responsive/static/src/components/apps_menu/apps_menu.scss
  web_responsive/static/src/components/apps_menu/apps_menu.xml
Labels: approved, bot is merging ⏳

#3211 [18.0][FIX] web_session_auto_close: Increase default timeout
  web_session_auto_close/controllers/main.py
  web_session_auto_close/models/res_config_settings.py
  web_session_auto_close/static/src/js/session_auto_close.esm.js
Labels: approved, bot is merging ⏳

#3156 [18.0][MIG] web_send_message_popup: Migration to 18.0
  web_send_message_popup/README.rst
  web_send_message_popup/__init__.py
  web_send_message_popup/__manifest__.py
  web_send_message_popup/i18n/fa.po
  web_send_message_popup/i18n/it.po
  web_send_message_popup/i18n/web_send_message_popup.pot
  web_send_message_popup/pyproject.toml
  web_send_message_popup/readme/CONTRIBUTORS.md
  web_send_message_popup/readme/DESCRIPTION.md
  web_send_message_popup/static/description/icon.png
  web_send_message_popup/static/description/index.html
  web_send_message_popup/static/src/chatter/web/chatter_patch.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#3219 [17.0][FIX] web_widget_x2many_2d_matrix: restore pre-v16 functionality
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/demo/res_groups_views.xml
  web_widget_x2many_2d_matrix/readme/CONTRIBUTORS.md
  web_widget_x2many_2d_matrix/readme/ROADMAP.md
  web_widget_x2many_2d_matrix/readme/USAGE.md
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.esm.js
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.xml
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.xml
Labels: bot is merging ⏳

#3203 [18.0][FIX] web_widget_x2many_2d_matrix: restore pre-v16 functionality
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/demo/res_groups_views.xml
  web_widget_x2many_2d_matrix/readme/CONTRIBUTORS.md
  web_widget_x2many_2d_matrix/readme/ROADMAP.md
  web_widget_x2many_2d_matrix/readme/USAGE.md
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.esm.js
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.xml
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.xml
  web_widget_x2many_2d_matrix/static/tests/web_widget_x2many_2d_matrix.test.js
Labels: bot is merging ⏳

#3214 [15.0][FIX] web_responsive: Remove test patching that is breaking tests
  web_responsive/__manifest__.py
  web_responsive/static/description/index.html
  web_responsive/static/tests/test_patch.js
Labels: approved, bot is merging ⏳

#3230 [18.0][FIX] web_widget_x2many_2d_matrix: adapt test invocation to upstream
  web_widget_x2many_2d_matrix/static/tests/web_widget_x2many_2d_matrix.test.js
  web_widget_x2many_2d_matrix/tests/test_web_widget_x2many_2d_matrix.py
Labels: bot is merging ⏳

#3177 [18.0][FIX] web_remember_tree_column_width: fix undefined `this`
  web_remember_tree_column_width/static/src/js/list_renderer.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#3208 [18.0][FIX] web_search_with_and: support add custom filter
  web_search_with_and/static/src/js/search_bar.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#3232 [18.0][MIG] web_widget_domain_editor_dialog: Migration to 18.0
  web_widget_domain_editor_dialog/README.rst
  web_widget_domain_editor_dialog/__init__.py
  web_widget_domain_editor_dialog/__manifest__.py
  web_widget_domain_editor_dialog/i18n/es.po
  web_widget_domain_editor_dialog/i18n/it.po
  web_widget_domain_editor_dialog/i18n/web_widget_domain_editor_dialog.pot
  web_widget_domain_editor_dialog/i18n/zh_CN.po
  web_widget_domain_editor_dialog/pyproject.toml
  web_widget_domain_editor_dialog/readme/CONTRIBUTORS.md
  web_widget_domain_editor_dialog/readme/DESCRIPTION.md
  web_widget_domain_editor_dialog/readme/USAGE.md
  web_widget_domain_editor_dialog/static/description/icon.png
  web_widget_domain_editor_dialog/static/description/index.html
  web_widget_domain_editor_dialog/static/src/img/behaviour.gif
  web_widget_domain_editor_dialog/static/src/js/domain_field.esm.js
  web_widget_domain_editor_dialog/static/src/js/widget_domain_editor_dialog.esm.js
Labels: approved, bot is merging ⏳

#2986 [17.0][ADD] web_pwa_customize: New module
  web_pwa_customize/README.rst
  web_pwa_customize/__init__.py
  web_pwa_customize/__manifest__.py
  web_pwa_customize/controllers/__init__.py
  web_pwa_customize/controllers/webmanifest.py
  web_pwa_customize/i18n/es.po
  web_pwa_customize/i18n/web_pwa_customize.pot
  web_pwa_customize/models/__init__.py
  web_pwa_customize/models/res_config_settings.py
  web_pwa_customize/pyproject.toml
  web_pwa_customize/readme/CONFIGURE.md
  web_pwa_customize/readme/CONTEXT.md
  web_pwa_customize/readme/CONTRIBUTORS.md
  web_pwa_customize/readme/DESCRIPTION.md
  web_pwa_customize/static/description/icon.png
  web_pwa_customize/static/description/index.html
  web_pwa_customize/tests/__init__.py
  web_pwa_customize/tests/test_web_pwa_customize.py
  web_pwa_customize/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#3015 [16.0][ADD] web_systray_button_init_action: New module to go to users defined action
  setup/web_systray_button_init_action/odoo/addons/web_systray_button_init_action
  setup/web_systray_button_init_action/setup.py
  web_pivot_computed_measure/tests/test_ui_pivot.py
  web_systray_button_init_action/README.rst
  web_systray_button_init_action/__init__.py
  web_systray_button_init_action/__manifest__.py
  web_systray_button_init_action/readme/CONFIGURE.rst
  web_systray_button_init_action/readme/CONTRIBUTORS.rst
  web_systray_button_init_action/readme/DESCRIPTION.rst
  web_systray_button_init_action/static/description/index.html
  web_systray_button_init_action/static/src/button/button.esm.js
  web_systray_button_init_action/static/src/button/button.xml
  web_systray_button_init_action/static/src/tours/tour.esm.js
  web_systray_button_init_action/tests/__init__.py
  web_systray_button_init_action/tests/test_web_systray_button_init_action.py
Labels: approved, ready to merge, bot is merging ⏳

#3237 [18.0][FIX] web_responsive: Tours that uses showAppsMenuItem are failing and click everywhere not working
  web_responsive/README.rst
  web_responsive/__manifest__.py
  web_responsive/static/description/index.html
  web_responsive/static/src/clickbot/clickbot.esm.js
  web_responsive/static/tests/test_patch.esm.js
Labels: approved, bot is merging ⏳
