Repository OCA/web, pull requests merged in 2025-05, with the labels that each got.

#3166 [18.0][FIX] web_company_color: fix navbar buttons color
  web_company_color/models/res_company.py
Labels: approved, bot is merging ⏳

#3133 [18.0][MIG] web_filter_header_button: Migration to 18.0
  web_filter_header_button/README.rst
  web_filter_header_button/__init__.py
  web_filter_header_button/__manifest__.py
  web_filter_header_button/demo/ir_module_module_view.xml
  web_filter_header_button/i18n/web_filter_header_button.pot
  web_filter_header_button/pyproject.toml
  web_filter_header_button/readme/CONFIGURE.md
  web_filter_header_button/readme/CONTEXT.md
  web_filter_header_button/readme/CONTRIBUTORS.md
  web_filter_header_button/readme/DESCRIPTION.md
  web_filter_header_button/readme/ROADMAP.md
  web_filter_header_button/readme/USAGE.md
  web_filter_header_button/static/description/icon.png
  web_filter_header_button/static/description/index.html
  web_filter_header_button/static/src/control_panel/control_panel.xml
  web_filter_header_button/static/src/control_panel/control_panel_patch.esm.js
  web_filter_header_button/static/src/filter_button/filter_button.esm.js
  web_filter_header_button/static/src/filter_button/filter_button.xml
  web_filter_header_button/static/src/search/search_arch_parser_patch.esm.js
  web_filter_header_button/static/src/search/search_model_patch.esm.js
Labels: approved, bot is merging ⏳

#2923 [16.0][IMP] web_notify:t3894 Allow notify with sound
  web_notify/README.rst
  web_notify/__manifest__.py
  web_notify/models/res_users.py
  web_notify/readme/CONTRIBUTORS.rst
  web_notify/readme/USAGE.rst
  web_notify/static/description/index.html
  web_notify/static/src/components/audio_player.esm.js
  web_notify/static/src/components/audio_player.xml
  web_notify/static/src/js/services/notification_services.esm.js
  web_notify/static/src/services/effect_service.esm.js
  web_notify/static/src/services/notification_sound_service.esm.js
  web_notify/tests/test_res_users.py
Labels: approved, ready to merge, bot is merging ⏳

#2995 [15.0][ADD] web_excel_export_dynamic_expand
  setup/web_excel_export_dynamic_expand/odoo/addons/web_excel_export_dynamic_expand
  setup/web_excel_export_dynamic_expand/setup.py
  web_excel_export_dynamic_expand/README.rst
  web_excel_export_dynamic_expand/__init__.py
  web_excel_export_dynamic_expand/__manifest__.py
  web_excel_export_dynamic_expand/controllers/__init__.py
  web_excel_export_dynamic_expand/controllers/excel_export.py
  web_excel_export_dynamic_expand/readme/CONTRIBUTORS.rst
  web_excel_export_dynamic_expand/readme/DESCRIPTION.rst
  web_excel_export_dynamic_expand/static/description/index.html
  web_excel_export_dynamic_expand/static/src/js/data_export.esm.js
Labels: approved, bot is merging ⏳

#3164 [18.0][MIG] web_m2x_options: Migration to 18.0
  web_m2x_options/README.rst
  web_m2x_options/__init__.py
  web_m2x_options/__manifest__.py
  web_m2x_options/i18n/ar.po
  web_m2x_options/i18n/de.po
  web_m2x_options/i18n/es.po
  web_m2x_options/i18n/es_BO.po
  web_m2x_options/i18n/fi.po
  web_m2x_options/i18n/fr.po
  web_m2x_options/i18n/hr.po
  web_m2x_options/i18n/it.po
  web_m2x_options/i18n/nl.po
  web_m2x_options/i18n/nl_NL.po
  web_m2x_options/i18n/pt_BR.po
  web_m2x_options/i18n/sl.po
  web_m2x_options/i18n/tr.po
  web_m2x_options/i18n/web_m2x_options.pot
  web_m2x_options/i18n/zh_CN.po
  web_m2x_options/models/__init__.py
  web_m2x_options/models/ir_config_parameter.py
  web_m2x_options/models/ir_http.py
  web_m2x_options/pyproject.toml
  web_m2x_options/readme/CONTRIBUTORS.md
  web_m2x_options/readme/CREDITS.md
  web_m2x_options/readme/DESCRIPTION.md
  web_m2x_options/readme/ROADMAP.md
  web_m2x_options/readme/USAGE.md
  web_m2x_options/static/description/icon.png
  web_m2x_options/static/description/index.html
  web_m2x_options/static/src/components/base.xml
  web_m2x_options/static/src/components/form.esm.js
  web_m2x_options/static/src/views/fields/standard_field_props.esm.js
  web_m2x_options/tests/__init__.py
  web_m2x_options/tests/test_ir_config_parameter.py
Labels: approved, ready to merge, bot is merging ⏳

#3169 [17.0][FIX] web_timeline: Enable XSS filtering with whitelist for safer HTML rendering
  web_timeline/static/src/views/timeline/timeline_renderer.esm.js
Labels: approved, bot is merging ⏳

#3171 [17.0][FIX] web_timeline: Add <b> element to XSS whitelist for safer HTML rendering
  web_timeline/static/src/views/timeline/timeline_renderer.esm.js
Labels: approved, bot is merging ⏳

#3136 [18.0][MIG] web_timeline
  web_timeline/README.rst
  web_timeline/__init__.py
  web_timeline/__manifest__.py
  web_timeline/demo/ir_cron_view.xml
  web_timeline/i18n/de.po
  web_timeline/i18n/es.po
  web_timeline/i18n/fa.po
  web_timeline/i18n/fr.po
  web_timeline/i18n/he.po
  web_timeline/i18n/hr.po
  web_timeline/i18n/it.po
  web_timeline/i18n/nl_NL.po
  web_timeline/i18n/pt.po
  web_timeline/i18n/pt_BR.po
  web_timeline/i18n/tr.po
  web_timeline/i18n/web_timeline.pot
  web_timeline/i18n/zh_CN.po
  web_timeline/models/__init__.py
  web_timeline/models/ir_action.py
  web_timeline/models/ir_ui_view.py
  web_timeline/pyproject.toml
  web_timeline/readme/CONFIGURE.md
  web_timeline/readme/CONTRIBUTORS.md
  web_timeline/readme/DESCRIPTION.md
  web_timeline/readme/ROADMAP.md
  web_timeline/readme/USAGE.md
  web_timeline/static/description/icon.png
  web_timeline/static/description/index.html
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.css
  web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js
  web_timeline/static/src/views/timeline/timeline_arch_parser.esm.js
  web_timeline/static/src/views/timeline/timeline_canvas.esm.js
  web_timeline/static/src/views/timeline/timeline_canvas.scss
  web_timeline/static/src/views/timeline/timeline_controller.esm.js
  web_timeline/static/src/views/timeline/timeline_controller.xml
  web_timeline/static/src/views/timeline/timeline_model.esm.js
  web_timeline/static/src/views/timeline/timeline_renderer.esm.js
  web_timeline/static/src/views/timeline/timeline_renderer.xml
  web_timeline/static/src/views/timeline/timeline_view.esm.js
  web_timeline/static/src/views/timeline/timeline_view.scss
  web_timeline/static/tests/helpers.esm.js
  web_timeline/static/tests/web_timeline_arch_parser_tests.esm.js
  web_timeline/static/tests/web_timeline_view_tests.esm.js
  web_timeline/tests/__init__.py
  web_timeline/tests/test_web_timeline.py
Labels: approved, ready to merge, bot is merging ⏳

#3175 [18.0][FIX] web_timeline: avoid sorting by many2many fields
  web_timeline/static/src/views/timeline/timeline_model.esm.js
Labels: bot is merging ⏳

#3173 [MIG] web_widget_open_tab: Migration to 18.0
  web_widget_open_tab/README.rst
  web_widget_open_tab/__init__.py
  web_widget_open_tab/__manifest__.py
  web_widget_open_tab/demo/res_users_view.xml
  web_widget_open_tab/i18n/ca.po
  web_widget_open_tab/i18n/de.po
  web_widget_open_tab/i18n/es.po
  web_widget_open_tab/i18n/it.po
  web_widget_open_tab/i18n/ja.po
  web_widget_open_tab/i18n/pt_BR.po
  web_widget_open_tab/i18n/web_widget_open_tab.pot
  web_widget_open_tab/models/__init__.py
  web_widget_open_tab/models/ir_model.py
  web_widget_open_tab/models/ir_ui_view.py
  web_widget_open_tab/pyproject.toml
  web_widget_open_tab/readme/CONTRIBUTORS.md
  web_widget_open_tab/readme/DESCRIPTION.md
  web_widget_open_tab/readme/ROADMAP.md
  web_widget_open_tab/readme/USAGE.md
  web_widget_open_tab/static/description/icon.png
  web_widget_open_tab/static/description/index.html
  web_widget_open_tab/static/src/js/open_tab_widget.esm.js
  web_widget_open_tab/static/src/xml/open_tab_widget.xml
  web_widget_open_tab/tests/__init__.py
  web_widget_open_tab/tests/test_main.py
  web_widget_open_tab/views/ir_model_views.xml
Labels: approved, bot is merging ⏳

#3053 [16.0][IMP] web_widget_dropdown_dynamic: Change license
  web_widget_dropdown_dynamic/README.rst
  web_widget_dropdown_dynamic/__init__.py
  web_widget_dropdown_dynamic/__manifest__.py
  web_widget_dropdown_dynamic/static/description/index.html
Labels: approved, ready to merge, merged 🎉

#3174 [17.0][FIX]: web_widget_x2many_2d_matrix: limit options values to x2many fields.
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
Labels: approved, ready to merge, bot is merging ⏳
