Repository OCA/web, pull requests merged in 2025-02, with the labels that each got.

#3075 [16.0][IMP] web_responsive: Remove unnecessary calendar optimisation
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: approved, bot is merging ⏳

#3078 [15.0][IMP] web_m2x_options: use the correct context in search function
  web_m2x_options/static/src/js/form.js
Labels: bot is merging ⏳

#3077 [17.0][IMP] web_responsive: Remove unnecessary calendar optimisation
  web_responsive/static/src/legacy/scss/web_responsive.scss
Labels: approved, bot is merging ⏳

#3067 [14.0][IMP] web_m2x_options: add 'ignore_m2x_options' option
  web_m2x_options/README.rst
  web_m2x_options/readme/CONTRIBUTORS.rst
  web_m2x_options/readme/USAGE.rst
  web_m2x_options/static/src/js/form.js
Labels: approved, bot is merging ⏳

#3083 [16.0][FIX] web_widget_product_label_section_and_note: Use a flag to change the icon based on product visibility.
  web_widget_product_label_section_and_note/static/src/components/product_label_section_and_note_field/product_label_section_and_note_field.esm.js
Labels: bot is merging ⏳

#3086 [FIX][16.0] web_refresher: error when dom destroyed during timeout
  web_refresher/static/src/js/refresher.esm.js
Labels: approved, bot is merging ⏳

#3064 [17.0][IMP] web_company_color: change menu systray colors
  web_company_color/models/res_company.py
Labels: approved, ready to merge, bot is merging ⏳

#3088 [18.0][FIX] web_widget_numeric_step: remove odoo-module tag and fix sort-import
  web_widget_numeric_step/static/src/numeric_step.esm.js
Labels: approved, bot is merging ⏳

#3056 [18.0][MIG] web_chatter_postion: Migration to 18.0
  web_chatter_position/README.rst
  web_chatter_position/__init__.py
  web_chatter_position/__manifest__.py
  web_chatter_position/i18n/ca.po
  web_chatter_position/i18n/de.po
  web_chatter_position/i18n/es.po
  web_chatter_position/i18n/fr.po
  web_chatter_position/i18n/hr.po
  web_chatter_position/i18n/it.po
  web_chatter_position/i18n/nl.po
  web_chatter_position/i18n/pt_BR.po
  web_chatter_position/i18n/tr.po
  web_chatter_position/i18n/web_chatter_position.pot
  web_chatter_position/models/__init__.py
  web_chatter_position/models/res_users.py
  web_chatter_position/pyproject.toml
  web_chatter_position/readme/CONTRIBUTORS.md
  web_chatter_position/readme/DESCRIPTION.md
  web_chatter_position/readme/USAGE.md
  web_chatter_position/static/description/icon.png
  web_chatter_position/static/description/index.html
  web_chatter_position/static/src/js/web_chatter_position.esm.js
  web_chatter_position/static/src/scss/form_controller.scss
  web_chatter_position/static/src/scss/form_renderer.scss
  web_chatter_position/static/src/scss/form_statusbar.scss
  web_chatter_position/views/res_users.xml
  web_chatter_position/views/web.xml
Labels: approved, bot is merging ⏳

#3070 [14.0][IMP] web_tree_many2one_clickable: improved visualization
  web_tree_many2one_clickable/README.rst
  web_tree_many2one_clickable/readme/CONTRIBUTORS.rst
  web_tree_many2one_clickable/static/description/index.html
  web_tree_many2one_clickable/static/src/css/web_tree_many2one_clickable.scss
  web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
Labels: approved, bot is merging ⏳

#3096 [16.0][IMP] web_editor_class_selector: Order classes by sequence
  web_editor_class_selector/models/web_editor_class.py
  web_editor_class_selector/views/web_editor_class_views.xml
Labels: approved, bot is merging ⏳

#3097 [17.0][IMP] web_editor_class_selector: Order classes by sequence
  web_editor_class_selector/models/web_editor_class.py
  web_editor_class_selector/views/web_editor_class_views.xml
Labels: approved, bot is merging ⏳

#3098 [16.0][FIX] product_label_section_and_note_field: Update name directly before calling update to prevent a race condition.
  web_widget_product_label_section_and_note/static/src/components/product_label_section_and_note_field/product_label_section_and_note_field.esm.js
Labels: bot is merging ⏳

#3032 [18.0][MIG] web_widget_dropdown_dynamic: Migration to 18.0
  web_widget_dropdown_dynamic/README.rst
  web_widget_dropdown_dynamic/__init__.py
  web_widget_dropdown_dynamic/__manifest__.py
  web_widget_dropdown_dynamic/demo/ir_filters_view.xml
  web_widget_dropdown_dynamic/demo/ir_model_fields.xml
  web_widget_dropdown_dynamic/i18n/de.po
  web_widget_dropdown_dynamic/i18n/es.po
  web_widget_dropdown_dynamic/i18n/it.po
  web_widget_dropdown_dynamic/i18n/web_widget_dropdown_dynamic.pot
  web_widget_dropdown_dynamic/models/__init__.py
  web_widget_dropdown_dynamic/models/ir_filters.py
  web_widget_dropdown_dynamic/pyproject.toml
  web_widget_dropdown_dynamic/readme/CONTRIBUTORS.md
  web_widget_dropdown_dynamic/readme/CREDITS.md
  web_widget_dropdown_dynamic/readme/DESCRIPTION.md
  web_widget_dropdown_dynamic/readme/USAGE.md
  web_widget_dropdown_dynamic/static/description/icon.png
  web_widget_dropdown_dynamic/static/description/index.html
  web_widget_dropdown_dynamic/static/src/js/field_dynamic_dropdown.esm.js
  web_widget_dropdown_dynamic/static/tests/web_widget_dropdown_dynamic_tests.esm.js
Labels: approved, bot is merging ⏳

#3093 [17.0][IMP] web_widget_x2many_2d_matrix: Fix domain issue
  web_widget_x2many_2d_matrix/README.rst
  web_widget_x2many_2d_matrix/__manifest__.py
  web_widget_x2many_2d_matrix/readme/CONTRIBUTORS.md
  web_widget_x2many_2d_matrix/static/description/index.html
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_field/x2many_2d_matrix_field.xml
  web_widget_x2many_2d_matrix/static/src/components/x2many_2d_matrix_renderer/x2many_2d_matrix_renderer.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#3102 [18.0][MIG] web_disable_export_group: Migration to version 18.0
  web_disable_export_group/README.rst
  web_disable_export_group/__init__.py
  web_disable_export_group/__manifest__.py
  web_disable_export_group/i18n/es.po
  web_disable_export_group/i18n/hr.po
  web_disable_export_group/i18n/it.po
  web_disable_export_group/i18n/pt.po
  web_disable_export_group/i18n/web_disable_export_group.pot
  web_disable_export_group/i18n/zh_CN.po
  web_disable_export_group/models/__init__.py
  web_disable_export_group/models/ir_http.py
  web_disable_export_group/models/models.py
  web_disable_export_group/pyproject.toml
  web_disable_export_group/readme/CONFIGURE.md
  web_disable_export_group/readme/CONTRIBUTORS.md
  web_disable_export_group/readme/DESCRIPTION.md
  web_disable_export_group/readme/USAGE.md
  web_disable_export_group/security/groups.xml
  web_disable_export_group/security/ir.model.access.csv
  web_disable_export_group/static/description/icon.png
  web_disable_export_group/static/description/index.html
  web_disable_export_group/static/src/views/list/export_all/export_all.esm.js
  web_disable_export_group/static/tests/tours/web_disable_export_group_tour.esm.js
  web_disable_export_group/tests/__init__.py
  web_disable_export_group/tests/test_tour.py
Labels: approved, bot is merging ⏳

#3105 [17.0][FIX] web_responsive: Fix blank screen on search (support menus w/o xmlid)
  web_responsive/static/src/components/menu_canonical_searchbar/searchbar.xml
Labels: approved, bot is merging ⏳
